// File generated by font_compiler.py
// FONT_SANSSERIF8[] binary size: 2186
// Generated from https://raw.githubusercontent.com/robhagemans/hoard-of-bitfonts/master/windows/windows-3.1/ms-sans-serif-e/MS_Sans_Serif_8.yaff

#include <stdint.h>

const uint8_t FONT_SANSSERIF8[] = {
    /* Metadata block:
     * First glyph byte = 32
     * End glyph byte = 255
     * Ascent = 9
     * Shift-up = 2
     * Default/fallback glyph = 128
     */
    32, 255, 9, 2, 128,

    /* 32 [ ] SPACE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 0
     * Data length = 0
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 0, 0, 0,

    /* 33 [!] EXCLAMATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * .@.
     * ...
     * ...
     */
0, 3, 1, 2, 4, 73, 146, 4, 1,

    /* 34 ["] QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 2
     * .....
     * .....
     * .@..@
     * .@..@
     * .@..@
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     */
0, 5, 1, 2, 2, 41, 37,

    /* 35 [#] NUMBER SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * ..@..@.
     * ..@..@.
     * .@@@@@@
     * ..@..@.
     * ..@..@.
     * ..@..@.
     * .@@@@@@
     * ..@..@.
     * ..@..@.
     * .......
     * .......
     */
0, 7, 2, 2, 8, 137, 228, 39, 145, 72, 126, 18, 9,

    /* 36 [$] DOLLAR SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ...@..
     * ..@@@.
     * .@.@.@
     * .@.@..
     * ..@@..
     * ...@@.
     * ...@.@
     * .@.@.@
     * ..@@@.
     * ...@..
     * ......
     */
0, 6, 3, 2, 7, 225, 84, 133, 193, 80, 149, 67,

    /* 37 [%] PERCENT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * ..@@....
     * .@..@..@
     * ..@@..@.
     * .....@..
     * ....@...
     * ...@....
     * ..@..@@.
     * .@..@..@
     * .....@@.
     * ........
     * ........
     */
0, 8, 2, 2, 9, 131, 36, 19, 8, 4, 2, 153, 36, 24,

    /* 38 [&] AMPERSAND
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@...
     * .@.@..
     * .@.@..
     * ..@...
     * ..@...
     * .@.@.@
     * .@..@.
     * .@..@.
     * ..@@.@
     * ......
     * ......
     */
0, 6, 2, 2, 7, 161, 40, 4, 161, 74, 18, 11,

    /* 39 ['] APOSTROPHE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 1
     * ..
     * ..
     * .@
     * .@
     * .@
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     */
0, 2, 1, 2, 1, 21,

    /* 40 [(] LEFT PARENTHESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * ..@
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ..@
     */
0, 3, 2, 2, 4, 37, 73, 146, 68,

    /* 41 [)] RIGHT PARENTHESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * .@.
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * .@.
     */
0, 3, 1, 2, 4, 145, 36, 73, 82,

    /* 42 [*] ASTERISK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 3
     * Data length = 2
     * ....
     * ....
     * ....
     * .@.@
     * ..@.
     * .@.@
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     */
0, 4, 1, 3, 2, 37, 5,

    /* 43 [+] PLUS SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 5
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ......
     * ...@..
     * ...@..
     * .@@@@@
     * ...@..
     * ...@..
     * ......
     * ......
     * ......
     */
0, 6, 3, 5, 4, 65, 124, 4, 1,

    /* 44 [,] COMMA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 10
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ..@
     * .@.
     * ...
     */
0, 3, 2, 10, 1, 5,

    /* 45 [-] HYPHEN-MINUS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 7
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * .@@
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 7, 1, 3,

    /* 46 [.] FULL STOP
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 10
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * .@.
     * ...
     * ...
     */
0, 3, 1, 10, 1, 1,

    /* 47 [/] SOLIDUS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 4
     * Pixel start Y = 2
     * Data length = 5
     * .....
     * .....
     * ....@
     * ....@
     * ....@
     * ...@.
     * ...@.
     * ..@..
     * ..@..
     * .@...
     * .@...
     * .....
     * .....
     */
0, 5, 4, 2, 5, 33, 68, 136, 16, 33,

    /* 48 [0] DIGIT ZERO
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 2, 2, 7, 39, 138, 162, 40, 138, 34, 7,

    /* 49 [1] DIGIT ONE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ...@..
     * .@@@..
     * ...@..
     * ...@..
     * ...@..
     * ...@..
     * ...@..
     * ...@..
     * ...@..
     * ......
     * ......
     */
0, 6, 3, 2, 7, 113, 16, 4, 65, 16, 4, 1,

    /* 50 [2] DIGIT TWO
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .....@
     * .....@
     * ....@.
     * ...@..
     * ..@...
     * .@....
     * .@@@@@
     * ......
     * ......
     */
0, 6, 2, 2, 7, 39, 130, 32, 132, 16, 130, 15,

    /* 51 [3] DIGIT THREE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .....@
     * .....@
     * ...@@.
     * .....@
     * .....@
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 2, 2, 7, 39, 130, 32, 6, 130, 34, 7,

    /* 52 [4] DIGIT FOUR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 4
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ....@.
     * ...@@.
     * ...@@.
     * ..@.@.
     * ..@.@.
     * .@..@.
     * .@@@@@
     * ....@.
     * ....@.
     * ......
     * ......
     */
0, 6, 4, 2, 7, 97, 24, 69, 73, 62, 4, 1,

    /* 53 [5] DIGIT FIVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@@@@@
     * .@....
     * .@....
     * .@@@@.
     * .@...@
     * .....@
     * .....@
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 1, 2, 7, 95, 16, 60, 17, 4, 69, 14,

    /* 54 [6] DIGIT SIX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@....
     * .@....
     * .@@@@.
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 2, 2, 7, 39, 10, 130, 39, 138, 34, 7,

    /* 55 [7] DIGIT SEVEN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@@@@@
     * .....@
     * ....@.
     * ....@.
     * ...@..
     * ...@..
     * ..@...
     * ..@...
     * ..@...
     * ......
     * ......
     */
0, 6, 1, 2, 7, 31, 132, 32, 4, 33, 8, 2,

    /* 56 [8] DIGIT EIGHT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 2, 2, 7, 39, 138, 34, 39, 138, 34, 7,

    /* 57 [9] DIGIT NINE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * ..@@@@
     * .....@
     * .....@
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 2, 2, 7, 39, 138, 34, 15, 130, 34, 7,

    /* 58 [:] COLON
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 2
     * ...
     * ...
     * ...
     * ...
     * ...
     * .@.
     * ...
     * ...
     * ...
     * ...
     * .@.
     * ...
     * ...
     */
0, 3, 1, 5, 2, 1, 128,

    /* 59 [;] SEMICOLON
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 3
     * ...
     * ...
     * ...
     * ...
     * ...
     * ..@
     * ...
     * ...
     * ...
     * ...
     * ..@
     * .@.
     * ...
     */
0, 3, 2, 5, 3, 1, 128, 2,

    /* 60 [<] LESS-THAN SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 4
     * Pixel start Y = 4
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * ....@.
     * ...@..
     * ..@...
     * .@....
     * ..@...
     * ...@..
     * ....@.
     * ......
     * ......
     */
0, 6, 4, 4, 5, 33, 132, 64, 32, 16,

    /* 61 [=] EQUALS SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 6
     * Data length = 3
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * .@@@@@
     * ......
     * .@@@@@
     * ......
     * ......
     * ......
     * ......
     */
0, 6, 1, 6, 3, 31, 240, 1,

    /* 62 [>] GREATER-THAN SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * .@....
     * ..@...
     * ...@..
     * ....@.
     * ...@..
     * ..@...
     * .@....
     * ......
     * ......
     */
0, 6, 1, 4, 5, 129, 64, 32, 132, 16,

    /* 63 [?] QUESTION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .....@
     * .....@
     * ....@.
     * ...@..
     * ...@..
     * ......
     * ...@..
     * ......
     * ......
     */
0, 6, 2, 2, 7, 39, 130, 32, 132, 32, 0, 2,

    /* 64 [@] COMMERCIAL AT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 11
     * Pixel start X = 4
     * Pixel start Y = 2
     * Data length = 13
     * ...........
     * ...........
     * ....@@@@...
     * ..@@....@@.
     * ..@......@.
     * .@...@@@..@
     * .@..@..@..@
     * .@..@..@..@
     * .@...@@.@@@
     * ..@........
     * ..@@.......
     * ....@@@@@..
     * ...........
     */
0, 11, 4, 2, 13, 15, 134, 17, 72, 156, 146, 148, 164, 216, 9, 192, 0, 248,

    /* 65 [A] LATIN CAPITAL LETTER A
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * ...@...
     * ...@...
     * ..@.@..
     * ..@.@..
     * .@...@.
     * .@...@.
     * .@@@@@.
     * @.....@
     * @.....@
     * .......
     * .......
     */
0, 7, 3, 2, 8, 129, 160, 80, 68, 34, 95, 48, 8,

    /* 66 [B] LATIN CAPITAL LETTER B
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * .@@@@..
     * .@...@.
     * .@...@.
     * .@...@.
     * .@@@@..
     * .@...@.
     * .@...@.
     * .@...@.
     * .@@@@..
     * .......
     * .......
     */
0, 7, 1, 2, 8, 143, 72, 36, 242, 136, 68, 34, 15,

    /* 67 [C] LATIN CAPITAL LETTER C
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * ..@@@@.
     * .@....@
     * .@.....
     * .@.....
     * .@.....
     * .@.....
     * .@.....
     * .@....@
     * ..@@@@.
     * .......
     * .......
     */
0, 7, 2, 2, 8, 79, 40, 16, 8, 4, 2, 33, 15,

    /* 68 [D] LATIN CAPITAL LETTER D
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@@@@...
     * .@...@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@...@..
     * .@@@@...
     * ........
     * ........
     */
0, 8, 1, 2, 9, 15, 17, 33, 33, 33, 33, 33, 17, 15,

    /* 69 [E] LATIN CAPITAL LETTER E
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * .@@@@@.
     * .@.....
     * .@.....
     * .@.....
     * .@@@@..
     * .@.....
     * .@.....
     * .@.....
     * .@@@@@.
     * .......
     * .......
     */
0, 7, 1, 2, 8, 159, 64, 32, 240, 8, 4, 2, 31,

    /* 70 [F] LATIN CAPITAL LETTER F
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@@@@@
     * .@....
     * .@....
     * .@....
     * .@@@@.
     * .@....
     * .@....
     * .@....
     * .@....
     * ......
     * ......
     */
0, 6, 1, 2, 7, 95, 16, 4, 79, 16, 4, 1,

    /* 71 [G] LATIN CAPITAL LETTER G
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * ..@@@@..
     * .@....@.
     * .@......
     * .@......
     * .@..@@@.
     * .@....@.
     * .@....@.
     * .@...@@.
     * ..@@@.@.
     * ........
     * ........
     */
0, 8, 2, 2, 9, 143, 144, 128, 128, 156, 144, 144, 24, 23,

    /* 72 [H] LATIN CAPITAL LETTER H
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@@@@@@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ........
     * ........
     */
0, 8, 1, 2, 9, 33, 33, 33, 33, 63, 33, 33, 33, 33,

    /* 73 [I] LATIN CAPITAL LETTER I
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 1, 2, 4, 73, 146, 36, 1,

    /* 74 [J] LATIN CAPITAL LETTER J
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 5
     * .....
     * .....
     * ...@.
     * ...@.
     * ...@.
     * ...@.
     * ...@.
     * ...@.
     * @..@.
     * @..@.
     * .@@..
     * .....
     * .....
     */
0, 5, 3, 2, 5, 33, 132, 16, 74, 201,

    /* 75 [K] LATIN CAPITAL LETTER K
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * .@...@.
     * .@..@..
     * .@.@...
     * .@@....
     * .@@....
     * .@.@...
     * .@..@..
     * .@...@.
     * .@....@
     * .......
     * .......
     */
0, 7, 1, 2, 8, 145, 68, 97, 48, 40, 36, 34, 33,

    /* 76 [L] LATIN CAPITAL LETTER L
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@....
     * .@....
     * .@....
     * .@....
     * .@....
     * .@....
     * .@....
     * .@....
     * .@@@@@
     * ......
     * ......
     */
0, 6, 1, 2, 7, 65, 16, 4, 65, 16, 4, 31,

    /* 77 [M] LATIN CAPITAL LETTER M
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 10
     * .........
     * .........
     * .@.....@.
     * .@.....@.
     * .@@...@@.
     * .@@...@@.
     * .@.@.@.@.
     * .@.@.@.@.
     * .@..@..@.
     * .@..@..@.
     * .@.....@.
     * .........
     * .........
     */
0, 9, 1, 2, 10, 65, 130, 140, 25, 83, 165, 74, 146, 36, 65,

    /* 78 [N] LATIN CAPITAL LETTER N
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@....@.
     * .@@...@.
     * .@@...@.
     * .@.@..@.
     * .@.@..@.
     * .@..@.@.
     * .@...@@.
     * .@...@@.
     * .@....@.
     * ........
     * ........
     */
0, 8, 1, 2, 9, 33, 35, 35, 37, 37, 41, 49, 49, 33,

    /* 79 [O] LATIN CAPITAL LETTER O
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 2, 2, 9, 143, 144, 144, 144, 144, 144, 144, 16, 15,

    /* 80 [P] LATIN CAPITAL LETTER P
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * .@@@@@.
     * .@....@
     * .@....@
     * .@....@
     * .@@@@@.
     * .@.....
     * .@.....
     * .@.....
     * .@.....
     * .......
     * .......
     */
0, 7, 1, 2, 8, 159, 80, 40, 244, 9, 4, 2, 1,

    /* 81 [Q] LATIN CAPITAL LETTER Q
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 10
     * ........
     * ........
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@..@.@.
     * .@...@@.
     * ..@@@@..
     * ......@.
     * ........
     */
0, 8, 2, 2, 10, 143, 144, 144, 144, 144, 144, 148, 24, 15, 16,

    /* 82 [R] LATIN CAPITAL LETTER R
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ........
     * ........
     */
0, 8, 1, 2, 9, 31, 33, 33, 33, 31, 33, 33, 33, 33,

    /* 83 [S] LATIN CAPITAL LETTER S
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * ..@@@..
     * .@...@.
     * .@.....
     * .@.....
     * ..@@@..
     * .....@.
     * .....@.
     * .@...@.
     * ..@@@..
     * .......
     * .......
     */
0, 7, 2, 2, 8, 71, 36, 16, 112, 64, 32, 17, 7,

    /* 84 [T] LATIN CAPITAL LETTER T
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * .@@@@@.
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * .......
     * .......
     */
0, 7, 1, 2, 8, 31, 2, 129, 64, 32, 16, 8, 4,

    /* 85 [U] LATIN CAPITAL LETTER U
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 1, 2, 9, 33, 33, 33, 33, 33, 33, 33, 33, 30,

    /* 86 [V] LATIN CAPITAL LETTER V
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * @.....@
     * @.....@
     * .@...@.
     * .@...@.
     * .@...@.
     * ..@.@..
     * ..@.@..
     * ...@...
     * ...@...
     * .......
     * .......
     */
0, 7, 0, 2, 8, 193, 160, 72, 36, 162, 80, 16, 8,

    /* 87 [W] LATIN CAPITAL LETTER W
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 11
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 12
     * ...........
     * ...........
     * @.........@
     * @.........@
     * .@...@...@.
     * .@...@...@.
     * .@...@...@.
     * ..@.@.@.@..
     * ..@.@.@.@..
     * ...@...@...
     * ...@...@...
     * ...........
     * ...........
     */
0, 11, 0, 2, 12, 1, 12, 160, 136, 68, 36, 34, 170, 80, 5, 17, 136,

    /* 88 [X] LATIN CAPITAL LETTER X
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * @.....@
     * @.....@
     * .@...@.
     * ..@.@..
     * ...@...
     * ..@.@..
     * .@...@.
     * @.....@
     * @.....@
     * .......
     * .......
     */
0, 7, 0, 2, 8, 193, 160, 136, 130, 160, 136, 130, 65,

    /* 89 [Y] LATIN CAPITAL LETTER Y
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * @.....@
     * @.....@
     * .@...@.
     * ..@.@..
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * .......
     * .......
     */
0, 7, 0, 2, 8, 193, 160, 136, 130, 64, 32, 16, 8,

    /* 90 [Z] LATIN CAPITAL LETTER Z
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * @@@@@@@
     * ......@
     * .....@.
     * ....@..
     * ...@...
     * ..@....
     * .@.....
     * @......
     * @@@@@@@
     * .......
     * .......
     */
0, 7, 0, 2, 8, 127, 32, 8, 130, 32, 8, 2, 127,

    /* 91 [[] LEFT SQUARE BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * .@@
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@@
     */
0, 3, 1, 2, 4, 75, 146, 36, 201,

    /* 92 [\] REVERSE SOLIDUS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * .@...
     * .@...
     * .@...
     * ..@..
     * ..@..
     * ...@.
     * ...@.
     * ....@
     * ....@
     * .....
     * .....
     */
0, 5, 1, 2, 6, 33, 4, 33, 8, 65, 8,

    /* 93 []] RIGHT SQUARE BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * .@@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * .@@
     */
0, 3, 1, 2, 4, 147, 36, 73, 210,

    /* 94 [^] CIRCUMFLEX ACCENT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 2
     * ......
     * ...@..
     * ..@.@.
     * .@...@
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     */
0, 6, 3, 1, 2, 161, 68,

    /* 95 [_] LOW LINE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 0
     * Pixel start Y = 12
     * Data length = 1
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * @@@@@@
     */
0, 6, 0, 12, 1, 63,

    /* 96 [`] GRAVE ACCENT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 1
     * ...
     * ...
     * .@.
     * ..@
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 2, 1, 17,

    /* 97 [a] LATIN SMALL LETTER A
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * ......
     * ..@@@.
     * .....@
     * ..@@@@
     * .@...@
     * .@...@
     * ..@@@@
     * ......
     * ......
     */
0, 6, 2, 5, 5, 7, 242, 162, 200, 3,

    /* 98 [b] LATIN SMALL LETTER B
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@....
     * .@....
     * .@....
     * .@@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * .@@@@.
     * ......
     * ......
     */
0, 6, 1, 2, 7, 65, 16, 60, 81, 20, 69, 15,

    /* 99 [c] LATIN SMALL LETTER C
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@....
     * .@....
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 2, 5, 5, 39, 10, 130, 200, 1,

    /* 100 [d] LATIN SMALL LETTER D
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 5
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .....@
     * .....@
     * .....@
     * ..@@@@
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@@
     * ......
     * ......
     */
0, 6, 5, 2, 7, 65, 144, 23, 69, 81, 228, 1,

    /* 101 [e] LATIN SMALL LETTER E
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@@@@@
     * .@....
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 2, 5, 5, 39, 250, 130, 200, 1,

    /* 102 [f] LATIN SMALL LETTER F
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * ..@
     * .@.
     * .@.
     * .@@
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 2, 2, 3, 37, 75, 146,

    /* 103 [g] LATIN SMALL LETTER G
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 6
     * ......
     * ......
     * ......
     * ......
     * ......
     * ..@@@@
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@@
     * .....@
     * .@@@@.
     */
0, 6, 2, 5, 6, 47, 138, 162, 200, 131, 30,

    /* 104 [h] LATIN SMALL LETTER H
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@....
     * .@....
     * .@....
     * .@.@@.
     * .@@..@
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ......
     * ......
     */
0, 6, 1, 2, 7, 65, 16, 52, 83, 20, 69, 17,

    /* 105 [i] LATIN SMALL LETTER I
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ..
     * ..
     * .@
     * ..
     * ..
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     * ..
     */
0, 2, 1, 2, 3, 65, 85, 1,

    /* 106 [j] LATIN SMALL LETTER J
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ..
     * ..
     * .@
     * ..
     * ..
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     */
0, 2, 1, 2, 3, 65, 85, 21,

    /* 107 [k] LATIN SMALL LETTER K
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@....
     * .@....
     * .@....
     * .@..@.
     * .@.@..
     * .@@...
     * .@.@..
     * .@..@.
     * .@...@
     * ......
     * ......
     */
0, 6, 1, 2, 7, 65, 16, 36, 197, 80, 36, 17,

    /* 108 [l] LATIN SMALL LETTER L
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ..
     * ..
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     * ..
     */
0, 2, 1, 2, 3, 85, 85, 1,

    /* 109 [m] LATIN SMALL LETTER M
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 6
     * ........
     * ........
     * ........
     * ........
     * ........
     * .@@@.@@.
     * .@..@..@
     * .@..@..@
     * .@..@..@
     * .@..@..@
     * .@..@..@
     * ........
     * ........
     */
0, 8, 1, 5, 6, 55, 73, 73, 73, 73, 73,

    /* 110 [n] LATIN SMALL LETTER N
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * ......
     * .@.@@.
     * .@@..@
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ......
     * ......
     */
0, 6, 1, 5, 5, 205, 20, 69, 81, 4,

    /* 111 [o] LATIN SMALL LETTER O
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 2, 5, 5, 39, 138, 162, 200, 1,

    /* 112 [p] LATIN SMALL LETTER P
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 6
     * ......
     * ......
     * ......
     * ......
     * ......
     * .@@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * .@@@@.
     * .@....
     * .@....
     */
0, 6, 1, 5, 6, 79, 20, 69, 209, 19, 4,

    /* 113 [q] LATIN SMALL LETTER Q
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 6
     * ......
     * ......
     * ......
     * ......
     * ......
     * ..@@@@
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@@
     * .....@
     * .....@
     */
0, 6, 2, 5, 6, 47, 138, 162, 200, 131, 32,

    /* 114 [r] LATIN SMALL LETTER R
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 2
     * ...
     * ...
     * ...
     * ...
     * ...
     * .@@
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 1, 5, 2, 75, 146,

    /* 115 [s] LATIN SMALL LETTER S
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 4
     * .....
     * .....
     * .....
     * .....
     * .....
     * ..@@.
     * .@..@
     * ..@..
     * ...@.
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 2, 5, 4, 147, 4, 73, 6,

    /* 116 [t] LATIN SMALL LETTER T
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 3
     * Data length = 3
     * ...
     * ...
     * ...
     * .@.
     * .@.
     * .@@
     * .@.
     * .@.
     * .@.
     * .@.
     * ..@
     * ...
     * ...
     */
0, 3, 1, 3, 3, 201, 146, 68,

    /* 117 [u] LATIN SMALL LETTER U
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * ......
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * .@..@@
     * ..@@.@
     * ......
     * ......
     */
0, 6, 1, 5, 5, 81, 20, 69, 153, 5,

    /* 118 [v] LATIN SMALL LETTER V
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * ......
     * .@...@
     * .@...@
     * ..@.@.
     * ..@.@.
     * ...@..
     * ...@..
     * ......
     * ......
     */
0, 6, 1, 5, 5, 81, 164, 40, 4, 1,

    /* 119 [w] LATIN SMALL LETTER W
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 6
     * ........
     * ........
     * ........
     * ........
     * ........
     * .@..@..@
     * .@..@..@
     * .@.@.@.@
     * .@.@.@.@
     * ..@...@.
     * ..@...@.
     * ........
     * ........
     */
0, 8, 1, 5, 6, 73, 73, 85, 85, 34, 34,

    /* 120 [x] LATIN SMALL LETTER X
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 4
     * .....
     * .....
     * .....
     * .....
     * .....
     * .@..@
     * .@..@
     * ..@@.
     * ..@@.
     * .@..@
     * .@..@
     * .....
     * .....
     */
0, 5, 1, 5, 4, 41, 25, 147, 18,

    /* 121 [y] LATIN SMALL LETTER Y
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 5
     * .....
     * .....
     * .....
     * .....
     * .....
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * ..@..
     * ..@..
     * @@...
     */
0, 5, 1, 5, 5, 41, 165, 100, 132, 12,

    /* 122 [z] LATIN SMALL LETTER Z
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 4
     * .....
     * .....
     * .....
     * .....
     * .....
     * .@@@@
     * ....@
     * ...@.
     * ..@..
     * .@...
     * .@@@@
     * .....
     * .....
     */
0, 5, 1, 5, 4, 15, 17, 17, 30,

    /* 123 [{] LEFT CURLY BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 6
     * ....
     * ...@
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * .@..
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ...@
     * ....
     */
0, 4, 3, 1, 6, 137, 136, 132, 136, 8, 1,

    /* 124 [|] VERTICAL LINE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ..
     * ..
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     */
0, 2, 1, 2, 3, 85, 85, 5,

    /* 125 [}] RIGHT CURLY BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 1
     * Data length = 6
     * ....
     * .@..
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ...@
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * .@..
     * ....
     */
0, 4, 1, 1, 6, 33, 34, 66, 34, 34, 1,

    /* 126 [~] TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 3
     * Data length = 2
     * .......
     * .......
     * .......
     * ..@@..@
     * .@..@@.
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     */
0, 7, 2, 3, 2, 83, 6,

    /* 127 
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 3
     * Data length = 4
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
0, 3, 1, 3, 4, 219, 182, 109, 3,

    /* 128 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 129 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 130 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 131 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 132 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 133 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 134 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 135 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 136 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 137 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 138 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 139 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 140 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 141 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 142 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 143 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 144 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 145 [‘] LEFT SINGLE QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 3
     * Data length = 1
     * ...
     * ...
     * ...
     * ..@
     * .@.
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 2, 3, 1, 5,

    /* 146 [’] RIGHT SINGLE QUOTATION MARK
     * Duplicate of = 145 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * ..@
     * .@.
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
145,

    /* 147 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 148 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 149 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 150 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 151 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 152 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 153 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 154 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 155 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 156 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 157 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 158 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 159 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 160 [ ] NO-BREAK SPACE
     * Duplicate of = 32 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
32,

    /* 161 [¡] INVERTED EXCLAMATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 4
     * ...
     * ...
     * ...
     * ...
     * .@.
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     */
0, 3, 1, 4, 4, 65, 146, 36, 1,

    /* 162 [¢] CENT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 4
     * Pixel start Y = 4
     * Data length = 6
     * ......
     * ......
     * ......
     * ......
     * ....@.
     * ..@@@.
     * .@...@
     * .@....
     * .@....
     * .@...@
     * ..@@@.
     * ..@...
     * ......
     */
0, 6, 4, 4, 6, 113, 162, 32, 136, 28, 1,

    /* 163 [£] POUND SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@@..
     * .@..@.
     * .@....
     * ..@...
     * .@@@..
     * ..@...
     * .@....
     * .@....
     * .@@@@@
     * ......
     * ......
     */
0, 6, 2, 2, 7, 35, 9, 132, 67, 8, 130, 15,

    /* 164 [¤] CURRENCY SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * ......
     * ......
     * .@...@
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * .@...@
     * ......
     * ......
     * ......
     * ......
     */
0, 6, 1, 2, 6, 145, 19, 69, 145, 19, 1,

    /* 165 [¥] YEN SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@...@
     * .@...@
     * .@...@
     * ..@.@.
     * .@@@@@
     * ...@..
     * .@@@@@
     * ...@..
     * ...@..
     * ......
     * ......
     */
0, 6, 1, 2, 7, 81, 20, 41, 31, 241, 17, 4,

    /* 166 [¦] BROKEN BAR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ..
     * ..
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     * .@
     * .@
     * .@
     * .@
     * .@
     */
0, 2, 1, 2, 3, 85, 81, 21,

    /* 167 [§] SECTION SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 8
     * ......
     * ......
     * ..@@@.
     * .@...@
     * ..@...
     * .@.@..
     * .@..@.
     * ..@..@
     * ...@.@
     * ....@.
     * .@...@
     * ..@@@.
     * ......
     */
0, 6, 2, 2, 8, 39, 18, 138, 68, 162, 144, 200, 1,

    /* 168 [¨] DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 3
     * Data length = 1
     * ...
     * ...
     * ...
     * @.@
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 0, 3, 1, 5,

    /* 169 [©] COPYRIGHT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 8
     * .........
     * .........
     * ...@@@@..
     * ..@....@.
     * .@..@@..@
     * .@.@....@
     * .@..@@..@
     * ..@....@.
     * ...@@@@..
     * .........
     * .........
     * .........
     * .........
     */
0, 9, 3, 2, 8, 15, 33, 153, 10, 101, 18, 194, 3,

    /* 170 [ª] FEMININE ORDINAL INDICATOR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ....
     * ....
     * .@@.
     * ..@@
     * .@.@
     * .@@@
     * ....
     * .@@@
     * ....
     * ....
     * ....
     * ....
     * ....
     */
0, 4, 1, 2, 3, 99, 117, 112,

    /* 171 [«] LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 6
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ...@.@
     * ..@.@.
     * .@.@..
     * ..@.@.
     * ...@.@
     * ......
     * ......
     */
0, 6, 3, 6, 4, 165, 20, 10, 5,

    /* 172 [¬] NOT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 7
     * Data length = 2
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * .@@@@@
     * .....@
     * ......
     * ......
     * ......
     * ......
     */
0, 6, 1, 7, 2, 31, 4,

    /* 173 SOFT HYPHEN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 6
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * .@@
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 6, 1, 3,

    /* 174 [®] REGISTERED SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 7
     * ........
     * ........
     * ...@@@..
     * ..@...@.
     * .@.@@@.@
     * .@.@@..@
     * .@.@.@.@
     * ..@...@.
     * ...@@@..
     * ........
     * ........
     * ........
     * ........
     */
0, 8, 3, 2, 7, 135, 72, 87, 83, 149, 8, 7,

    /* 175 [¯] MACRON
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 0
     * Pixel start Y = 1
     * Data length = 1
     * ......
     * @@@@@@
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     */
0, 6, 0, 1, 1, 63,

    /* 176 [°] DEGREE SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 2
     * ....
     * ....
     * ..@.
     * .@.@
     * ..@.
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     */
0, 4, 2, 2, 2, 41, 1,

    /* 177 [±] PLUS-MINUS SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 4
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * ...@..
     * ...@..
     * .@@@@@
     * ...@..
     * ...@..
     * ......
     * .@@@@@
     * ......
     * ......
     */
0, 6, 3, 4, 5, 65, 124, 4, 1, 124,

    /* 178 [²] SUPERSCRIPT TWO
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 2
     * ...
     * ...
     * @@.
     * ..@
     * .@.
     * @..
     * @@@
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 0, 2, 2, 163, 114,

    /* 179 [³] SUPERSCRIPT THREE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 2
     * ...
     * ...
     * @@.
     * ..@
     * .@.
     * ..@
     * @@.
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 0, 2, 2, 163, 56,

    /* 180 [´] ACUTE ACCENT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 1
     * ...
     * ...
     * ..@
     * .@.
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 2, 2, 1, 5,

    /* 181 [µ] MICRO SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 6
     * ......
     * ......
     * ......
     * ......
     * ......
     * .@..@.
     * .@..@.
     * .@..@.
     * .@..@.
     * .@..@.
     * .@@@.@
     * .@....
     * .@....
     */
0, 6, 1, 5, 6, 73, 146, 36, 201, 21, 4,

    /* 182 [¶] PILCROW SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 8
     * ......
     * ......
     * ..@@@@
     * .@@@@@
     * .@@@@@
     * .@@@@@
     * ..@@@@
     * ...@.@
     * ...@.@
     * ...@.@
     * ...@.@
     * ...@.@
     * ......
     */
0, 6, 2, 2, 8, 239, 251, 62, 143, 162, 40, 138, 2,

    /* 183 [·] MIDDLE DOT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 6
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * .@.
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 6, 1, 1,

    /* 184 [¸] CEDILLA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 11
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ..@
     * .@@
     */
0, 3, 2, 11, 1, 13,

    /* 185 [¹] SUPERSCRIPT ONE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 2
     * ...
     * ...
     * ..@
     * .@@
     * ..@
     * ..@
     * ..@
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 2, 2, 2, 77, 18,

    /* 186 [º] MASCULINE ORDINAL INDICATOR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ....
     * ....
     * .@@@
     * .@.@
     * .@.@
     * .@@@
     * ....
     * .@@@
     * ....
     * ....
     * ....
     * ....
     * ....
     */
0, 4, 1, 2, 3, 87, 117, 112,

    /* 187 [»] RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 6
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * .@.@..
     * ..@.@.
     * ...@.@
     * ..@.@.
     * .@.@..
     * ......
     * ......
     */
0, 6, 1, 6, 4, 133, 66, 41, 5,

    /* 188 [¼] VULGAR FRACTION ONE QUARTER
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * ..@.....
     * .@@....@
     * ..@...@.
     * ..@..@..
     * ..@.@..@
     * ...@..@@
     * ..@..@.@
     * .@...@@@
     * .......@
     * ........
     * ........
     */
0, 8, 2, 2, 9, 129, 33, 17, 9, 37, 50, 169, 56, 32,

    /* 189 [½] VULGAR FRACTION ONE HALF
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * ..@.....
     * .@@....@
     * ..@...@.
     * ..@..@..
     * ..@.@@@.
     * ...@...@
     * ..@...@.
     * .@...@..
     * .....@@@
     * ........
     * ........
     */
0, 8, 2, 2, 9, 129, 33, 17, 9, 29, 34, 145, 8, 56,

    /* 190 [¾] VULGAR FRACTION THREE QUARTERS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@@.....
     * ...@...@
     * ..@...@.
     * ...@.@..
     * .@@.@..@
     * ...@..@@
     * ..@..@.@
     * .@...@@@
     * .......@
     * ........
     * ........
     */
0, 8, 1, 2, 9, 3, 68, 34, 20, 75, 100, 82, 113, 64,

    /* 191 [¿] INVERTED QUESTION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 4
     * Data length = 7
     * ......
     * ......
     * ......
     * ......
     * ...@..
     * ......
     * ...@..
     * ...@..
     * ..@...
     * .@....
     * .@....
     * .@...@
     * ..@@@.
     */
0, 6, 3, 4, 7, 1, 16, 132, 16, 4, 145, 3,

    /* 192 [À] LATIN CAPITAL LETTER A WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 10
     * ..@....
     * ...@...
     * ...@...
     * ...@...
     * ..@.@..
     * ..@.@..
     * .@...@.
     * .@...@.
     * .@@@@@.
     * @.....@
     * @.....@
     * .......
     * .......
     */
0, 7, 2, 0, 10, 1, 129, 64, 80, 40, 34, 145, 47, 24, 4,

    /* 193 [Á] LATIN CAPITAL LETTER A WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 10
     * ....@..
     * ...@...
     * ...@...
     * ...@...
     * ..@.@..
     * ..@.@..
     * .@...@.
     * .@...@.
     * .@@@@@.
     * @.....@
     * @.....@
     * .......
     * .......
     */
0, 7, 4, 0, 10, 65, 32, 16, 20, 138, 72, 228, 11, 6, 1,

    /* 194 [Â] LATIN CAPITAL LETTER A WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 10
     * ...@...
     * ..@.@..
     * .......
     * ...@...
     * ..@.@..
     * ..@.@..
     * .@...@.
     * .@...@.
     * .@@@@@.
     * @.....@
     * @.....@
     * .......
     * .......
     */
0, 7, 3, 0, 10, 65, 1, 32, 40, 20, 145, 200, 23, 12, 2,

    /* 195 [Ã] LATIN CAPITAL LETTER A WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 10
     * ..@@.@.
     * .@.@@..
     * ...@...
     * ...@...
     * ..@.@..
     * ..@.@..
     * .@...@.
     * .@...@.
     * .@@@@@.
     * @.....@
     * @.....@
     * .......
     * .......
     */
0, 7, 2, 0, 10, 75, 131, 64, 80, 40, 34, 145, 47, 24, 4,

    /* 196 [Ä] LATIN CAPITAL LETTER A WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 0
     * Data length = 10
     * .@...@.
     * .......
     * ...@...
     * ...@...
     * ..@.@..
     * ..@.@..
     * .@...@.
     * .@...@.
     * .@@@@@.
     * @.....@
     * @.....@
     * .......
     * .......
     */
0, 7, 1, 0, 10, 17, 0, 129, 160, 80, 68, 34, 95, 48, 8,

    /* 197 [Å] LATIN CAPITAL LETTER A WITH RING ABOVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 10
     * ...@...
     * ..@.@..
     * ...@...
     * ...@...
     * ..@.@..
     * ..@.@..
     * .@...@.
     * .@...@.
     * .@@@@@.
     * @.....@
     * @.....@
     * .......
     * .......
     */
0, 7, 3, 0, 10, 65, 65, 32, 40, 20, 145, 200, 23, 12, 2,

    /* 198 [Æ] LATIN CAPITAL LETTER AE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 11
     * ..........
     * ..........
     * ...@@@@@@.
     * ...@@.....
     * ..@.@.....
     * ..@.@.....
     * .@..@@@@..
     * .@@@@.....
     * .@..@.....
     * @...@.....
     * @...@@@@@.
     * ..........
     * ..........
     */
0, 10, 3, 2, 11, 63, 12, 40, 160, 64, 30, 15, 36, 136, 32, 62,

    /* 199 [Ç] LATIN CAPITAL LETTER C WITH CEDILLA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 10
     * .......
     * .......
     * ..@@@@.
     * .@....@
     * .@.....
     * .@.....
     * .@.....
     * .@.....
     * .@.....
     * .@....@
     * ..@@@@.
     * ....@..
     * ...@@..
     */
0, 7, 2, 2, 10, 79, 40, 16, 8, 4, 2, 33, 15, 130, 1,

    /* 200 [È] LATIN CAPITAL LETTER E WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 10
     * ..@....
     * ...@...
     * .@@@@@.
     * .@.....
     * .@.....
     * .@.....
     * .@@@@..
     * .@.....
     * .@.....
     * .@.....
     * .@@@@@.
     * .......
     * .......
     */
0, 7, 2, 0, 10, 1, 225, 19, 8, 4, 30, 129, 64, 224, 3,

    /* 201 [É] LATIN CAPITAL LETTER E WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 9
     * ....@..
     * ...@...
     * .@@@@@.
     * .@.....
     * .@.....
     * .@.....
     * .@@@@..
     * .@.....
     * .@.....
     * .@.....
     * .@@@@@.
     * .......
     * .......
     */
0, 7, 4, 0, 9, 65, 248, 4, 2, 129, 71, 32, 16, 248,

    /* 202 [Ê] LATIN CAPITAL LETTER E WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 10
     * ...@...
     * ..@.@..
     * .@@@@@.
     * .@.....
     * .@.....
     * .@.....
     * .@@@@..
     * .@.....
     * .@.....
     * .@.....
     * .@@@@@.
     * .......
     * .......
     */
0, 7, 3, 0, 10, 65, 241, 9, 4, 2, 143, 64, 32, 240, 1,

    /* 203 [Ë] LATIN CAPITAL LETTER E WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 0
     * Data length = 10
     * .@...@.
     * .......
     * .@@@@@.
     * .@.....
     * .@.....
     * .@.....
     * .@@@@..
     * .@.....
     * .@.....
     * .@.....
     * .@@@@@.
     * .......
     * .......
     */
0, 7, 1, 0, 10, 17, 192, 39, 16, 8, 60, 2, 129, 192, 7,

    /* 204 [Ì] LATIN CAPITAL LETTER I WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 0
     * Data length = 4
     * @..
     * .@.
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 0, 0, 4, 17, 36, 73, 146,

    /* 205 [Í] LATIN CAPITAL LETTER I WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 4
     * ..@
     * .@.
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 2, 0, 4, 5, 73, 146, 36,

    /* 206 [Î] LATIN CAPITAL LETTER I WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 0
     * Data length = 4
     * .@.
     * @.@
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 1, 0, 4, 21, 146, 36, 73,

    /* 207 [Ï] LATIN CAPITAL LETTER I WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 0
     * Data length = 4
     * @.@
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 0, 0, 4, 133, 36, 73, 146,

    /* 208 [Ð] LATIN CAPITAL LETTER ETH
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@@@@...
     * .@...@..
     * .@....@.
     * .@....@.
     * @@@@..@.
     * .@....@.
     * .@....@.
     * .@...@..
     * .@@@@...
     * ........
     * ........
     */
0, 8, 1, 2, 9, 15, 17, 33, 161, 39, 33, 33, 17, 15,

    /* 209 [Ñ] LATIN CAPITAL LETTER N WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 11
     * ..@@..@.
     * .@..@@..
     * .@....@.
     * .@@...@.
     * .@@...@.
     * .@.@..@.
     * .@.@..@.
     * .@..@.@.
     * .@...@@.
     * .@...@@.
     * .@....@.
     * ........
     * ........
     */
0, 8, 2, 0, 11, 147, 140, 144, 145, 145, 146, 146, 148, 152, 152, 16,

    /* 210 [Ò] LATIN CAPITAL LETTER O WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 11
     * ...@....
     * ....@...
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 3, 0, 11, 1, 130, 71, 72, 72, 72, 72, 72, 72, 136, 7,

    /* 211 [Ó] LATIN CAPITAL LETTER O WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 11
     * ....@...
     * ...@....
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 4, 0, 11, 129, 192, 35, 36, 36, 36, 36, 36, 36, 196, 3,

    /* 212 [Ô] LATIN CAPITAL LETTER O WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 11
     * ...@@...
     * ..@..@..
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 3, 0, 11, 131, 132, 71, 72, 72, 72, 72, 72, 72, 136, 7,

    /* 213 [Õ] LATIN CAPITAL LETTER O WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 11
     * ..@@..@.
     * .@..@@..
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 2, 0, 11, 147, 12, 143, 144, 144, 144, 144, 144, 144, 16, 15,

    /* 214 [Ö] LATIN CAPITAL LETTER O WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 11
     * ..@..@..
     * ........
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 2, 0, 11, 9, 0, 143, 144, 144, 144, 144, 144, 144, 16, 15,

    /* 215 [×] MULTIPLICATION SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ......
     * .@...@
     * ..@.@.
     * ...@..
     * ..@.@.
     * .@...@
     * ......
     * ......
     * ......
     */
0, 6, 1, 5, 4, 145, 66, 40, 17,

    /* 216 [Ø] LATIN CAPITAL LETTER O WITH STROKE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * ..@@@@@.
     * .@...@@.
     * .@..@.@.
     * .@..@.@.
     * .@.@..@.
     * .@.@..@.
     * .@@...@.
     * .@@...@.
     * .@@@@@..
     * ........
     * ........
     */
0, 8, 2, 2, 9, 159, 152, 148, 148, 146, 146, 145, 145, 15,

    /* 217 [Ù] LATIN CAPITAL LETTER U WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 11
     * ...@....
     * ....@...
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 3, 0, 11, 1, 66, 72, 72, 72, 72, 72, 72, 72, 136, 7,

    /* 218 [Ú] LATIN CAPITAL LETTER U WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 11
     * ....@...
     * ...@....
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 4, 0, 11, 129, 32, 36, 36, 36, 36, 36, 36, 36, 196, 3,

    /* 219 [Û] LATIN CAPITAL LETTER U WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 11
     * ...@@...
     * ..@..@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 3, 0, 11, 131, 68, 72, 72, 72, 72, 72, 72, 72, 136, 7,

    /* 220 [Ü] LATIN CAPITAL LETTER U WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 11
     * ..@..@..
     * ........
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 2, 0, 11, 9, 128, 144, 144, 144, 144, 144, 144, 144, 16, 15,

    /* 221 [Ý] LATIN CAPITAL LETTER Y WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 9
     * ....@..
     * ...@...
     * @.....@
     * @.....@
     * .@...@.
     * ..@.@..
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * .......
     * .......
     */
0, 7, 4, 0, 9, 65, 4, 131, 34, 10, 2, 129, 64, 32,

    /* 222 [Þ] LATIN CAPITAL LETTER THORN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * .@.....
     * .@.....
     * .@@@@@.
     * .@....@
     * .@....@
     * .@....@
     * .@@@@@.
     * .@.....
     * .@.....
     * .......
     * .......
     */
0, 7, 1, 2, 8, 129, 192, 39, 20, 10, 125, 2, 1,

    /* 223 [ß] LATIN SMALL LETTER SHARP S
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@@..
     * .@..@.
     * .@..@.
     * .@..@.
     * .@.@@.
     * .@...@
     * .@...@
     * .@...@
     * .@.@@.
     * ......
     * ......
     */
0, 6, 2, 2, 7, 35, 73, 146, 38, 138, 162, 6,

    /* 224 [à] LATIN SMALL LETTER A WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@...
     * ...@..
     * ......
     * ..@@@.
     * .....@
     * ..@@@@
     * .@...@
     * .@...@
     * ..@@@@
     * ......
     * ......
     */
0, 6, 2, 2, 7, 129, 0, 28, 200, 139, 34, 15,

    /* 225 [á] LATIN SMALL LETTER A WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 4
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ....@.
     * ...@..
     * ......
     * ..@@@.
     * .....@
     * ..@@@@
     * .@...@
     * .@...@
     * ..@@@@
     * ......
     * ......
     */
0, 6, 4, 2, 7, 33, 0, 7, 242, 162, 200, 3,

    /* 226 [â] LATIN SMALL LETTER A WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ...@..
     * ..@.@.
     * ......
     * ..@@@.
     * .....@
     * ..@@@@
     * .@...@
     * .@...@
     * ..@@@@
     * ......
     * ......
     */
0, 6, 3, 2, 7, 161, 0, 14, 228, 69, 145, 7,

    /* 227 [ã] LATIN SMALL LETTER A WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@@.@
     * .@.@@.
     * ......
     * ..@@@.
     * .....@
     * ..@@@@
     * .@...@
     * .@...@
     * ..@@@@
     * ......
     * ......
     */
0, 6, 2, 2, 7, 171, 1, 28, 200, 139, 34, 15,

    /* 228 [ä] LATIN SMALL LETTER A WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@..@
     * ......
     * ......
     * ..@@@.
     * .....@
     * ..@@@@
     * .@...@
     * .@...@
     * ..@@@@
     * ......
     * ......
     */
0, 6, 2, 2, 7, 9, 0, 28, 200, 139, 34, 15,

    /* 229 [å] LATIN SMALL LETTER A WITH RING ABOVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 8
     * ......
     * ...@..
     * ..@.@.
     * ...@..
     * ......
     * ..@@@.
     * .....@
     * ..@@@@
     * .@...@
     * .@...@
     * ..@@@@
     * ......
     * ......
     */
0, 6, 3, 1, 8, 161, 16, 128, 3, 121, 81, 228, 1,

    /* 230 [æ] LATIN SMALL LETTER AE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 8
     * ..........
     * ..........
     * ..........
     * ..........
     * ..........
     * ..@@@.@@@.
     * .....@...@
     * ..@@@@@@@@
     * .@...@....
     * .@...@...@
     * ..@@@.@@@.
     * ..........
     * ..........
     */
0, 10, 2, 5, 8, 119, 32, 242, 47, 130, 136, 220, 1,

    /* 231 [ç] LATIN SMALL LETTER C WITH CEDILLA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 6
     * ......
     * ......
     * ......
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@....
     * .@....
     * .@...@
     * ..@@@.
     * ...@..
     * ..@@..
     */
0, 6, 2, 5, 6, 39, 10, 130, 200, 33, 12,

    /* 232 [è] LATIN SMALL LETTER E WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@...
     * ...@..
     * ......
     * ..@@@.
     * .@...@
     * .@@@@@
     * .@....
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 2, 2, 7, 129, 0, 156, 232, 11, 34, 7,

    /* 233 [é] LATIN SMALL LETTER E WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 4
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ....@.
     * ...@..
     * ......
     * ..@@@.
     * .@...@
     * .@@@@@
     * .@....
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 4, 2, 7, 33, 0, 39, 250, 130, 200, 1,

    /* 234 [ê] LATIN SMALL LETTER E WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ...@..
     * ..@.@.
     * ......
     * ..@@@.
     * .@...@
     * .@@@@@
     * .@....
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 3, 2, 7, 161, 0, 78, 244, 5, 145, 3,

    /* 235 [ë] LATIN SMALL LETTER E WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@...@
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@@@@@
     * .@....
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 1, 2, 7, 17, 0, 56, 209, 23, 68, 14,

    /* 236 [ì] LATIN SMALL LETTER I WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 3
     * ..
     * ..
     * @.
     * .@
     * ..
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     * ..
     */
0, 2, 0, 2, 3, 137, 170, 2,

    /* 237 [í] LATIN SMALL LETTER I WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 4
     * ....
     * ....
     * ...@
     * ..@.
     * ....
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ....
     * ....
     */
0, 4, 3, 2, 4, 9, 136, 136, 136,

    /* 238 [î] LATIN SMALL LETTER I WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ....
     * ....
     * ..@.
     * .@.@
     * ....
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ....
     * ....
     */
0, 4, 2, 2, 5, 41, 16, 17, 17, 1,

    /* 239 [ï] LATIN SMALL LETTER I WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 5
     * ....
     * ....
     * .@.@
     * ....
     * ....
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ....
     * ....
     */
0, 4, 1, 2, 5, 5, 32, 34, 34, 2,

    /* 240 [ð] LATIN SMALL LETTER ETH
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@.@.
     * ...@..
     * ..@.@.
     * ....@.
     * ..@@@@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 2, 2, 7, 133, 80, 16, 47, 138, 34, 7,

    /* 241 [ñ] LATIN SMALL LETTER N WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@@.@
     * .@.@@.
     * ......
     * .@.@@.
     * .@@..@
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ......
     * ......
     */
0, 6, 2, 2, 7, 171, 1, 154, 41, 138, 162, 8,

    /* 242 [ò] LATIN SMALL LETTER O WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@...
     * ...@..
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 2, 2, 7, 129, 0, 156, 40, 138, 34, 7,

    /* 243 [ó] LATIN SMALL LETTER O WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 4
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ....@.
     * ...@..
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 4, 2, 7, 33, 0, 39, 138, 162, 200, 1,

    /* 244 [ô] LATIN SMALL LETTER O WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ...@..
     * ..@.@.
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 3, 2, 7, 161, 0, 78, 20, 69, 145, 3,

    /* 245 [õ] LATIN SMALL LETTER O WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@@.@
     * .@.@@.
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 2, 2, 7, 171, 1, 156, 40, 138, 34, 7,

    /* 246 [ö] LATIN SMALL LETTER O WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@...@
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     * ......
     */
0, 6, 1, 2, 7, 17, 0, 56, 81, 20, 69, 14,

    /* 247 [÷] DIVISION SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 5
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ......
     * ...@..
     * ......
     * .@@@@@
     * ......
     * ...@..
     * ......
     * ......
     * ......
     */
0, 6, 3, 5, 4, 1, 124, 0, 1,

    /* 248 [ø] LATIN SMALL LETTER O WITH STROKE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * ......
     * ..@@@@
     * .@..@@
     * .@.@.@
     * .@.@.@
     * .@@..@
     * .@@@@.
     * ......
     * ......
     */
0, 6, 2, 5, 5, 47, 171, 170, 233, 1,

    /* 249 [ù] LATIN SMALL LETTER U WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@...
     * ...@..
     * ......
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * .@..@@
     * ..@@.@
     * ......
     * ......
     */
0, 6, 2, 2, 7, 129, 0, 162, 40, 138, 50, 11,

    /* 250 [ú] LATIN SMALL LETTER U WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 4
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ....@.
     * ...@..
     * ......
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * .@..@@
     * ..@@.@
     * ......
     * ......
     */
0, 6, 4, 2, 7, 33, 128, 40, 138, 162, 204, 2,

    /* 251 [û] LATIN SMALL LETTER U WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ...@..
     * ..@.@.
     * ......
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * .@..@@
     * ..@@.@
     * ......
     * ......
     */
0, 6, 3, 2, 7, 161, 0, 81, 20, 69, 153, 5,

    /* 252 [ü] LATIN SMALL LETTER U WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@...@
     * ......
     * ......
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * .@..@@
     * ..@@.@
     * ......
     * ......
     */
0, 6, 1, 2, 7, 17, 0, 68, 81, 20, 101, 22,

    /* 253 [ý] LATIN SMALL LETTER Y WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 7
     * .....
     * .....
     * ...@.
     * ..@..
     * .....
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * ..@..
     * ..@..
     * @@...
     */
0, 5, 3, 2, 7, 17, 32, 165, 148, 140, 144, 1,

    /* 254 [þ] LATIN SMALL LETTER THORN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * ......
     * ......
     * .@....
     * .@....
     * .@....
     * .@@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * .@@@@.
     * .@....
     * .@....
     */
0, 6, 1, 2, 8, 65, 16, 60, 81, 20, 69, 79, 16,

    /* 255 [ÿ] LATIN SMALL LETTER Y WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * .....
     * .....
     * .@..@
     * .....
     * .....
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * ..@..
     * ..@..
     * @@...
     */
0, 5, 1, 2, 7, 9, 128, 148, 82, 50, 66, 6,

};
