// File generated by font_compiler.py
// FONT_HELV8[] binary size: 1933

#include <stdint.h>

const uint8_t FONT_HELV8[] = {
    /* Metadata block:
     * First glyph byte = 32
     * End glyph byte = 255
     * Glyph height = 10
     * Default/fallback glyph = 80
     */
    32, 255, 10, 80,

    /* 32 [ ] SPACE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 0
     * Data length = 0
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 0, 0, 0,

    /* 33 [!] EXCLAMATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * .@.
     * ...
     */
0, 3, 1, 2, 3, 73, 18, 4,

    /* 34 ["] QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 2
     * .....
     * .....
     * .@..@
     * .@..@
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     */
0, 5, 1, 2, 2, 41, 1,

    /* 35 [#] NUMBER SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .......
     * .......
     * ..@..@.
     * ..@..@.
     * .@@@@@@
     * ..@..@.
     * .@@@@@@
     * ..@..@.
     * ..@..@.
     * .......
     */
0, 7, 2, 2, 6, 137, 228, 39, 249, 73, 36,

    /* 36 [$] DOLLAR SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 7
     * ......
     * ...@..
     * ..@@@.
     * .@.@.@
     * .@.@..
     * ..@@@.
     * ...@.@
     * .@.@.@
     * ..@@@.
     * ...@..
     */
0, 6, 3, 1, 7, 225, 84, 133, 67, 85, 14, 1,

    /* 37 [%] PERCENT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ........
     * ........
     * ..@@...@
     * .@..@.@.
     * ..@@.@..
     * ....@...
     * ...@.@@.
     * ..@.@..@
     * .@...@@.
     * ........
     */
0, 8, 2, 2, 7, 163, 20, 11, 4, 26, 165, 24,

    /* 38 [&] AMPERSAND
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ..@...
     * .@.@..
     * .@.@..
     * ..@...
     * .@.@.@
     * .@..@.
     * ..@@.@
     * ......
     */
0, 6, 2, 2, 5, 161, 40, 132, 42, 177,

    /* 39 ['] APOSTROPHE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 1
     * ..
     * ..
     * .@
     * .@
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     */
0, 2, 1, 2, 1, 5,

    /* 40 [(] LEFT PARENTHESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * ..@
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ..@
     */
0, 3, 2, 2, 3, 37, 73, 34,

    /* 41 [)] RIGHT PARENTHESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * .@.
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * .@.
     */
0, 3, 1, 2, 3, 145, 36, 41,

    /* 42 [*] ASTERISK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 2
     * ....
     * ....
     * .@.@
     * ..@.
     * .@.@
     * ....
     * ....
     * ....
     * ....
     * ....
     */
0, 4, 1, 2, 2, 37, 5,

    /* 43 [+] PLUS SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 3
     * Data length = 4
     * ......
     * ......
     * ......
     * ...@..
     * ...@..
     * .@@@@@
     * ...@..
     * ...@..
     * ......
     * ......
     */
0, 6, 3, 3, 4, 65, 124, 4, 1,

    /* 44 [,] COMMA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 8
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ..@
     * .@.
     */
0, 3, 2, 8, 1, 5,

    /* 45 [-] HYPHEN-MINUS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * .@@
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 5, 1, 3,

    /* 46 [.] FULL STOP
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 8
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * .@.
     * ...
     */
0, 3, 1, 8, 1, 1,

    /* 47 [/] SOLIDUS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 4
     * .....
     * .....
     * ...@.
     * ...@.
     * ..@..
     * ..@..
     * ..@..
     * .@...
     * .@...
     * .....
     */
0, 5, 3, 2, 4, 33, 66, 136, 16,

    /* 48 [0] DIGIT ZERO
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     */
0, 6, 2, 2, 5, 39, 138, 162, 40, 114,

    /* 49 [1] DIGIT ONE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ...@..
     * .@@@..
     * ...@..
     * ...@..
     * ...@..
     * ...@..
     * ...@..
     * ......
     */
0, 6, 3, 2, 5, 113, 16, 4, 65, 16,

    /* 50 [2] DIGIT TWO
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .....@
     * ....@.
     * ...@..
     * ..@...
     * .@@@@@
     * ......
     */
0, 6, 2, 2, 5, 39, 130, 16, 66, 248,

    /* 51 [3] DIGIT THREE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .....@
     * ...@@.
     * .....@
     * .@...@
     * ..@@@.
     * ......
     */
0, 6, 2, 2, 5, 39, 130, 24, 40, 114,

    /* 52 [4] DIGIT FOUR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 4
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ....@.
     * ...@@.
     * ..@.@.
     * .@..@.
     * .@@@@@
     * ....@.
     * ....@.
     * ......
     */
0, 6, 4, 2, 5, 97, 148, 228, 67, 16,

    /* 53 [5] DIGIT FIVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * .@@@@@
     * .@....
     * .@@@@.
     * .@...@
     * .....@
     * .@...@
     * ..@@@.
     * ......
     */
0, 6, 1, 2, 5, 95, 240, 68, 80, 228,

    /* 54 [6] DIGIT SIX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@....
     * .@@@@.
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     */
0, 6, 2, 2, 5, 39, 10, 158, 40, 114,

    /* 55 [7] DIGIT SEVEN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * .@@@@@
     * .....@
     * ....@.
     * ...@..
     * ..@...
     * ..@...
     * ..@...
     * ......
     */
0, 6, 1, 2, 5, 31, 132, 16, 130, 32,

    /* 56 [8] DIGIT EIGHT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * ..@@@.
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     */
0, 6, 2, 2, 5, 39, 138, 156, 40, 114,

    /* 57 [9] DIGIT NINE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * ..@@@@
     * .....@
     * .@...@
     * ..@@@.
     * ......
     */
0, 6, 2, 2, 5, 39, 138, 60, 40, 114,

    /* 58 [:] COLON
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 2
     * ...
     * ...
     * ...
     * ...
     * .@.
     * ...
     * ...
     * ...
     * .@.
     * ...
     */
0, 3, 1, 4, 2, 1, 16,

    /* 59 [;] SEMICOLON
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 2
     * ...
     * ...
     * ...
     * ...
     * ..@
     * ...
     * ...
     * ...
     * ..@
     * .@.
     */
0, 3, 2, 4, 2, 1, 80,

    /* 60 [<] LESS-THAN SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 5
     * Pixel start Y = 3
     * Data length = 4
     * ......
     * ......
     * ......
     * .....@
     * ...@@.
     * .@@...
     * ...@@.
     * .....@
     * ......
     * ......
     */
0, 6, 5, 3, 4, 49, 3, 3, 1,

    /* 61 [=] EQUALS SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 3
     * ......
     * ......
     * ......
     * ......
     * .@@@@@
     * ......
     * .@@@@@
     * ......
     * ......
     * ......
     */
0, 6, 1, 4, 3, 31, 240, 1,

    /* 62 [>] GREATER-THAN SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 3
     * Data length = 4
     * ......
     * ......
     * ......
     * .@....
     * ..@@..
     * ....@@
     * ..@@..
     * .@....
     * ......
     * ......
     */
0, 6, 1, 3, 4, 129, 129, 25, 1,

    /* 63 [?] QUESTION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .....@
     * ....@.
     * ...@..
     * ......
     * ...@..
     * ......
     */
0, 6, 2, 2, 5, 39, 130, 16, 2, 32,

    /* 64 [@] COMMERCIAL AT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 11
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 11
     * ...........
     * ...........
     * ...@@@@@@..
     * ..@......@.
     * .@...@@@..@
     * .@..@..@..@
     * .@..@..@..@
     * .@...@@.@@.
     * ..@........
     * ...@@@@@@..
     */
0, 11, 3, 2, 11, 63, 4, 18, 167, 36, 37, 41, 54, 2, 224, 7,

    /* 65 [A] LATIN CAPITAL LETTER A
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 6
     * .......
     * .......
     * ...@...
     * ..@.@..
     * ..@.@..
     * .@...@.
     * .@@@@@.
     * @.....@
     * @.....@
     * .......
     */
0, 7, 3, 2, 6, 65, 161, 136, 124, 193, 32,

    /* 66 [B] LATIN CAPITAL LETTER B
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * .......
     * .......
     * .@@@@..
     * .@...@.
     * .@...@.
     * .@@@@..
     * .@...@.
     * .@...@.
     * .@@@@..
     * .......
     */
0, 7, 1, 2, 6, 143, 72, 228, 17, 137, 60,

    /* 67 [C] LATIN CAPITAL LETTER C
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .......
     * .......
     * ..@@@@.
     * .@....@
     * .@.....
     * .@.....
     * .@.....
     * .@....@
     * ..@@@@.
     * .......
     */
0, 7, 2, 2, 6, 79, 40, 16, 8, 132, 60,

    /* 68 [D] LATIN CAPITAL LETTER D
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ........
     * ........
     * .@@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@@@@@..
     * ........
     */
0, 8, 1, 2, 7, 31, 33, 33, 33, 33, 33, 31,

    /* 69 [E] LATIN CAPITAL LETTER E
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * .......
     * .......
     * .@@@@@.
     * .@.....
     * .@.....
     * .@@@@..
     * .@.....
     * .@.....
     * .@@@@@.
     * .......
     */
0, 7, 1, 2, 6, 159, 64, 224, 17, 8, 124,

    /* 70 [F] LATIN CAPITAL LETTER F
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * .@@@@@
     * .@....
     * .@....
     * .@@@@.
     * .@....
     * .@....
     * .@....
     * ......
     */
0, 6, 1, 2, 5, 95, 16, 60, 65, 16,

    /* 71 [G] LATIN CAPITAL LETTER G
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ........
     * ........
     * ..@@@@..
     * .@....@.
     * .@......
     * .@..@@@.
     * .@....@.
     * .@....@.
     * ..@@@@@.
     * ........
     */
0, 8, 2, 2, 7, 143, 144, 128, 156, 144, 16, 31,

    /* 72 [H] LATIN CAPITAL LETTER H
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ........
     * ........
     * .@....@.
     * .@....@.
     * .@....@.
     * .@@@@@@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ........
     */
0, 8, 1, 2, 7, 33, 33, 33, 63, 33, 33, 33,

    /* 73 [I] LATIN CAPITAL LETTER I
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     */
0, 3, 1, 2, 3, 73, 146, 4,

    /* 74 [J] LATIN CAPITAL LETTER J
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 4
     * .....
     * .....
     * ...@.
     * ...@.
     * ...@.
     * ...@.
     * ...@.
     * @..@.
     * .@@..
     * .....
     */
0, 5, 3, 2, 4, 33, 132, 80, 50,

    /* 75 [K] LATIN CAPITAL LETTER K
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * .......
     * .......
     * .@...@.
     * .@..@..
     * .@.@...
     * .@@@...
     * .@..@..
     * .@...@.
     * .@....@
     * .......
     */
0, 7, 1, 2, 6, 145, 68, 225, 144, 136, 132,

    /* 76 [L] LATIN CAPITAL LETTER L
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * ......
     * ......
     * .@....
     * .@....
     * .@....
     * .@....
     * .@....
     * .@....
     * .@@@@@
     * ......
     */
0, 6, 1, 2, 6, 65, 16, 4, 65, 240, 1,

    /* 77 [M] LATIN CAPITAL LETTER M
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * .........
     * .........
     * .@.....@.
     * .@@...@@.
     * .@@...@@.
     * .@.@.@.@.
     * .@.@.@.@.
     * .@..@..@.
     * .@..@..@.
     * .........
     */
0, 9, 1, 2, 8, 65, 198, 140, 169, 82, 37, 73, 18,

    /* 78 [N] LATIN CAPITAL LETTER N
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ........
     * ........
     * .@....@.
     * .@@...@.
     * .@.@..@.
     * .@.@..@.
     * .@..@.@.
     * .@...@@.
     * .@....@.
     * ........
     */
0, 8, 1, 2, 7, 33, 35, 37, 37, 41, 49, 33,

    /* 79 [O] LATIN CAPITAL LETTER O
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ........
     * ........
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     */
0, 8, 2, 2, 7, 143, 144, 144, 144, 144, 16, 15,

    /* 80 [P] LATIN CAPITAL LETTER P
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * .......
     * .......
     * .@@@@@.
     * .@....@
     * .@....@
     * .@@@@@.
     * .@.....
     * .@.....
     * .@.....
     * .......
     */
0, 7, 1, 2, 6, 159, 80, 232, 19, 8, 4,

    /* 81 [Q] LATIN CAPITAL LETTER Q
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@..@.@.
     * ..@@@@..
     * ......@.
     */
0, 8, 2, 2, 8, 143, 144, 144, 144, 144, 20, 15, 16,

    /* 82 [R] LATIN CAPITAL LETTER R
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ........
     * ........
     * .@@@@@..
     * .@....@.
     * .@....@.
     * .@@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * ........
     */
0, 8, 1, 2, 7, 31, 33, 33, 31, 33, 33, 33,

    /* 83 [S] LATIN CAPITAL LETTER S
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .......
     * .......
     * ..@@@..
     * .@...@.
     * .@.....
     * ..@@@..
     * .....@.
     * .@...@.
     * ..@@@..
     * .......
     */
0, 7, 2, 2, 6, 71, 36, 224, 128, 68, 28,

    /* 84 [T] LATIN CAPITAL LETTER T
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * .......
     * .......
     * .@@@@@.
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * .......
     */
0, 7, 1, 2, 6, 31, 2, 129, 64, 32, 16,

    /* 85 [U] LATIN CAPITAL LETTER U
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ........
     * ........
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     */
0, 8, 1, 2, 7, 33, 33, 33, 33, 33, 33, 30,

    /* 86 [V] LATIN CAPITAL LETTER V
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 6
     * .......
     * .......
     * @.....@
     * @.....@
     * .@...@.
     * .@...@.
     * ..@.@..
     * ..@.@..
     * ...@...
     * .......
     */
0, 7, 0, 2, 6, 193, 160, 72, 68, 161, 32,

    /* 87 [W] LATIN CAPITAL LETTER W
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 11
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 10
     * ...........
     * ...........
     * @.........@
     * @.........@
     * .@...@...@.
     * .@...@...@.
     * ..@.@.@.@..
     * ..@.@.@.@..
     * ...@...@...
     * ...........
     */
0, 11, 0, 2, 10, 1, 12, 160, 136, 68, 68, 21, 170, 32, 2,

    /* 88 [X] LATIN CAPITAL LETTER X
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * @.....@
     * .@...@.
     * ..@.@..
     * ...@...
     * ..@.@..
     * .@...@.
     * @.....@
     * .......
     */
0, 7, 0, 2, 7, 65, 17, 5, 65, 17, 5, 1,

    /* 89 [Y] LATIN CAPITAL LETTER Y
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 6
     * .......
     * .......
     * @.....@
     * .@...@.
     * ..@.@..
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * .......
     */
0, 7, 0, 2, 6, 65, 17, 5, 129, 64, 32,

    /* 90 [Z] LATIN CAPITAL LETTER Z
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * ......
     * ......
     * .@@@@@
     * .....@
     * ....@.
     * ...@..
     * ..@...
     * .@....
     * .@@@@@
     * ......
     */
0, 6, 1, 2, 6, 31, 132, 16, 66, 240, 1,

    /* 91 [[] LEFT SQUARE BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * .@@
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@@
     */
0, 3, 1, 2, 3, 75, 146, 100,

    /* 92 [\] REVERSE SOLIDUS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 5
     * .....
     * .....
     * .@...
     * .@...
     * ..@..
     * ..@..
     * ..@..
     * ...@.
     * ...@.
     * .....
     */
0, 5, 1, 2, 5, 33, 8, 33, 8, 1,

    /* 93 []] RIGHT SQUARE BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * .@@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * .@@
     */
0, 3, 1, 2, 3, 147, 36, 105,

    /* 94 [^] CIRCUMFLEX ACCENT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 2
     * ...@..
     * ..@.@.
     * .@...@
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     */
0, 6, 3, 0, 2, 161, 68,

    /* 95 [_] LOW LINE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 0
     * Pixel start Y = 9
     * Data length = 1
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * @@@@@@
     */
0, 6, 0, 9, 1, 63,

    /* 96 [`] GRAVE ACCENT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 1
     * Data length = 1
     * ...
     * .@.
     * ..@
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 1, 1, 17,

    /* 97 [a] LATIN SMALL LETTER A
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ..@@@.
     * .....@
     * ..@@@@
     * .@...@
     * ..@@@@
     * ......
     */
0, 6, 2, 4, 4, 7, 242, 34, 15,

    /* 98 [b] LATIN SMALL LETTER B
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * .@....
     * .@....
     * .@@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@@@@.
     * ......
     */
0, 6, 1, 2, 5, 65, 240, 68, 81, 244,

    /* 99 [c] LATIN SMALL LETTER C
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 3
     * .....
     * .....
     * .....
     * .....
     * ..@@@
     * .@...
     * .@...
     * .@...
     * ..@@@
     * .....
     */
0, 5, 2, 4, 3, 23, 66, 112,

    /* 100 [d] LATIN SMALL LETTER D
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 5
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * .....@
     * .....@
     * ..@@@@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@@
     * ......
     */
0, 6, 5, 2, 5, 65, 94, 20, 69, 30,

    /* 101 [e] LATIN SMALL LETTER E
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@@@@@
     * .@....
     * ..@@@.
     * ......
     */
0, 6, 2, 4, 4, 39, 250, 2, 7,

    /* 102 [f] LATIN SMALL LETTER F
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * ..@
     * .@.
     * .@@
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     */
0, 3, 2, 2, 3, 101, 73, 2,

    /* 103 [g] LATIN SMALL LETTER G
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * ..@@@@
     * .@...@
     * .@...@
     * ..@@@@
     * .....@
     * .@@@@.
     */
0, 6, 2, 4, 5, 47, 138, 60, 232, 1,

    /* 104 [h] LATIN SMALL LETTER H
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * ......
     * ......
     * .@....
     * .@....
     * .@@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ......
     */
0, 6, 1, 2, 6, 65, 240, 68, 81, 20, 1,

    /* 105 [i] LATIN SMALL LETTER I
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 2
     * ..
     * ..
     * .@
     * ..
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     */
0, 2, 1, 2, 2, 81, 21,

    /* 106 [j] LATIN SMALL LETTER J
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 2
     * ..
     * ..
     * .@
     * ..
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     */
0, 2, 1, 2, 2, 81, 85,

    /* 107 [k] LATIN SMALL LETTER K
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 5
     * .....
     * .....
     * .@...
     * .@...
     * .@..@
     * .@.@.
     * .@@@.
     * .@..@
     * .@..@
     * .....
     */
0, 5, 1, 2, 5, 33, 164, 114, 82, 2,

    /* 108 [l] LATIN SMALL LETTER L
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 2
     * ..
     * ..
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     */
0, 2, 1, 2, 2, 85, 21,

    /* 109 [m] LATIN SMALL LETTER M
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 5
     * ........
     * ........
     * ........
     * ........
     * .@@@.@@.
     * .@..@..@
     * .@..@..@
     * .@..@..@
     * .@..@..@
     * ........
     */
0, 8, 1, 4, 5, 55, 73, 73, 73, 73,

    /* 110 [n] LATIN SMALL LETTER N
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * .@@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ......
     */
0, 6, 1, 4, 4, 79, 20, 69, 17,

    /* 111 [o] LATIN SMALL LETTER O
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     */
0, 6, 2, 4, 4, 39, 138, 34, 7,

    /* 112 [p] LATIN SMALL LETTER P
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * .@@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@@@@.
     * .@....
     */
0, 6, 1, 4, 4, 79, 20, 69, 79,

    /* 113 [q] LATIN SMALL LETTER Q
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * ..@@@@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@@
     * .....@
     */
0, 6, 2, 4, 5, 47, 138, 34, 15, 2,

    /* 114 [r] LATIN SMALL LETTER R
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 2
     * ...
     * ...
     * ...
     * ...
     * .@@
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     */
0, 3, 1, 4, 2, 75, 18,

    /* 115 [s] LATIN SMALL LETTER S
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 3
     * .....
     * .....
     * .....
     * .....
     * ..@@@
     * .@...
     * ..@@.
     * ....@
     * .@@@.
     * .....
     */
0, 5, 2, 4, 3, 23, 12, 58,

    /* 116 [t] LATIN SMALL LETTER T
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 3
     * Data length = 3
     * ...
     * ...
     * ...
     * .@.
     * .@@
     * .@.
     * .@.
     * .@.
     * ..@
     * ...
     */
0, 3, 1, 3, 3, 89, 18, 1,

    /* 117 [u] LATIN SMALL LETTER U
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@@
     * ......
     */
0, 6, 1, 4, 4, 81, 20, 69, 30,

    /* 118 [v] LATIN SMALL LETTER V
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * .@...@
     * .@...@
     * .@...@
     * ..@.@.
     * ...@..
     * ......
     */
0, 6, 1, 4, 4, 81, 20, 41, 4,

    /* 119 [w] LATIN SMALL LETTER W
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 5
     * ........
     * ........
     * ........
     * ........
     * .@..@..@
     * .@..@..@
     * .@.@.@.@
     * ..@...@.
     * ..@...@.
     * ........
     */
0, 8, 1, 4, 5, 73, 73, 85, 34, 34,

    /* 120 [x] LATIN SMALL LETTER X
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 3
     * .....
     * .....
     * .....
     * .....
     * .@..@
     * .@..@
     * ..@@.
     * .@..@
     * .@..@
     * .....
     */
0, 5, 1, 4, 3, 41, 153, 148,

    /* 121 [y] LATIN SMALL LETTER Y
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 4
     * .....
     * .....
     * .....
     * .....
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * ..@..
     * @@...
     */
0, 5, 1, 4, 4, 41, 37, 35, 3,

    /* 122 [z] LATIN SMALL LETTER Z
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 3
     * .....
     * .....
     * .....
     * .....
     * .@@@@
     * ....@
     * ..@@.
     * .@...
     * .@@@@
     * .....
     */
0, 5, 1, 4, 3, 15, 153, 240,

    /* 123 [{] LEFT CURLY BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 5
     * ....
     * ...@
     * ..@.
     * ..@.
     * ..@.
     * .@..
     * ..@.
     * ..@.
     * ..@.
     * ...@
     */
0, 4, 3, 1, 5, 137, 72, 136, 8, 1,

    /* 124 [|] VERTICAL LINE
     * Duplicate of = 108 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ..
     * ..
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     */
108,

    /* 125 [}] RIGHT CURLY BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 1
     * Data length = 5
     * ....
     * .@..
     * ..@.
     * ..@.
     * ..@.
     * ...@
     * ..@.
     * ..@.
     * ..@.
     * .@..
     */
0, 4, 1, 1, 5, 33, 34, 36, 34, 1,

    /* 126 [~] TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 2
     * .......
     * .......
     * ..@@..@
     * .@..@@.
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     */
0, 7, 2, 2, 2, 83, 6,

    /* 127 
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
0, 3, 1, 2, 3, 219, 182, 13,

    /* 128 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 129 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 130 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 131 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 132 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 133 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 134 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 135 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 136 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 137 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 138 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 139 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 140 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 141 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 142 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 143 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 144 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 145 [‘] LEFT SINGLE QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 1
     * ...
     * ...
     * ..@
     * .@.
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 2, 2, 1, 5,

    /* 146 [’] RIGHT SINGLE QUOTATION MARK
     * Duplicate of = 145 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ..@
     * .@.
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
145,

    /* 147 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 148 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 149 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 150 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 151 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 152 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 153 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 154 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 155 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 156 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 157 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 158 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 159 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     */
127,

    /* 160 [ ] NO-BREAK SPACE
     * Duplicate of = 32 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
32,

    /* 161 [¡] INVERTED EXCLAMATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 3
     * Data length = 3
     * ...
     * ...
     * ...
     * .@.
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     */
0, 3, 1, 3, 3, 65, 146, 4,

    /* 162 [¢] CENT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 4
     * Pixel start Y = 3
     * Data length = 5
     * ......
     * ......
     * ......
     * ....@.
     * ..@@@.
     * .@...@
     * .@....
     * .@...@
     * ..@@@.
     * ..@...
     */
0, 6, 4, 3, 5, 113, 162, 32, 114, 4,

    /* 163 [£] POUND SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ..@@@.
     * .@...@
     * ..@...
     * .@@@..
     * ..@...
     * .@....
     * .@@@@@
     * ......
     */
0, 6, 2, 2, 5, 39, 18, 14, 33, 248,

    /* 164 [¤] CURRENCY SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * .@...@
     * ..@@@.
     * .@...@
     * .@...@
     * ..@@@.
     * .@...@
     * ......
     * ......
     */
0, 6, 1, 2, 5, 145, 19, 69, 78, 4,

    /* 165 [¥] YEN SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * .@...@
     * .@...@
     * ..@.@.
     * ...@..
     * .@@@@@
     * ...@..
     * ...@..
     * ......
     */
0, 6, 1, 2, 5, 81, 164, 16, 31, 65,

    /* 166 [¦] BROKEN BAR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 2
     * ..
     * ..
     * .@
     * .@
     * .@
     * ..
     * ..
     * .@
     * .@
     * .@
     */
0, 2, 1, 2, 2, 21, 84,

    /* 167 [§] SECTION SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * ......
     * ......
     * ..@@@.
     * .@...@
     * ..@@..
     * .@..@.
     * ..@..@
     * ...@@.
     * .@...@
     * ..@@@.
     */
0, 6, 2, 2, 6, 39, 50, 18, 137, 137, 28,

    /* 168 [¨] DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 1
     * ...
     * ...
     * @.@
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 0, 2, 1, 5,

    /* 169 [©] COPYRIGHT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 8
     * ..........
     * ..........
     * ...@@@@...
     * ..@....@..
     * .@..@@..@.
     * .@.@....@.
     * .@..@@..@.
     * ..@....@..
     * ...@@@@...
     * ..........
     */
0, 10, 3, 2, 8, 15, 66, 100, 82, 72, 38, 66, 240,

    /* 170 [ª] FEMININE ORDINAL INDICATOR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 1
     * Data length = 3
     * ....
     * .@@.
     * ..@@
     * .@.@
     * .@@@
     * ....
     * .@@@
     * ....
     * ....
     * ....
     */
0, 4, 1, 1, 3, 99, 117, 112,

    /* 171 [«] LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 4
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ...@.@
     * ..@.@.
     * .@.@..
     * ..@.@.
     * ...@.@
     * ......
     */
0, 6, 3, 4, 4, 165, 20, 10, 5,

    /* 172 [¬] NOT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 2
     * ......
     * ......
     * ......
     * ......
     * ......
     * .@@@@@
     * .....@
     * ......
     * ......
     * ......
     */
0, 6, 1, 5, 2, 31, 4,

    /* 173 SOFT HYPHEN
     * Duplicate of = 45 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * ...
     * ...
     * .@@
     * ...
     * ...
     * ...
     * ...
     */
45,

    /* 174 [®] REGISTERED SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 7
     * ........
     * ........
     * ...@@@..
     * ..@...@.
     * .@.@@@.@
     * .@.@@..@
     * .@.@.@.@
     * ..@...@.
     * ...@@@..
     * ........
     */
0, 8, 3, 2, 7, 135, 72, 87, 83, 149, 8, 7,

    /* 175 [¯] MACRON
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 0
     * Pixel start Y = 0
     * Data length = 1
     * @@@@@@
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     */
0, 6, 0, 0, 1, 63,

    /* 176 [°] DEGREE SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 2
     * ....
     * ....
     * ..@.
     * .@.@
     * ..@.
     * ....
     * ....
     * ....
     * ....
     * ....
     */
0, 4, 2, 2, 2, 41, 1,

    /* 177 [±] PLUS-MINUS SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ...@..
     * ...@..
     * .@@@@@
     * ...@..
     * ...@..
     * ......
     * .@@@@@
     * ......
     */
0, 6, 3, 2, 5, 65, 124, 4, 1, 124,

    /* 178 [²] SUPERSCRIPT TWO
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 1
     * Data length = 2
     * ...
     * @@.
     * ..@
     * .@.
     * @..
     * @@@
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 0, 1, 2, 163, 114,

    /* 179 [³] SUPERSCRIPT THREE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 1
     * Data length = 2
     * ...
     * @@.
     * ..@
     * .@.
     * ..@
     * @@.
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 0, 1, 2, 163, 56,

    /* 180 [´] ACUTE ACCENT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 1
     * ...
     * ..@
     * .@.
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 2, 1, 1, 5,

    /* 181 [µ] MICRO SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * .@..@.
     * .@..@.
     * .@..@.
     * .@..@.
     * .@@@.@
     * .@....
     */
0, 6, 1, 4, 4, 73, 146, 36, 87,

    /* 182 [¶] PILCROW SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * ......
     * ......
     * ..@@@@
     * .@@@@@
     * .@@@@@
     * ..@@@@
     * ...@.@
     * ...@.@
     * ...@.@
     * ...@.@
     */
0, 6, 2, 2, 6, 239, 251, 60, 138, 162, 40,

    /* 183 [·] MIDDLE DOT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * .@.
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 5, 1, 1,

    /* 184 [¸] CEDILLA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 8
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ..@
     * .@@
     */
0, 3, 2, 8, 1, 13,

    /* 185 [¹] SUPERSCRIPT ONE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 2
     * ...
     * ..@
     * .@@
     * ..@
     * ..@
     * ..@
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 2, 1, 2, 77, 18,

    /* 186 [º] MASCULINE ORDINAL INDICATOR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ....
     * ....
     * .@@@
     * .@.@
     * .@@@
     * ....
     * .@@@
     * ....
     * ....
     * ....
     */
0, 4, 1, 2, 3, 87, 7, 7,

    /* 187 [»] RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * .@.@..
     * ..@.@.
     * ...@.@
     * ..@.@.
     * .@.@..
     * ......
     */
0, 6, 1, 4, 4, 133, 66, 41, 5,

    /* 188 [¼] VULGAR FRACTION ONE QUARTER
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 9
     * ........
     * ..@.....
     * .@@....@
     * ..@...@.
     * ..@..@..
     * ..@.@..@
     * ...@..@@
     * ..@..@.@
     * .@...@@@
     * .......@
     */
0, 8, 2, 1, 9, 129, 33, 17, 9, 37, 50, 169, 56, 32,

    /* 189 [½] VULGAR FRACTION ONE HALF
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 9
     * ........
     * ..@.....
     * .@@....@
     * ..@...@.
     * ..@..@..
     * ..@.@@@.
     * ...@...@
     * ..@...@.
     * .@...@..
     * .....@@@
     */
0, 8, 2, 1, 9, 129, 33, 17, 9, 29, 34, 145, 8, 56,

    /* 190 [¾] VULGAR FRACTION THREE QUARTERS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * .@@....@
     * ...@..@.
     * ..@..@..
     * ...@@..@
     * .@@@..@@
     * ..@..@.@
     * .@...@@@
     * .......@
     */
0, 8, 1, 2, 8, 67, 36, 18, 76, 103, 82, 113, 64,

    /* 191 [¿] INVERTED QUESTION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 3
     * Data length = 5
     * ......
     * ......
     * ......
     * ...@..
     * ......
     * ...@..
     * ..@...
     * .@....
     * .@...@
     * ..@@@.
     */
0, 6, 3, 3, 5, 1, 16, 66, 16, 57,

    /* 192 [À] LATIN CAPITAL LETTER A WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 8
     * ..@....
     * ...@...
     * ...@...
     * ..@.@..
     * ..@.@..
     * .@...@.
     * .@@@@@.
     * @.....@
     * @.....@
     * .......
     */
0, 7, 2, 0, 8, 1, 129, 160, 80, 68, 190, 96, 16,

    /* 193 [Á] LATIN CAPITAL LETTER A WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 8
     * ....@..
     * ...@...
     * ...@...
     * ..@.@..
     * ..@.@..
     * .@...@.
     * .@@@@@.
     * @.....@
     * @.....@
     * .......
     */
0, 7, 4, 0, 8, 65, 32, 40, 20, 145, 47, 24, 4,

    /* 194 [Â] LATIN CAPITAL LETTER A WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 8
     * ...@...
     * ..@.@..
     * ...@...
     * ..@.@..
     * ..@.@..
     * .@...@.
     * .@@@@@.
     * @.....@
     * @.....@
     * .......
     */
0, 7, 3, 0, 8, 65, 65, 80, 40, 34, 95, 48, 8,

    /* 195 [Ã] LATIN CAPITAL LETTER A WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 8
     * ..@@.@.
     * .@.@@..
     * ...@...
     * ..@.@..
     * ..@.@..
     * .@...@.
     * .@@@@@.
     * @.....@
     * @.....@
     * .......
     */
0, 7, 2, 0, 8, 75, 131, 160, 80, 68, 190, 96, 16,

    /* 196 [Ä] LATIN CAPITAL LETTER A WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 0
     * Data length = 8
     * .@...@.
     * .......
     * ...@...
     * ..@.@..
     * ..@.@..
     * .@...@.
     * .@@@@@.
     * @.....@
     * @.....@
     * .......
     */
0, 7, 1, 0, 8, 17, 0, 65, 161, 136, 124, 193, 32,

    /* 197 [Å] LATIN CAPITAL LETTER A WITH RING ABOVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 8
     * ..@@@..
     * ..@.@..
     * ..@@@..
     * ..@.@..
     * ..@.@..
     * .@...@.
     * .@@@@@.
     * @.....@
     * @.....@
     * .......
     */
0, 7, 2, 0, 8, 135, 194, 161, 80, 68, 190, 96, 16,

    /* 198 [Æ] LATIN CAPITAL LETTER AE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 9
     * ..........
     * ..........
     * ...@@@@@@.
     * ..@.@.....
     * ..@.@.....
     * .@..@@@@..
     * .@@@@.....
     * @...@.....
     * @...@@@@@.
     * ..........
     */
0, 10, 3, 2, 9, 63, 10, 40, 144, 199, 131, 8, 226, 3,

    /* 199 [Ç] LATIN CAPITAL LETTER C WITH CEDILLA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * ..@@@@.
     * .@....@
     * .@.....
     * .@.....
     * .@.....
     * .@....@
     * ..@@@@.
     * ...@@..
     */
0, 7, 2, 2, 7, 79, 40, 16, 8, 132, 60, 12,

    /* 200 [È] LATIN CAPITAL LETTER E WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 8
     * ..@....
     * ...@...
     * .@@@@@.
     * .@.....
     * .@.....
     * .@@@@..
     * .@.....
     * .@.....
     * .@@@@@.
     * .......
     */
0, 7, 2, 0, 8, 1, 225, 19, 8, 60, 2, 129, 15,

    /* 201 [É] LATIN CAPITAL LETTER E WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 8
     * ....@..
     * ...@...
     * .@@@@@.
     * .@.....
     * .@.....
     * .@@@@..
     * .@.....
     * .@.....
     * .@@@@@.
     * .......
     */
0, 7, 4, 0, 8, 65, 248, 4, 2, 143, 64, 224, 3,

    /* 202 [Ê] LATIN CAPITAL LETTER E WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 8
     * ...@...
     * ..@.@..
     * .@@@@@.
     * .@.....
     * .@.....
     * .@@@@..
     * .@.....
     * .@.....
     * .@@@@@.
     * .......
     */
0, 7, 3, 0, 8, 65, 241, 9, 4, 30, 129, 192, 7,

    /* 203 [Ë] LATIN CAPITAL LETTER E WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 0
     * Data length = 8
     * .@...@.
     * .......
     * .@@@@@.
     * .@.....
     * .@.....
     * .@@@@..
     * .@.....
     * .@.....
     * .@@@@@.
     * .......
     */
0, 7, 1, 0, 8, 17, 192, 39, 16, 120, 4, 2, 31,

    /* 204 [Ì] LATIN CAPITAL LETTER I WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 0
     * Data length = 4
     * @..
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     */
0, 3, 0, 0, 4, 145, 36, 73, 2,

    /* 205 [Í] LATIN CAPITAL LETTER I WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 3
     * ..@
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     */
0, 3, 2, 0, 3, 37, 73, 146,

    /* 206 [Î] LATIN CAPITAL LETTER I WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 0
     * Data length = 4
     * .@.
     * @.@
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     */
0, 3, 1, 0, 4, 85, 146, 36, 1,

    /* 207 [Ï] LATIN CAPITAL LETTER I WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 0
     * Data length = 4
     * @.@
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     */
0, 3, 0, 0, 4, 133, 36, 73, 2,

    /* 208 [Ð] LATIN CAPITAL LETTER ETH
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ........
     * ........
     * .@@@@@..
     * .@....@.
     * .@....@.
     * @@@@..@.
     * .@....@.
     * .@....@.
     * .@@@@@..
     * ........
     */
0, 8, 1, 2, 7, 31, 33, 161, 39, 33, 33, 31,

    /* 209 [Ñ] LATIN CAPITAL LETTER N WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 9
     * ..@@..@.
     * .@..@@..
     * .@....@.
     * .@@...@.
     * .@.@..@.
     * .@.@..@.
     * .@..@.@.
     * .@...@@.
     * .@....@.
     * ........
     */
0, 8, 2, 0, 9, 147, 140, 144, 145, 146, 146, 148, 152, 16,

    /* 210 [Ò] LATIN CAPITAL LETTER O WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 9
     * ...@....
     * ....@...
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     */
0, 8, 3, 0, 9, 1, 130, 71, 72, 72, 72, 72, 136, 7,

    /* 211 [Ó] LATIN CAPITAL LETTER O WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 9
     * ....@...
     * ...@....
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     */
0, 8, 4, 0, 9, 129, 192, 35, 36, 36, 36, 36, 196, 3,

    /* 212 [Ô] LATIN CAPITAL LETTER O WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 9
     * ...@@...
     * ..@..@..
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     */
0, 8, 3, 0, 9, 131, 132, 71, 72, 72, 72, 72, 136, 7,

    /* 213 [Õ] LATIN CAPITAL LETTER O WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 9
     * ..@@..@.
     * .@..@@..
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     */
0, 8, 2, 0, 9, 147, 12, 143, 144, 144, 144, 144, 16, 15,

    /* 214 [Ö] LATIN CAPITAL LETTER O WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 9
     * ..@..@..
     * ........
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     */
0, 8, 2, 0, 9, 9, 0, 143, 144, 144, 144, 144, 16, 15,

    /* 215 [×] MULTIPLICATION SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 3
     * Data length = 4
     * ......
     * ......
     * ......
     * .@...@
     * ..@.@.
     * ...@..
     * ..@.@.
     * .@...@
     * ......
     * ......
     */
0, 6, 1, 3, 4, 145, 66, 40, 17,

    /* 216 [Ø] LATIN CAPITAL LETTER O WITH STROKE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ........
     * ........
     * ..@@@@@.
     * .@...@@.
     * .@..@.@.
     * .@..@.@.
     * .@.@..@.
     * .@@...@.
     * .@@@@@..
     * ........
     */
0, 8, 2, 2, 7, 159, 152, 148, 148, 146, 145, 15,

    /* 217 [Ù] LATIN CAPITAL LETTER U WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 9
     * ...@....
     * ....@...
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     */
0, 8, 3, 0, 9, 1, 66, 72, 72, 72, 72, 72, 136, 7,

    /* 218 [Ú] LATIN CAPITAL LETTER U WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 9
     * ....@...
     * ...@....
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     */
0, 8, 4, 0, 9, 129, 32, 36, 36, 36, 36, 36, 196, 3,

    /* 219 [Û] LATIN CAPITAL LETTER U WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 9
     * ...@@...
     * ..@..@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     */
0, 8, 3, 0, 9, 131, 68, 72, 72, 72, 72, 72, 136, 7,

    /* 220 [Ü] LATIN CAPITAL LETTER U WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 9
     * ..@..@..
     * ........
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     */
0, 8, 2, 0, 9, 9, 128, 144, 144, 144, 144, 144, 16, 15,

    /* 221 [Ý] LATIN CAPITAL LETTER Y WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 7
     * ....@..
     * ...@...
     * @.....@
     * .@...@.
     * ..@.@..
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * .......
     */
0, 7, 4, 0, 7, 65, 4, 69, 20, 4, 2, 129,

    /* 222 [Þ] LATIN CAPITAL LETTER THORN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * .......
     * .......
     * .@.....
     * .@@@@@.
     * .@....@
     * .@....@
     * .@@@@@.
     * .@.....
     * .@.....
     * .......
     */
0, 7, 1, 2, 6, 129, 79, 40, 244, 9, 4,

    /* 223 [ß] LATIN SMALL LETTER SHARP S
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ..@@..
     * .@..@.
     * .@..@.
     * .@.@@.
     * .@...@
     * .@...@
     * .@.@@.
     * ......
     */
0, 6, 2, 2, 5, 35, 73, 154, 40, 106,

    /* 224 [à] LATIN SMALL LETTER A WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 6
     * ......
     * ..@...
     * ...@..
     * ......
     * ..@@@.
     * .....@
     * ..@@@@
     * .@...@
     * ..@@@@
     * ......
     */
0, 6, 2, 1, 6, 129, 0, 28, 200, 139, 60,

    /* 225 [á] LATIN SMALL LETTER A WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 4
     * Pixel start Y = 1
     * Data length = 6
     * ......
     * ....@.
     * ...@..
     * ......
     * ..@@@.
     * .....@
     * ..@@@@
     * .@...@
     * ..@@@@
     * ......
     */
0, 6, 4, 1, 6, 33, 0, 7, 242, 34, 15,

    /* 226 [â] LATIN SMALL LETTER A WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 6
     * ......
     * ...@..
     * ..@.@.
     * ......
     * ..@@@.
     * .....@
     * ..@@@@
     * .@...@
     * ..@@@@
     * ......
     */
0, 6, 3, 1, 6, 161, 0, 14, 228, 69, 30,

    /* 227 [ã] LATIN SMALL LETTER A WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 6
     * ......
     * ..@@.@
     * .@.@@.
     * ......
     * ..@@@.
     * .....@
     * ..@@@@
     * .@...@
     * ..@@@@
     * ......
     */
0, 6, 2, 1, 6, 171, 1, 28, 200, 139, 60,

    /* 228 [ä] LATIN SMALL LETTER A WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ..@.@.
     * ......
     * ..@@@.
     * .....@
     * ..@@@@
     * .@...@
     * ..@@@@
     * ......
     */
0, 6, 2, 2, 5, 5, 112, 32, 47, 242,

    /* 229 [å] LATIN SMALL LETTER A WITH RING ABOVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 7
     * ...@..
     * ..@.@.
     * ...@..
     * ......
     * ..@@@.
     * .....@
     * ..@@@@
     * .@...@
     * ..@@@@
     * ......
     */
0, 6, 3, 0, 7, 161, 16, 128, 3, 121, 145, 7,

    /* 230 [æ] LATIN SMALL LETTER AE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 6
     * ..........
     * ..........
     * ..........
     * ..........
     * ..@@@.@@@.
     * .....@...@
     * ..@@@@@@@@
     * .@...@....
     * ..@@@.@@@.
     * ..........
     */
0, 10, 2, 4, 6, 119, 32, 242, 47, 2, 119,

    /* 231 [ç] LATIN SMALL LETTER C WITH CEDILLA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ..@@@.
     * .@...@
     * .@....
     * .@...@
     * ..@@@.
     * ..@@..
     */
0, 6, 2, 4, 4, 39, 10, 34, 199,

    /* 232 [è] LATIN SMALL LETTER E WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 6
     * ......
     * ..@...
     * ...@..
     * ......
     * ..@@@.
     * .@...@
     * .@@@@@
     * .@....
     * ..@@@.
     * ......
     */
0, 6, 2, 1, 6, 129, 0, 156, 232, 11, 28,

    /* 233 [é] LATIN SMALL LETTER E WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 4
     * Pixel start Y = 1
     * Data length = 6
     * ......
     * ....@.
     * ...@..
     * ......
     * ..@@@.
     * .@...@
     * .@@@@@
     * .@....
     * ..@@@.
     * ......
     */
0, 6, 4, 1, 6, 33, 0, 39, 250, 2, 7,

    /* 234 [ê] LATIN SMALL LETTER E WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 6
     * ......
     * ...@..
     * ..@.@.
     * ......
     * ..@@@.
     * .@...@
     * .@@@@@
     * .@....
     * ..@@@.
     * ......
     */
0, 6, 3, 1, 6, 161, 0, 78, 244, 5, 14,

    /* 235 [ë] LATIN SMALL LETTER E WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ..@.@.
     * ......
     * ..@@@.
     * .@...@
     * .@@@@@
     * .@....
     * ..@@@.
     * ......
     */
0, 6, 2, 2, 5, 5, 112, 162, 47, 112,

    /* 236 [ì] LATIN SMALL LETTER I WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 0
     * Pixel start Y = 1
     * Data length = 2
     * ..
     * @.
     * .@
     * ..
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     */
0, 2, 0, 1, 2, 137, 170,

    /* 237 [í] LATIN SMALL LETTER I WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 4
     * ....
     * ...@
     * ..@.
     * ....
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ....
     */
0, 4, 3, 1, 4, 9, 136, 136, 8,

    /* 238 [î] LATIN SMALL LETTER I WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 4
     * ....
     * ..@.
     * .@.@
     * ....
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ....
     */
0, 4, 2, 1, 4, 41, 16, 17, 17,

    /* 239 [ï] LATIN SMALL LETTER I WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * ....
     * ....
     * .@.@
     * ....
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ....
     */
0, 4, 1, 2, 4, 5, 34, 34, 2,

    /* 240 [ð] LATIN SMALL LETTER ETH
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ..@.@.
     * ...@..
     * ..@.@.
     * ..@@@@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     */
0, 6, 2, 2, 5, 133, 80, 188, 40, 114,

    /* 241 [ñ] LATIN SMALL LETTER N WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 6
     * ......
     * ..@@.@
     * .@.@@.
     * ......
     * .@@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ......
     */
0, 6, 2, 1, 6, 171, 1, 158, 40, 138, 34,

    /* 242 [ò] LATIN SMALL LETTER O WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 6
     * ......
     * ..@...
     * ...@..
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     */
0, 6, 2, 1, 6, 129, 0, 156, 40, 138, 28,

    /* 243 [ó] LATIN SMALL LETTER O WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 4
     * Pixel start Y = 1
     * Data length = 6
     * ......
     * ....@.
     * ...@..
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     */
0, 6, 4, 1, 6, 33, 0, 39, 138, 34, 7,

    /* 244 [ô] LATIN SMALL LETTER O WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 6
     * ......
     * ...@..
     * ..@.@.
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     */
0, 6, 3, 1, 6, 161, 0, 78, 20, 69, 14,

    /* 245 [õ] LATIN SMALL LETTER O WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 6
     * ......
     * ..@@.@
     * .@.@@.
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     */
0, 6, 2, 1, 6, 171, 1, 156, 40, 138, 28,

    /* 246 [ö] LATIN SMALL LETTER O WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ..@.@.
     * ......
     * ..@@@.
     * .@...@
     * .@...@
     * .@...@
     * ..@@@.
     * ......
     */
0, 6, 2, 2, 5, 5, 112, 162, 40, 114,

    /* 247 [÷] DIVISION SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 3
     * Data length = 4
     * ......
     * ......
     * ......
     * ...@..
     * ......
     * .@@@@@
     * ......
     * ...@..
     * ......
     * ......
     */
0, 6, 3, 3, 4, 1, 124, 0, 1,

    /* 248 [ø] LATIN SMALL LETTER O WITH STROKE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ..@@@@
     * .@..@@
     * .@.@.@
     * .@@..@
     * .@@@@.
     * ......
     */
0, 6, 2, 4, 4, 47, 171, 166, 7,

    /* 249 [ù] LATIN SMALL LETTER U WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 6
     * ......
     * ..@...
     * ...@..
     * ......
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@@
     * ......
     */
0, 6, 2, 1, 6, 129, 0, 162, 40, 138, 60,

    /* 250 [ú] LATIN SMALL LETTER U WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 4
     * Pixel start Y = 1
     * Data length = 6
     * ......
     * ....@.
     * ...@..
     * ......
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@@
     * ......
     */
0, 6, 4, 1, 6, 33, 128, 40, 138, 34, 15,

    /* 251 [û] LATIN SMALL LETTER U WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 6
     * ......
     * ...@..
     * ..@.@.
     * ......
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@@
     * ......
     */
0, 6, 3, 1, 6, 161, 0, 81, 20, 69, 30,

    /* 252 [ü] LATIN SMALL LETTER U WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ......
     * ......
     * ..@.@.
     * ......
     * .@...@
     * .@...@
     * .@...@
     * .@...@
     * ..@@@@
     * ......
     */
0, 6, 2, 2, 5, 5, 136, 162, 40, 242,

    /* 253 [ý] LATIN SMALL LETTER Y WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 5
     * .....
     * ...@.
     * ..@..
     * .....
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * ..@..
     * @@...
     */
0, 5, 3, 1, 5, 17, 32, 165, 100, 100,

    /* 254 [þ] LATIN SMALL LETTER THORN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * ......
     * ......
     * .@....
     * .@....
     * .@@@@.
     * .@...@
     * .@...@
     * .@...@
     * .@@@@.
     * .@....
     */
0, 6, 1, 2, 6, 65, 240, 68, 81, 244, 4,

};
