// File generated by font_compiler.py
// FONT_HELV10[] binary size: 2299

#include <stdint.h>

const uint8_t FONT_HELV10[] = {
    /* Metadata block:
     * First glyph byte = 32
     * End glyph byte = 255
     * Glyph height = 12
     * Default/fallback glyph = 80
     */
    32, 255, 12, 80,

    /* 32 [ ] SPACE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 0
     * Data length = 0
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 0, 0, 0,

    /* 33 [!] EXCLAMATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * .@.
     * ...
     * ...
     */
0, 3, 1, 2, 3, 73, 146, 32,

    /* 34 ["] QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 2
     * .....
     * .....
     * .@.@.
     * .@.@.
     * .@.@.
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     */
0, 5, 1, 2, 2, 165, 20,

    /* 35 [#] NUMBER SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * ...@.@.
     * ...@.@.
     * .@@@@@@
     * ..@.@..
     * ..@.@..
     * @@@@@@.
     * .@.@...
     * .@.@...
     * .......
     * .......
     */
0, 7, 3, 2, 7, 133, 242, 83, 40, 63, 133, 2,

    /* 36 [$] DOLLAR SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * ...@...
     * ..@@@..
     * .@.@.@.
     * .@.@...
     * ..@@@..
     * ...@.@.
     * .@.@.@.
     * ..@@@..
     * ...@...
     * .......
     */
0, 7, 3, 2, 8, 193, 81, 41, 56, 40, 21, 7, 1,

    /* 37 [%] PERCENT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 12
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 12
     * ............
     * ............
     * ..@@.....@..
     * .@..@...@...
     * .@..@..@....
     * ..@@..@.....
     * .....@..@@..
     * ....@..@..@.
     * ...@...@..@.
     * ..@.....@@..
     * ............
     * ............
     */
0, 12, 2, 2, 12, 131, 72, 132, 36, 48, 1, 200, 64, 18, 34, 17, 12,

    /* 38 [&] AMPERSAND
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 9
     * .........
     * .........
     * ...@@....
     * ..@..@...
     * ..@..@...
     * ...@@....
     * ..@.@....
     * .@...@.@.
     * .@....@..
     * ..@@@@.@.
     * .........
     * .........
     */
0, 9, 3, 2, 9, 3, 9, 18, 24, 40, 136, 18, 194, 11,

    /* 39 ['] APOSTROPHE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 1
     * ...
     * ...
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 2, 1, 73,

    /* 40 [(] LEFT PARENTHESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 5
     * ....
     * ....
     * ..@.
     * .@..
     * .@..
     * .@..
     * .@..
     * .@..
     * .@..
     * .@..
     * .@..
     * ..@.
     */
0, 4, 2, 2, 5, 137, 136, 136, 136, 16,

    /* 41 [)] RIGHT PARENTHESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 5
     * ....
     * ....
     * .@..
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * .@..
     */
0, 4, 1, 2, 5, 33, 34, 34, 34, 18,

    /* 42 [*] ASTERISK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 3
     * .....
     * .....
     * ..@..
     * @.@.@
     * .@@@.
     * .@.@.
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     */
0, 5, 2, 2, 3, 169, 78, 1,

    /* 43 [+] PLUS SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 4
     * Data length = 4
     * .......
     * .......
     * .......
     * .......
     * ...@...
     * ...@...
     * .@@@@@.
     * ...@...
     * ...@...
     * .......
     * .......
     * .......
     */
0, 7, 3, 4, 4, 129, 240, 33, 16,

    /* 44 [,] COMMA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 9
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * .@.
     * .@.
     * @..
     */
0, 3, 1, 9, 1, 41,

    /* 45 [-] HYPHEN-MINUS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 0
     * Pixel start Y = 6
     * Data length = 1
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * @@@@
     * ....
     * ....
     * ....
     * ....
     * ....
     */
0, 4, 0, 6, 1, 15,

    /* 46 [.] FULL STOP
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 9
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * .@.
     * ...
     * ...
     */
0, 3, 1, 9, 1, 1,

    /* 47 [/] SOLIDUS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 4
     * ....
     * ....
     * ...@
     * ...@
     * ..@.
     * ..@.
     * .@..
     * .@..
     * @...
     * @...
     * ....
     * ....
     */
0, 4, 3, 2, 4, 145, 72, 36, 2,

    /* 48 [0] DIGIT ZERO
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * ..@@@..
     * .@...@.
     * .@...@.
     * .@...@.
     * .@...@.
     * .@...@.
     * .@...@.
     * ..@@@..
     * .......
     * .......
     */
0, 7, 2, 2, 7, 71, 36, 18, 137, 68, 34, 14,

    /* 49 [1] DIGIT ONE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * ...@...
     * .@@@...
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * ...@...
     * .......
     * .......
     */
0, 7, 3, 2, 7, 225, 64, 32, 16, 8, 4, 2,

    /* 50 [2] DIGIT TWO
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * ..@@@..
     * .@...@.
     * .@...@.
     * ....@..
     * ...@...
     * ..@....
     * .@.....
     * .@@@@@.
     * .......
     * .......
     */
0, 7, 2, 2, 7, 71, 36, 130, 32, 8, 2, 31,

    /* 51 [3] DIGIT THREE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * ..@@@..
     * .@...@.
     * .....@.
     * ...@@..
     * .....@.
     * .....@.
     * .@...@.
     * ..@@@..
     * .......
     * .......
     */
0, 7, 2, 2, 7, 71, 4, 194, 128, 64, 34, 14,

    /* 52 [4] DIGIT FOUR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 5
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * .....@.
     * ....@@.
     * ...@.@.
     * ..@..@.
     * .@...@.
     * .@@@@@.
     * .....@.
     * .....@.
     * .......
     * .......
     */
0, 7, 5, 2, 7, 193, 80, 36, 145, 15, 4, 2,

    /* 53 [5] DIGIT FIVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * .@@@@@.
     * .@.....
     * .@.....
     * .@@@@..
     * .@...@.
     * .....@.
     * .@...@.
     * ..@@@..
     * .......
     * .......
     */
0, 7, 1, 2, 7, 159, 64, 224, 17, 129, 68, 28,

    /* 54 [6] DIGIT SIX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * ..@@@..
     * .@...@.
     * .@.....
     * .@.@@..
     * .@@..@.
     * .@...@.
     * .@...@.
     * ..@@@..
     * .......
     * .......
     */
0, 7, 2, 2, 7, 71, 36, 208, 152, 68, 34, 14,

    /* 55 [7] DIGIT SEVEN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * .@@@@@.
     * .....@.
     * ....@..
     * ....@..
     * ...@...
     * ...@...
     * ..@....
     * ..@....
     * .......
     * .......
     */
0, 7, 1, 2, 7, 31, 8, 2, 65, 32, 8, 4,

    /* 56 [8] DIGIT EIGHT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * ..@@@..
     * .@...@.
     * .@...@.
     * ..@@@..
     * .@...@.
     * .@...@.
     * .@...@.
     * ..@@@..
     * .......
     * .......
     */
0, 7, 2, 2, 7, 71, 36, 226, 136, 68, 34, 14,

    /* 57 [9] DIGIT NINE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * ..@@@..
     * .@...@.
     * .@...@.
     * .@..@@.
     * ..@@.@.
     * .....@.
     * .@...@.
     * ..@@@..
     * .......
     * .......
     */
0, 7, 2, 2, 7, 71, 36, 146, 177, 64, 34, 14,

    /* 58 [:] COLON
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 2
     * ...
     * ...
     * ...
     * ...
     * .@.
     * ...
     * ...
     * ...
     * ...
     * .@.
     * ...
     * ...
     */
0, 3, 1, 4, 2, 1, 128,

    /* 59 [;] SEMICOLON
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 3
     * ...
     * ...
     * ...
     * ...
     * .@.
     * ...
     * ...
     * ...
     * ...
     * .@.
     * .@.
     * @..
     */
0, 3, 1, 4, 3, 1, 128, 20,

    /* 60 [<] LESS-THAN SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 4
     * Pixel start Y = 3
     * Data length = 6
     * .......
     * .......
     * .......
     * ....@..
     * ...@...
     * ..@....
     * .@.....
     * ..@....
     * ...@...
     * ....@..
     * .......
     * .......
     */
0, 7, 4, 3, 6, 65, 16, 4, 4, 4, 4,

    /* 61 [=] EQUALS SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 3
     * .......
     * .......
     * .......
     * .......
     * .......
     * .@@@@@.
     * .......
     * .@@@@@.
     * .......
     * .......
     * .......
     * .......
     */
0, 7, 1, 5, 3, 31, 192, 7,

    /* 62 [>] GREATER-THAN SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 3
     * Data length = 6
     * .......
     * .......
     * .......
     * ..@....
     * ...@...
     * ....@..
     * .....@.
     * ....@..
     * ...@...
     * ..@....
     * .......
     * .......
     */
0, 7, 2, 3, 6, 1, 1, 1, 65, 16, 4,

    /* 63 [?] QUESTION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * ..@@@..
     * .@...@.
     * .@...@.
     * ....@..
     * ...@...
     * ...@...
     * .......
     * ...@...
     * .......
     * .......
     */
0, 7, 2, 2, 7, 71, 36, 130, 32, 16, 0, 4,

    /* 64 [@] COMMERCIAL AT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 14
     * Pixel start X = 5
     * Pixel start Y = 1
     * Data length = 19
     * ..............
     * .....@@@@.....
     * ...@@....@@...
     * ..@........@..
     * ..@...@@@..@..
     * .@...@..@...@.
     * .@...@..@...@.
     * .@...@..@...@.
     * ..@...@@.@@@..
     * ..@...........
     * ...@@.....@@..
     * .....@@@@@....
     */
   0, 14, 5, 1, 19, 15, 48, 12, 2, 132, 56, 17, 137, 68, 34, 145, 136, 216, 33,
    0, 48, 24, 240, 1,

    /* 65 [A] LATIN CAPITAL LETTER A
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 4
     * Pixel start Y = 2
     * Data length = 9
     * .........
     * .........
     * ....@....
     * ....@....
     * ...@.@...
     * ...@.@...
     * ..@...@..
     * ..@@@@@..
     * .@.....@.
     * .@.....@.
     * .........
     * .........
     */
0, 9, 4, 2, 9, 1, 2, 10, 20, 68, 248, 8, 18, 4,

    /* 66 [B] LATIN CAPITAL LETTER B
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * .........
     * .........
     * .@@@@@@..
     * .@.....@.
     * .@.....@.
     * .@@@@@@..
     * .@.....@.
     * .@.....@.
     * .@.....@.
     * .@@@@@@..
     * .........
     * .........
     */
0, 9, 1, 2, 9, 63, 130, 4, 249, 17, 36, 72, 144, 31,

    /* 67 [C] LATIN CAPITAL LETTER C
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 9
     * .........
     * .........
     * ...@@@@..
     * ..@....@.
     * .@......@
     * .@.......
     * .@.......
     * .@......@
     * ..@....@.
     * ...@@@@..
     * .........
     * .........
     */
0, 9, 3, 2, 9, 15, 33, 129, 2, 4, 8, 36, 132, 7,

    /* 68 [D] LATIN CAPITAL LETTER D
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 10
     * ..........
     * ..........
     * .@@@@@@...
     * .@.....@..
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@.....@..
     * .@@@@@@...
     * ..........
     * ..........
     */
0, 10, 1, 2, 10, 63, 4, 17, 72, 32, 129, 4, 18, 196, 15,

    /* 69 [E] LATIN CAPITAL LETTER E
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * .........
     * .........
     * .@@@@@@@.
     * .@.......
     * .@.......
     * .@@@@@@..
     * .@.......
     * .@.......
     * .@.......
     * .@@@@@@@.
     * .........
     * .........
     */
0, 9, 1, 2, 9, 127, 2, 4, 248, 17, 32, 64, 128, 63,

    /* 70 [F] LATIN CAPITAL LETTER F
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * .@@@@@@@
     * .@......
     * .@......
     * .@@@@@@.
     * .@......
     * .@......
     * .@......
     * .@......
     * ........
     * ........
     */
0, 8, 1, 2, 8, 127, 1, 1, 63, 1, 1, 1, 1,

    /* 71 [G] LATIN CAPITAL LETTER G
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 10
     * ..........
     * ..........
     * ...@@@@...
     * ..@....@..
     * .@......@.
     * .@........
     * .@....@@@.
     * .@......@.
     * ..@....@@.
     * ...@@@@.@.
     * ..........
     * ..........
     */
0, 10, 3, 2, 10, 15, 66, 4, 18, 64, 56, 129, 8, 195, 11,

    /* 72 [H] LATIN CAPITAL LETTER H
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 10
     * ..........
     * ..........
     * .@......@.
     * .@......@.
     * .@......@.
     * .@@@@@@@@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * ..........
     * ..........
     */
0, 10, 1, 2, 10, 129, 4, 18, 200, 63, 129, 4, 18, 72, 32,

    /* 73 [I] LATIN CAPITAL LETTER I
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 1, 2, 3, 73, 146, 36,

    /* 74 [J] LATIN CAPITAL LETTER J
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 5
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * .....@.
     * .....@.
     * .....@.
     * .....@.
     * .....@.
     * .@...@.
     * .@...@.
     * ..@@@..
     * .......
     * .......
     */
0, 7, 5, 2, 7, 129, 64, 32, 144, 72, 196, 1,

    /* 75 [K] LATIN CAPITAL LETTER K
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * .@....@.
     * .@...@..
     * .@..@...
     * .@.@....
     * .@@.@...
     * .@...@..
     * .@....@.
     * .@.....@
     * ........
     * ........
     */
0, 8, 1, 2, 8, 33, 17, 9, 5, 11, 17, 33, 65,

    /* 76 [L] LATIN CAPITAL LETTER L
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * .@.....
     * .@.....
     * .@.....
     * .@.....
     * .@.....
     * .@.....
     * .@.....
     * .@@@@@@
     * .......
     * .......
     */
0, 7, 1, 2, 7, 129, 64, 32, 16, 8, 4, 126,

    /* 77 [M] LATIN CAPITAL LETTER M
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 11
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 11
     * ...........
     * ...........
     * .@.......@.
     * .@@.....@@.
     * .@.@...@.@.
     * .@..@.@..@.
     * .@...@...@.
     * .@.......@.
     * .@.......@.
     * .@.......@.
     * ...........
     * ...........
     */
0, 11, 1, 2, 11, 1, 25, 76, 81, 82, 18, 145, 128, 4, 36, 32,

    /* 78 [N] LATIN CAPITAL LETTER N
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 10
     * ..........
     * ..........
     * .@......@.
     * .@@.....@.
     * .@.@....@.
     * .@..@...@.
     * .@...@..@.
     * .@....@.@.
     * .@.....@@.
     * .@......@.
     * ..........
     * ..........
     */
0, 10, 1, 2, 10, 129, 12, 82, 72, 34, 145, 132, 18, 76, 32,

    /* 79 [O] LATIN CAPITAL LETTER O
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 10
     * ..........
     * ..........
     * ...@@@@...
     * ..@....@..
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * ..@....@..
     * ...@@@@...
     * ..........
     * ..........
     */
0, 10, 3, 2, 10, 15, 66, 4, 18, 72, 32, 129, 8, 193, 3,

    /* 80 [P] LATIN CAPITAL LETTER P
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * .........
     * .........
     * .@@@@@@@.
     * .@......@
     * .@......@
     * .@......@
     * .@@@@@@@.
     * .@.......
     * .@.......
     * .@.......
     * .........
     * .........
     */
0, 9, 1, 2, 8, 127, 2, 5, 10, 244, 39, 64, 128,

    /* 81 [Q] LATIN CAPITAL LETTER Q
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 10
     * ..........
     * ..........
     * ...@@@@...
     * ..@....@..
     * .@......@.
     * .@......@.
     * .@......@.
     * .@....@.@.
     * ..@....@..
     * ...@@@@.@.
     * ..........
     * ..........
     */
0, 10, 3, 2, 10, 15, 66, 4, 18, 72, 32, 161, 8, 193, 11,

    /* 82 [R] LATIN CAPITAL LETTER R
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 10
     * ..........
     * ..........
     * .@@@@@@@..
     * .@......@.
     * .@......@.
     * .@......@.
     * .@@@@@@@..
     * .@......@.
     * .@......@.
     * .@.......@
     * ..........
     * ..........
     */
0, 10, 1, 2, 10, 127, 4, 18, 72, 32, 127, 4, 18, 72, 64,

    /* 83 [S] LATIN CAPITAL LETTER S
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 9
     * .........
     * .........
     * ..@@@@@..
     * .@.....@.
     * .@.....@.
     * ..@@@....
     * .....@@..
     * .@.....@.
     * .@.....@.
     * ..@@@@@..
     * .........
     * .........
     */
0, 9, 2, 2, 9, 31, 65, 130, 56, 128, 17, 36, 136, 15,

    /* 84 [T] LATIN CAPITAL LETTER T
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 9
     * .........
     * .........
     * @@@@@@@@@
     * ....@....
     * ....@....
     * ....@....
     * ....@....
     * ....@....
     * ....@....
     * ....@....
     * .........
     * .........
     */
0, 9, 0, 2, 9, 255, 33, 64, 128, 0, 1, 2, 4, 8,

    /* 85 [U] LATIN CAPITAL LETTER U
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 10
     * ..........
     * ..........
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * ..@@@@@@..
     * ..........
     * ..........
     */
0, 10, 1, 2, 10, 129, 4, 18, 72, 32, 129, 4, 18, 136, 31,

    /* 86 [V] LATIN CAPITAL LETTER V
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * .........
     * .........
     * .@.....@.
     * .@.....@.
     * ..@...@..
     * ..@...@..
     * ...@.@...
     * ...@.@...
     * ....@....
     * ....@....
     * .........
     * .........
     */
0, 9, 1, 2, 9, 65, 130, 136, 16, 65, 129, 2, 2, 4,

    /* 87 [W] LATIN CAPITAL LETTER W
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 13
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 13
     * .............
     * .............
     * @.....@.....@
     * @.....@.....@
     * .@...@.@...@.
     * .@...@.@...@.
     * ..@.@...@.@..
     * ..@.@...@.@..
     * ...@.....@...
     * ...@.....@...
     * .............
     * .............
     */
0, 13, 0, 2, 13, 65, 48, 8, 138, 34, 81, 68, 81, 40, 10, 130, 64, 16,

    /* 88 [X] LATIN CAPITAL LETTER X
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * @......@
     * .@....@.
     * ..@..@..
     * ...@@...
     * ...@@...
     * ..@..@..
     * .@....@.
     * @......@
     * ........
     * ........
     */
0, 8, 0, 2, 8, 129, 66, 36, 24, 24, 36, 66, 129,

    /* 89 [Y] LATIN CAPITAL LETTER Y
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 9
     * .........
     * .........
     * @.......@
     * .@.....@.
     * ..@...@..
     * ...@.@...
     * ....@....
     * ....@....
     * ....@....
     * ....@....
     * .........
     * .........
     */
0, 9, 0, 2, 9, 1, 5, 17, 65, 1, 1, 2, 4, 8,

    /* 90 [Z] LATIN CAPITAL LETTER Z
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * .@@@@@@.
     * ......@.
     * .....@..
     * ....@...
     * ...@....
     * ..@.....
     * .@......
     * .@@@@@@.
     * ........
     * ........
     */
0, 8, 1, 2, 8, 63, 32, 16, 8, 4, 2, 1, 63,

    /* 91 [[] LEFT SQUARE BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 5
     * ....
     * ....
     * .@@@
     * .@..
     * .@..
     * .@..
     * .@..
     * .@..
     * .@..
     * .@..
     * .@..
     * .@@@
     */
0, 4, 1, 2, 5, 23, 17, 17, 17, 113,

    /* 92 [\] REVERSE SOLIDUS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 4
     * ....
     * ....
     * @...
     * @...
     * .@..
     * .@..
     * ..@.
     * ..@.
     * ...@
     * ...@
     * ....
     * ....
     */
0, 4, 0, 2, 4, 17, 34, 68, 136,

    /* 93 []] RIGHT SQUARE BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 5
     * ....
     * ....
     * @@@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * @@@.
     */
0, 4, 0, 2, 5, 71, 68, 68, 68, 116,

    /* 94 [^] CIRCUMFLEX ACCENT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 3
     * .......
     * .......
     * ...@...
     * ..@.@..
     * .@...@.
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     */
0, 7, 3, 2, 3, 65, 17, 1,

    /* 95 [_] LOW LINE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 0
     * Pixel start Y = 11
     * Data length = 1
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     * @@@@@@@
     */
0, 7, 0, 11, 1, 127,

    /* 96 [`] GRAVE ACCENT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 1
     * Data length = 1
     * ....
     * .@..
     * ..@.
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     */
0, 4, 1, 1, 1, 33,

    /* 97 [a] LATIN SMALL LETTER A
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 6
     * ........
     * ........
     * ........
     * ........
     * ..@@@@..
     * .@....@.
     * ..@@@@@.
     * .@....@.
     * .@....@.
     * ..@@@@.@
     * ........
     * ........
     */
0, 8, 2, 4, 6, 143, 16, 159, 144, 16, 47,

    /* 98 [b] LATIN SMALL LETTER B
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * .@......
     * .@......
     * .@.@@@..
     * .@@...@.
     * .@....@.
     * .@....@.
     * .@@...@.
     * .@.@@@..
     * ........
     * ........
     */
0, 8, 1, 2, 8, 1, 1, 29, 35, 33, 33, 35, 29,

    /* 99 [c] LATIN SMALL LETTER C
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 5
     * .......
     * .......
     * .......
     * .......
     * ..@@@@.
     * .@....@
     * .@.....
     * .@.....
     * .@....@
     * ..@@@@.
     * .......
     * .......
     */
0, 7, 2, 4, 5, 79, 40, 16, 8, 121,

    /* 100 [d] LATIN SMALL LETTER D
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 6
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * ......@.
     * ......@.
     * ..@@@.@.
     * .@...@@.
     * .@....@.
     * .@....@.
     * .@...@@.
     * ..@@@.@.
     * ........
     * ........
     */
0, 8, 6, 2, 8, 1, 113, 137, 9, 9, 137, 113, 1,

    /* 101 [e] LATIN SMALL LETTER E
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 6
     * ........
     * ........
     * ........
     * ........
     * ..@@@@..
     * .@....@.
     * .@@@@@@.
     * .@......
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 2, 4, 6, 143, 144, 159, 128, 16, 15,

    /* 102 [f] LATIN SMALL LETTER F
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * ..@
     * .@.
     * @@@
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 2, 2, 3, 117, 73, 18,

    /* 103 [g] LATIN SMALL LETTER G
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 8
     * ........
     * ........
     * ........
     * ........
     * ..@@@.@.
     * .@...@@.
     * .@....@.
     * .@....@.
     * .@...@@.
     * ..@@@.@.
     * ......@.
     * ..@@@@..
     */
0, 8, 2, 4, 8, 151, 152, 144, 144, 24, 23, 16, 15,

    /* 104 [h] LATIN SMALL LETTER H
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * .@.....
     * .@.....
     * .@.@@..
     * .@@..@.
     * .@...@.
     * .@...@.
     * .@...@.
     * .@...@.
     * .......
     * .......
     */
0, 7, 1, 2, 7, 129, 64, 99, 18, 137, 68, 34,

    /* 105 [i] LATIN SMALL LETTER I
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * .@.
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 1, 2, 3, 65, 146, 36,

    /* 106 [j] LATIN SMALL LETTER J
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * .@.
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * @..
     */
0, 3, 1, 2, 4, 65, 146, 36, 5,

    /* 107 [k] LATIN SMALL LETTER K
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * .@.....
     * .@.....
     * .@...@.
     * .@..@..
     * .@.@...
     * .@@.@..
     * .@...@.
     * .@....@
     * .......
     * .......
     */
0, 7, 1, 2, 7, 129, 64, 36, 81, 88, 68, 66,

    /* 108 [l] LATIN SMALL LETTER L
     * Duplicate of = 73 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
73,

    /* 109 [m] LATIN SMALL LETTER M
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 11
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 8
     * ...........
     * ...........
     * ...........
     * ...........
     * .@.@@..@@..
     * .@@..@@..@.
     * .@...@...@.
     * .@...@...@.
     * .@...@...@.
     * .@...@...@.
     * ...........
     * ...........
     */
0, 11, 1, 4, 8, 205, 152, 73, 68, 34, 18, 145, 136,

    /* 110 [n] LATIN SMALL LETTER N
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 5
     * .......
     * .......
     * .......
     * .......
     * .@.@@..
     * .@@..@.
     * .@...@.
     * .@...@.
     * .@...@.
     * .@...@.
     * .......
     * .......
     */
0, 7, 1, 4, 5, 141, 73, 36, 18, 137,

    /* 111 [o] LATIN SMALL LETTER O
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 6
     * ........
     * ........
     * ........
     * ........
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 2, 4, 6, 143, 144, 144, 144, 16, 15,

    /* 112 [p] LATIN SMALL LETTER P
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 8
     * ........
     * ........
     * ........
     * ........
     * .@.@@@..
     * .@@...@.
     * .@....@.
     * .@....@.
     * .@@...@.
     * .@.@@@..
     * .@......
     * .@......
     */
0, 8, 1, 4, 8, 29, 35, 33, 33, 35, 29, 1, 1,

    /* 113 [q] LATIN SMALL LETTER Q
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 8
     * ........
     * ........
     * ........
     * ........
     * ..@@@.@.
     * .@...@@.
     * .@....@.
     * .@....@.
     * .@...@@.
     * ..@@@.@.
     * ......@.
     * ......@.
     */
0, 8, 2, 4, 8, 151, 152, 144, 144, 24, 23, 16, 16,

    /* 114 [r] LATIN SMALL LETTER R
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 3
     * ....
     * ....
     * ....
     * ....
     * .@.@
     * .@@.
     * .@..
     * .@..
     * .@..
     * .@..
     * ....
     * ....
     */
0, 4, 1, 4, 3, 53, 17, 17,

    /* 115 [s] LATIN SMALL LETTER S
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 5
     * .......
     * .......
     * .......
     * .......
     * ..@@@..
     * .@...@.
     * ..@@...
     * ....@..
     * .@...@.
     * ..@@@..
     * .......
     * .......
     */
0, 7, 2, 4, 5, 71, 196, 128, 136, 56,

    /* 116 [t] LATIN SMALL LETTER T
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * .@.
     * .@.
     * @@@
     * .@.
     * .@.
     * .@.
     * .@.
     * ..@
     * ...
     * ...
     */
0, 3, 1, 2, 3, 233, 146, 68,

    /* 117 [u] LATIN SMALL LETTER U
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 5
     * .......
     * .......
     * .......
     * .......
     * .@...@.
     * .@...@.
     * .@...@.
     * .@...@.
     * .@..@@.
     * ..@@.@.
     * .......
     * .......
     */
0, 7, 1, 4, 5, 145, 72, 36, 146, 177,

    /* 118 [v] LATIN SMALL LETTER V
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 5
     * .......
     * .......
     * .......
     * .......
     * .@...@.
     * .@...@.
     * ..@.@..
     * ..@.@..
     * ...@...
     * ...@...
     * .......
     * .......
     */
0, 7, 1, 4, 5, 145, 136, 66, 65, 32,

    /* 119 [w] LATIN SMALL LETTER W
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 0
     * Pixel start Y = 4
     * Data length = 7
     * .........
     * .........
     * .........
     * .........
     * @...@...@
     * @...@...@
     * .@.@.@.@.
     * .@.@.@.@.
     * ..@...@..
     * ..@...@..
     * .........
     * .........
     */
0, 9, 0, 4, 7, 17, 35, 170, 82, 69, 132, 8,

    /* 120 [x] LATIN SMALL LETTER X
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 0
     * Pixel start Y = 4
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * @....@
     * .@..@.
     * ..@@..
     * ..@@..
     * .@..@.
     * @....@
     * ......
     * ......
     */
0, 6, 0, 4, 5, 161, 196, 48, 82, 8,

    /* 121 [y] LATIN SMALL LETTER Y
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 7
     * .......
     * .......
     * .......
     * .......
     * .@...@.
     * .@...@.
     * ..@.@..
     * ..@.@..
     * ...@...
     * ...@...
     * ..@....
     * @@.....
     */
0, 7, 1, 4, 7, 145, 136, 66, 65, 32, 8, 3,

    /* 122 [z] LATIN SMALL LETTER Z
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * .@@@@.
     * ....@.
     * ...@..
     * ..@...
     * .@....
     * .@@@@.
     * ......
     * ......
     */
0, 6, 1, 4, 5, 15, 66, 8, 193, 3,

    /* 123 [{] LEFT CURLY BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ...@@
     * ..@..
     * ..@..
     * ..@..
     * .@...
     * ..@..
     * ..@..
     * ..@..
     * ..@..
     * ...@@
     */
0, 5, 3, 2, 6, 19, 66, 4, 33, 132, 96,

    /* 124 [|] VERTICAL LINE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     */
0, 3, 1, 2, 4, 73, 146, 36, 9,

    /* 125 [}] RIGHT CURLY BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * @@...
     * ..@..
     * ..@..
     * ..@..
     * ...@.
     * ..@..
     * ..@..
     * ..@..
     * ..@..
     * @@...
     */
0, 5, 0, 2, 6, 131, 16, 130, 8, 33, 100,

    /* 126 [~] TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 2
     * .........
     * .........
     * ..@@..@..
     * .@..@@...
     * .........
     * .........
     * .........
     * .........
     * .........
     * .........
     * .........
     * .........
     */
0, 9, 2, 2, 2, 19, 25,

    /* 127 
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
0, 4, 1, 2, 4, 51, 51, 51, 51,

    /* 128 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 129 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 130 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 131 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 132 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 133 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 134 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 135 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 136 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 137 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 138 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 139 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 140 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 141 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 142 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 143 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 144 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 145 [‘] LEFT SINGLE QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 1
     * ...
     * ...
     * ..@
     * .@.
     * .@.
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 2, 2, 1, 37,

    /* 146 [’] RIGHT SINGLE QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 1
     * ...
     * ...
     * .@.
     * .@.
     * @..
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 2, 1, 41,

    /* 147 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 148 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 149 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 150 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 151 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 152 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 153 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 154 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 155 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 156 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 157 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 158 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 159 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     * ....
     */
127,

    /* 160 [ ] NO-BREAK SPACE
     * Duplicate of = 32 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
32,

    /* 161 [¡] INVERTED EXCLAMATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 3
     * ...
     * ...
     * ...
     * ...
     * .@.
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     */
0, 3, 1, 4, 3, 65, 146, 36,

    /* 162 [¢] CENT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 5
     * Pixel start Y = 3
     * Data length = 6
     * .......
     * .......
     * .......
     * .....@.
     * ..@@@..
     * .@..@@.
     * .@.@...
     * .@.@...
     * .@@..@.
     * ..@@@..
     * .@.....
     * .......
     */
0, 7, 5, 3, 6, 113, 100, 10, 133, 137, 35,

    /* 163 [£] POUND SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * ..@@...
     * .@..@..
     * .@.....
     * ..@....
     * .@@@@..
     * ..@....
     * .@.....
     * .@@@@@.
     * .......
     * .......
     */
0, 7, 2, 2, 7, 67, 34, 32, 120, 8, 2, 31,

    /* 164 [¤] CURRENCY SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 5
     * .......
     * .......
     * .@...@.
     * ..@@@..
     * ..@.@..
     * ..@@@..
     * .@...@.
     * .......
     * .......
     * .......
     * .......
     * .......
     */
0, 7, 1, 2, 5, 17, 135, 194, 17, 1,

    /* 165 [¥] YEN SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * @.....@
     * @.....@
     * .@...@.
     * @@@@@@@
     * ...@...
     * @@@@@@@
     * ...@...
     * ...@...
     * .......
     * .......
     */
0, 7, 0, 2, 7, 193, 160, 232, 143, 248, 35, 16,

    /* 166 [¦] BROKEN BAR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     */
0, 3, 1, 2, 4, 73, 2, 36, 9,

    /* 167 [§] SECTION SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * ..@@@..
     * .@...@.
     * ..@@...
     * .@..@..
     * ..@..@.
     * ...@@..
     * .@...@.
     * ..@@@..
     * .......
     * .......
     */
0, 7, 2, 2, 7, 71, 196, 144, 144, 48, 34, 14,

    /* 168 [¨] DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 1
     * ....
     * ....
     * @..@
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     */
0, 4, 0, 2, 1, 9,

    /* 169 [©] COPYRIGHT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * ..@@@@..
     * .@....@.
     * @..@@@.@
     * @.@....@
     * @.@....@
     * @..@@@.@
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 2, 2, 8, 143, 80, 110, 97, 97, 174, 16, 15,

    /* 170 [ª] FEMININE ORDINAL INDICATOR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * .....
     * .....
     * .@@@.
     * ..@@.
     * .@.@.
     * .@@@.
     * .....
     * .@@@.
     * .....
     * .....
     * .....
     * .....
     */
0, 5, 1, 2, 4, 199, 148, 3, 14,

    /* 171 [«] LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 5
     * Data length = 4
     * .......
     * .......
     * .......
     * .......
     * .......
     * ...@.@.
     * ..@.@..
     * .@.@...
     * ..@.@..
     * ...@.@.
     * .......
     * .......
     */
0, 7, 3, 5, 4, 69, 81, 80, 80,

    /* 172 [¬] NOT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 2
     * .......
     * .......
     * .......
     * .......
     * .......
     * .@@@@@.
     * .....@.
     * .......
     * .......
     * .......
     * .......
     * .......
     */
0, 7, 1, 5, 2, 31, 8,

    /* 173 SOFT HYPHEN
     * Duplicate of = 45 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * @@@@
     * ....
     * ....
     * ....
     * ....
     * ....
     */
45,

    /* 174 [®] REGISTERED SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * ..@@@@..
     * .@....@.
     * @.@@@..@
     * @.@..@.@
     * @.@@@..@
     * @.@..@.@
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 2, 2, 8, 143, 80, 103, 105, 103, 169, 16, 15,

    /* 175 [¯] MACRON
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 0
     * Pixel start Y = 0
     * Data length = 1
     * @@@@@@@
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     * .......
     */
0, 7, 0, 0, 1, 127,

    /* 176 [°] DEGREE SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 2
     * ....
     * ....
     * ..@.
     * .@.@
     * ..@.
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     */
0, 4, 2, 2, 2, 41, 1,

    /* 177 [±] PLUS-MINUS SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 3
     * Data length = 6
     * .......
     * .......
     * .......
     * ...@...
     * ...@...
     * .@@@@@.
     * ...@...
     * ...@...
     * .......
     * .@@@@@.
     * .......
     * .......
     */
0, 7, 3, 3, 6, 129, 240, 33, 16, 0, 31,

    /* 178 [²] SUPERSCRIPT TWO
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ....
     * ....
     * .@@.
     * @..@
     * ..@.
     * .@..
     * @@@@
     * ....
     * ....
     * ....
     * ....
     * ....
     */
0, 4, 1, 2, 3, 75, 146, 7,

    /* 179 [³] SUPERSCRIPT THREE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ....
     * ....
     * .@@.
     * @..@
     * ..@.
     * @..@
     * .@@.
     * ....
     * ....
     * ....
     * ....
     * ....
     */
0, 4, 1, 2, 3, 75, 74, 3,

    /* 180 [´] ACUTE ACCENT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 1
     * ....
     * ..@.
     * .@..
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     */
0, 4, 2, 1, 1, 9,

    /* 181 [µ] MICRO SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 7
     * .......
     * .......
     * .......
     * .......
     * .@...@.
     * .@...@.
     * .@...@.
     * .@...@.
     * .@...@.
     * .@@@@.@
     * .@.....
     * .@.....
     */
0, 7, 1, 4, 7, 145, 72, 36, 18, 121, 5, 2,

    /* 182 [¶] PILCROW SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * ..@@@@.
     * .@@@.@.
     * .@@@.@.
     * .@@@.@.
     * ..@@.@.
     * ...@.@.
     * ...@.@.
     * ...@.@.
     * ...@.@.
     * .......
     */
0, 7, 2, 2, 8, 207, 229, 114, 177, 80, 40, 20, 10,

    /* 183 [·] MIDDLE DOT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * .@.
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 5, 1, 1,

    /* 184 [¸] CEDILLA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 2
     * Pixel start Y = 10
     * Data length = 1
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ..@.
     * .@@.
     */
0, 4, 2, 10, 1, 25,

    /* 185 [¹] SUPERSCRIPT ONE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 3
     * ....
     * ....
     * ..@.
     * .@@.
     * ..@.
     * ..@.
     * ..@.
     * ....
     * ....
     * ....
     * ....
     * ....
     */
0, 4, 2, 2, 3, 25, 17, 1,

    /* 186 [º] MASCULINE ORDINAL INDICATOR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * .....
     * .....
     * .@@@.
     * .@.@.
     * .@.@.
     * .@@@.
     * .....
     * .@@@.
     * .....
     * .....
     * .....
     * .....
     */
0, 5, 1, 2, 4, 167, 148, 3, 14,

    /* 187 [»] RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 4
     * .......
     * .......
     * .......
     * .......
     * .......
     * .@.@...
     * ..@.@..
     * ...@.@.
     * ..@.@..
     * .@.@...
     * .......
     * .......
     */
0, 7, 1, 5, 4, 5, 5, 69, 81,

    /* 188 [¼] VULGAR FRACTION ONE QUARTER
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * .........
     * .........
     * .@...@...
     * @@...@...
     * .@..@....
     * .@..@...@
     * .@.@...@@
     * ...@..@.@
     * ..@..@@@@
     * ..@.....@
     * .........
     * .........
     */
0, 9, 1, 2, 9, 17, 35, 36, 72, 84, 140, 148, 60, 65,

    /* 189 [½] VULGAR FRACTION ONE HALF
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * .........
     * .........
     * .@...@...
     * @@...@...
     * .@..@....
     * .@..@.@@.
     * .@.@.@..@
     * ...@...@.
     * ..@...@..
     * ..@..@@@@
     * .........
     * .........
     */
0, 9, 1, 2, 9, 17, 35, 36, 72, 83, 137, 136, 8, 121,

    /* 190 [¾] VULGAR FRACTION THREE QUARTERS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * .........
     * .........
     * .@@...@..
     * @..@..@..
     * ..@..@...
     * @..@.@..@
     * .@@.@..@@
     * ....@.@.@
     * ...@.@@@@
     * ...@....@
     * .........
     * .........
     */
0, 9, 1, 2, 9, 35, 73, 72, 164, 180, 12, 21, 61, 66,

    /* 191 [¿] INVERTED QUESTION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 6
     * Pixel start Y = 0
     * Data length = 10
     * ......@
     * .......
     * .......
     * .......
     * ...@@..
     * .......
     * ...@...
     * ...@...
     * ..@....
     * .@...@.
     * .@...@.
     * ..@@@..
     */
0, 7, 6, 0, 10, 1, 0, 0, 6, 128, 64, 16, 68, 34, 14,

    /* 192 [À] LATIN CAPITAL LETTER A WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 11
     * ...@.....
     * ....@....
     * ....@....
     * ....@....
     * ...@.@...
     * ...@.@...
     * ..@...@..
     * ..@@@@@..
     * .@.....@.
     * .@.....@.
     * .........
     * .........
     */
0, 9, 3, 0, 11, 1, 4, 8, 16, 80, 160, 32, 194, 71, 144, 32,

    /* 193 [Á] LATIN CAPITAL LETTER A WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 5
     * Pixel start Y = 0
     * Data length = 11
     * .....@...
     * ....@....
     * ....@....
     * ....@....
     * ...@.@...
     * ...@.@...
     * ..@...@..
     * ..@@@@@..
     * .@.....@.
     * .@.....@.
     * .........
     * .........
     */
0, 9, 5, 0, 11, 1, 1, 2, 4, 20, 40, 136, 240, 17, 36, 8,

    /* 194 [Â] LATIN CAPITAL LETTER A WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 11
     * ....@....
     * ...@.@...
     * .........
     * ....@....
     * ...@.@...
     * ...@.@...
     * ..@...@..
     * ..@@@@@..
     * .@.....@.
     * .@.....@.
     * .........
     * .........
     */
0, 9, 4, 0, 11, 1, 5, 0, 8, 40, 80, 16, 225, 35, 72, 16,

    /* 195 [Ã] LATIN CAPITAL LETTER A WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 11
     * ...@@.@..
     * ..@.@@...
     * ....@....
     * ....@....
     * ...@.@...
     * ...@.@...
     * ..@...@..
     * ..@@@@@..
     * .@.....@.
     * .@.....@.
     * .........
     * .........
     */
0, 9, 3, 0, 11, 11, 13, 8, 16, 80, 160, 32, 194, 71, 144, 32,

    /* 196 [Ä] LATIN CAPITAL LETTER A WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 11
     * ..@...@..
     * .........
     * ....@....
     * ....@....
     * ...@.@...
     * ...@.@...
     * ..@...@..
     * ..@@@@@..
     * .@.....@.
     * .@.....@.
     * .........
     * .........
     */
0, 9, 2, 0, 11, 17, 0, 16, 32, 160, 64, 65, 132, 143, 32, 65,

    /* 197 [Å] LATIN CAPITAL LETTER A WITH RING ABOVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 11
     * ....@....
     * ...@.@...
     * ....@....
     * ....@....
     * ...@.@...
     * ...@.@...
     * ..@...@..
     * ..@@@@@..
     * .@.....@.
     * .@.....@.
     * .........
     * .........
     */
0, 9, 4, 0, 11, 1, 5, 4, 8, 40, 80, 16, 225, 35, 72, 16,

    /* 198 [Æ] LATIN CAPITAL LETTER AE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 13
     * Pixel start X = 4
     * Pixel start Y = 2
     * Data length = 13
     * .............
     * .............
     * ....@@@@@@@@.
     * ....@@.......
     * ...@.@.......
     * ...@.@@@@@@..
     * ..@..@.......
     * ..@@@@.......
     * .@...@.......
     * .@...@@@@@@@.
     * .............
     * .............
     */
0, 13, 4, 2, 13, 255, 96, 0, 10, 64, 63, 36, 128, 7, 136, 0, 241, 7,

    /* 199 [Ç] LATIN CAPITAL LETTER C WITH CEDILLA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 11
     * .........
     * .........
     * ...@@@@..
     * ..@....@.
     * .@......@
     * .@.......
     * .@.......
     * .@......@
     * ..@....@.
     * ...@@@@..
     * .....@...
     * ....@@...
     */
0, 9, 3, 2, 11, 15, 33, 129, 2, 4, 8, 36, 132, 7, 4, 12,

    /* 200 [È] LATIN CAPITAL LETTER E WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 11
     * ...@.....
     * ....@....
     * .@@@@@@@.
     * .@.......
     * .@.......
     * .@@@@@@..
     * .@.......
     * .@.......
     * .@.......
     * .@@@@@@@.
     * .........
     * .........
     */
0, 9, 3, 0, 11, 1, 4, 127, 2, 4, 248, 17, 32, 64, 128, 63,

    /* 201 [É] LATIN CAPITAL LETTER E WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 5
     * Pixel start Y = 0
     * Data length = 11
     * .....@...
     * ....@....
     * .@@@@@@@.
     * .@.......
     * .@.......
     * .@@@@@@..
     * .@.......
     * .@.......
     * .@.......
     * .@@@@@@@.
     * .........
     * .........
     */
0, 9, 5, 0, 11, 1, 193, 159, 0, 1, 126, 4, 8, 16, 224, 15,

    /* 202 [Ê] LATIN CAPITAL LETTER E WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 11
     * ....@....
     * ...@.@...
     * .@@@@@@@.
     * .@.......
     * .@.......
     * .@@@@@@..
     * .@.......
     * .@.......
     * .@.......
     * .@@@@@@@.
     * .........
     * .........
     */
0, 9, 4, 0, 11, 1, 133, 63, 1, 2, 252, 8, 16, 32, 192, 31,

    /* 203 [Ë] LATIN CAPITAL LETTER E WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 11
     * ..@...@..
     * .........
     * .@@@@@@@.
     * .@.......
     * .@.......
     * .@@@@@@..
     * .@.......
     * .@.......
     * .@.......
     * .@@@@@@@.
     * .........
     * .........
     */
0, 9, 2, 0, 11, 17, 0, 254, 4, 8, 240, 35, 64, 128, 0, 127,

    /* 204 [Ì] LATIN CAPITAL LETTER I WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 0
     * Data length = 4
     * @..
     * .@.
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 0, 0, 4, 17, 36, 73, 18,

    /* 205 [Í] LATIN CAPITAL LETTER I WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 4
     * ..@
     * .@.
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 2, 0, 4, 5, 73, 146, 4,

    /* 206 [Î] LATIN CAPITAL LETTER I WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 0
     * Data length = 4
     * .@.
     * @.@
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 1, 0, 4, 21, 146, 36, 9,

    /* 207 [Ï] LATIN CAPITAL LETTER I WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 0
     * Data length = 4
     * @.@
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 0, 0, 4, 133, 36, 73, 18,

    /* 208 [Ð] LATIN CAPITAL LETTER ETH
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * .........
     * .........
     * .@@@@@...
     * .@....@..
     * .@.....@.
     * @@@@...@.
     * .@.....@.
     * .@.....@.
     * .@....@..
     * .@@@@@...
     * .........
     * .........
     */
0, 9, 1, 2, 9, 31, 66, 4, 61, 18, 36, 72, 136, 15,

    /* 209 [Ñ] LATIN CAPITAL LETTER N WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 12
     * ...@@..@..
     * ..@..@@...
     * .@......@.
     * .@@.....@.
     * .@.@....@.
     * .@..@...@.
     * .@...@..@.
     * .@....@.@.
     * .@.....@@.
     * .@......@.
     * ..........
     * ..........
     */
0, 10, 3, 0, 12, 19, 50, 4, 50, 72, 33, 137, 68, 18, 74, 48, 129,

    /* 210 [Ò] LATIN CAPITAL LETTER O WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 12
     * ...@......
     * ....@.....
     * ...@@@@...
     * ..@....@..
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * ..@....@..
     * ...@@@@...
     * ..........
     * ..........
     */
0, 10, 3, 0, 12, 1, 8, 240, 32, 68, 32, 129, 4, 18, 136, 16, 60,

    /* 211 [Ó] LATIN CAPITAL LETTER O WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 6
     * Pixel start Y = 0
     * Data length = 12
     * ......@...
     * .....@....
     * ...@@@@...
     * ..@....@..
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * ..@....@..
     * ...@@@@...
     * ..........
     * ..........
     */
0, 10, 6, 0, 12, 1, 2, 30, 132, 8, 36, 144, 64, 2, 17, 130, 7,

    /* 212 [Ô] LATIN CAPITAL LETTER O WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 12
     * ....@@....
     * ...@..@...
     * ...@@@@...
     * ..@....@..
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * ..@....@..
     * ...@@@@...
     * ..........
     * ..........
     */
0, 10, 4, 0, 12, 3, 18, 120, 16, 34, 144, 64, 2, 9, 68, 8, 30,

    /* 213 [Õ] LATIN CAPITAL LETTER O WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 12
     * ...@@..@..
     * ..@..@@...
     * ...@@@@...
     * ..@....@..
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * ..@....@..
     * ...@@@@...
     * ..........
     * ..........
     */
0, 10, 3, 0, 12, 19, 50, 240, 32, 68, 32, 129, 4, 18, 136, 16, 60,

    /* 214 [Ö] LATIN CAPITAL LETTER O WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 12
     * ...@..@...
     * ..........
     * ...@@@@...
     * ..@....@..
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * ..@....@..
     * ...@@@@...
     * ..........
     * ..........
     */
0, 10, 3, 0, 12, 9, 0, 240, 32, 68, 32, 129, 4, 18, 136, 16, 60,

    /* 215 [×] MULTIPLICATION SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 5
     * .......
     * .......
     * .......
     * .......
     * .@...@.
     * ..@.@..
     * ...@...
     * ..@.@..
     * .@...@.
     * .......
     * .......
     * .......
     */
0, 7, 1, 4, 5, 17, 5, 65, 17, 1,

    /* 216 [Ø] LATIN CAPITAL LETTER O WITH STROKE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 10
     * ..........
     * ..........
     * ...@@@@.@.
     * ..@....@..
     * .@....@.@.
     * .@...@..@.
     * .@..@...@.
     * .@.@....@.
     * ..@....@..
     * .@.@@@@...
     * ..........
     * ..........
     */
0, 10, 3, 2, 10, 47, 66, 132, 18, 73, 34, 133, 8, 209, 3,

    /* 217 [Ù] LATIN CAPITAL LETTER U WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 12
     * ....@.....
     * .....@....
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * ..@@@@@@..
     * ..........
     * ..........
     */
0, 10, 4, 0, 12, 1, 8, 2, 9, 36, 144, 64, 2, 9, 36, 16, 63,

    /* 218 [Ú] LATIN CAPITAL LETTER U WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 5
     * Pixel start Y = 0
     * Data length = 12
     * .....@....
     * ....@.....
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * ..@@@@@@..
     * ..........
     * ..........
     */
0, 10, 5, 0, 12, 1, 2, 129, 4, 18, 72, 32, 129, 4, 18, 136, 31,

    /* 219 [Û] LATIN CAPITAL LETTER U WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 12
     * ....@@....
     * ...@..@...
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * ..@@@@@@..
     * ..........
     * ..........
     */
0, 10, 4, 0, 12, 3, 18, 2, 9, 36, 144, 64, 2, 9, 36, 16, 63,

    /* 220 [Ü] LATIN CAPITAL LETTER U WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 12
     * ...@..@...
     * ..........
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * .@......@.
     * ..@@@@@@..
     * ..........
     * ..........
     */
0, 10, 3, 0, 12, 9, 0, 4, 18, 72, 32, 129, 4, 18, 72, 32, 126,

    /* 221 [Ý] LATIN CAPITAL LETTER Y WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 5
     * Pixel start Y = 0
     * Data length = 11
     * .....@...
     * ....@....
     * @.......@
     * .@.....@.
     * ..@...@..
     * ...@.@...
     * ....@....
     * ....@....
     * ....@....
     * ....@....
     * .........
     * .........
     */
0, 9, 5, 0, 11, 1, 33, 160, 32, 34, 40, 32, 64, 128, 0, 1,

    /* 222 [Þ] LATIN CAPITAL LETTER THORN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * .........
     * .........
     * .@.......
     * .@.......
     * .@@@@@@..
     * .@.....@.
     * .@.....@.
     * .@@@@@@..
     * .@.......
     * .@.......
     * .........
     * .........
     */
0, 9, 1, 2, 8, 1, 2, 252, 8, 18, 228, 71, 128,

    /* 223 [ß] LATIN SMALL LETTER SHARP S
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@.@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@.@@@..
     * ........
     * ........
     */
0, 8, 2, 2, 8, 143, 144, 144, 142, 144, 144, 144, 14,

    /* 224 [à] LATIN SMALL LETTER A WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 9
     * ........
     * ...@....
     * ....@...
     * ........
     * ..@@@@..
     * .@....@.
     * ..@@@@@.
     * .@....@.
     * .@....@.
     * ..@@@@.@
     * ........
     * ........
     */
0, 8, 3, 1, 9, 1, 2, 128, 71, 136, 79, 72, 136, 23,

    /* 225 [á] LATIN SMALL LETTER A WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 4
     * Pixel start Y = 1
     * Data length = 9
     * ........
     * ....@...
     * ...@....
     * ........
     * ..@@@@..
     * .@....@.
     * ..@@@@@.
     * .@....@.
     * .@....@.
     * ..@@@@.@
     * ........
     * ........
     */
0, 8, 4, 1, 9, 129, 0, 192, 35, 196, 39, 36, 196, 11,

    /* 226 [â] LATIN SMALL LETTER A WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 9
     * ........
     * ...@@...
     * ..@..@..
     * ........
     * ..@@@@..
     * .@....@.
     * ..@@@@@.
     * .@....@.
     * .@....@.
     * ..@@@@.@
     * ........
     * ........
     */
0, 8, 3, 1, 9, 131, 4, 128, 71, 136, 79, 72, 136, 23,

    /* 227 [ã] LATIN SMALL LETTER A WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 9
     * ........
     * ..@@..@.
     * .@..@@..
     * ........
     * ..@@@@..
     * .@....@.
     * ..@@@@@.
     * .@....@.
     * .@....@.
     * ..@@@@.@
     * ........
     * ........
     */
0, 8, 2, 1, 9, 147, 12, 0, 143, 16, 159, 144, 16, 47,

    /* 228 [ä] LATIN SMALL LETTER A WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * ..@..@..
     * ........
     * ..@@@@..
     * .@....@.
     * ..@@@@@.
     * .@....@.
     * .@....@.
     * ..@@@@.@
     * ........
     * ........
     */
0, 8, 2, 2, 8, 9, 0, 143, 16, 159, 144, 16, 47,

    /* 229 [å] LATIN SMALL LETTER A WITH RING ABOVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 10
     * ...@@...
     * ..@..@..
     * ...@@...
     * ........
     * ..@@@@..
     * .@....@.
     * ..@@@@@.
     * .@....@.
     * .@....@.
     * ..@@@@.@
     * ........
     * ........
     */
0, 8, 3, 0, 10, 131, 4, 3, 128, 71, 136, 79, 72, 136, 23,

    /* 230 [æ] LATIN SMALL LETTER AE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 13
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 10
     * .............
     * .............
     * .............
     * .............
     * ..@@@@.@@@@..
     * .@....@....@.
     * ..@@@@@@@@@@.
     * .@....@......
     * .@....@....@.
     * ..@@@@.@@@@..
     * .............
     * .............
     */
0, 13, 2, 4, 10, 239, 17, 66, 252, 79, 8, 8, 33, 222, 3,

    /* 231 [ç] LATIN SMALL LETTER C WITH CEDILLA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 7
     * .......
     * .......
     * .......
     * .......
     * ..@@@@.
     * .@....@
     * .@.....
     * .@.....
     * .@....@
     * ..@@@@.
     * ....@..
     * ...@@..
     */
0, 7, 2, 4, 7, 79, 40, 16, 8, 121, 16, 12,

    /* 232 [è] LATIN SMALL LETTER E WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 9
     * ........
     * ...@....
     * ....@...
     * ........
     * ..@@@@..
     * .@....@.
     * .@@@@@@.
     * .@......
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 3, 1, 9, 1, 2, 128, 71, 200, 79, 64, 136, 7,

    /* 233 [é] LATIN SMALL LETTER E WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 4
     * Pixel start Y = 1
     * Data length = 9
     * ........
     * ....@...
     * ...@....
     * ........
     * ..@@@@..
     * .@....@.
     * .@@@@@@.
     * .@......
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 4, 1, 9, 129, 0, 192, 35, 228, 39, 32, 196, 3,

    /* 234 [ê] LATIN SMALL LETTER E WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 9
     * ........
     * ...@@...
     * ..@..@..
     * ........
     * ..@@@@..
     * .@....@.
     * .@@@@@@.
     * .@......
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 3, 1, 9, 131, 4, 128, 71, 200, 79, 64, 136, 7,

    /* 235 [ë] LATIN SMALL LETTER E WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * ..@..@..
     * ........
     * ..@@@@..
     * .@....@.
     * .@@@@@@.
     * .@......
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 2, 2, 8, 9, 0, 143, 144, 159, 128, 16, 15,

    /* 236 [ì] LATIN SMALL LETTER I WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 1
     * Data length = 4
     * ...
     * @..
     * .@.
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 0, 1, 4, 17, 36, 73, 2,

    /* 237 [í] LATIN SMALL LETTER I WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 3
     * ...
     * ..@
     * .@.
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 2, 1, 3, 5, 73, 146,

    /* 238 [î] LATIN SMALL LETTER I WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 1
     * Data length = 4
     * ...
     * .@.
     * @.@
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 1, 1, 4, 21, 146, 36, 1,

    /* 239 [ï] LATIN SMALL LETTER I WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * @.@
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 0, 2, 3, 133, 36, 73,

    /* 240 [ð] LATIN SMALL LETTER ETH
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * ..@@.@..
     * ....@...
     * ...@.@..
     * ..@@@@@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 2, 2, 8, 11, 4, 10, 159, 144, 144, 16, 15,

    /* 241 [ñ] LATIN SMALL LETTER N WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 8
     * .......
     * ..@@.@.
     * .@.@@..
     * .......
     * .@.@@..
     * .@@..@.
     * .@...@.
     * .@...@.
     * .@...@.
     * .@...@.
     * .......
     * .......
     */
0, 7, 2, 1, 8, 75, 3, 208, 152, 68, 34, 145, 8,

    /* 242 [ò] LATIN SMALL LETTER O WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 9
     * ........
     * ...@....
     * ....@...
     * ........
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 3, 1, 9, 1, 2, 128, 71, 72, 72, 72, 136, 7,

    /* 243 [ó] LATIN SMALL LETTER O WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 4
     * Pixel start Y = 1
     * Data length = 9
     * ........
     * ....@...
     * ...@....
     * ........
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 4, 1, 9, 129, 0, 192, 35, 36, 36, 36, 196, 3,

    /* 244 [ô] LATIN SMALL LETTER O WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 9
     * ........
     * ...@@...
     * ..@..@..
     * ........
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 3, 1, 9, 131, 4, 128, 71, 72, 72, 72, 136, 7,

    /* 245 [õ] LATIN SMALL LETTER O WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 9
     * ........
     * ..@@..@.
     * .@..@@..
     * ........
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 2, 1, 9, 147, 12, 0, 143, 144, 144, 144, 16, 15,

    /* 246 [ö] LATIN SMALL LETTER O WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * ..@..@..
     * ........
     * ..@@@@..
     * .@....@.
     * .@....@.
     * .@....@.
     * .@....@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 2, 2, 8, 9, 0, 143, 144, 144, 144, 16, 15,

    /* 247 [÷] DIVISION SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 4
     * Data length = 4
     * .......
     * .......
     * .......
     * .......
     * ...@...
     * .......
     * .@@@@@.
     * .......
     * ...@...
     * .......
     * .......
     * .......
     */
0, 7, 3, 4, 4, 1, 240, 1, 16,

    /* 248 [ø] LATIN SMALL LETTER O WITH STROKE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 6
     * Pixel start Y = 3
     * Data length = 7
     * ........
     * ........
     * ........
     * ......@.
     * ..@@@@..
     * .@...@@.
     * .@..@.@.
     * .@.@..@.
     * .@@...@.
     * ..@@@@..
     * .@......
     * ........
     */
0, 8, 6, 3, 7, 241, 136, 73, 41, 25, 241, 8,

    /* 249 [ù] LATIN SMALL LETTER U WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 1
     * Data length = 8
     * .......
     * ..@....
     * ...@...
     * .......
     * .@...@.
     * .@...@.
     * .@...@.
     * .@...@.
     * .@..@@.
     * ..@@.@.
     * .......
     * .......
     */
0, 7, 2, 1, 8, 1, 1, 16, 137, 68, 34, 25, 11,

    /* 250 [ú] LATIN SMALL LETTER U WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 4
     * Pixel start Y = 1
     * Data length = 8
     * .......
     * ....@..
     * ...@...
     * .......
     * .@...@.
     * .@...@.
     * .@...@.
     * .@...@.
     * .@..@@.
     * ..@@.@.
     * .......
     * .......
     */
0, 7, 4, 1, 8, 65, 0, 68, 34, 145, 72, 198, 2,

    /* 251 [û] LATIN SMALL LETTER U WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 8
     * .......
     * ...@...
     * ..@.@..
     * .......
     * .@...@.
     * .@...@.
     * .@...@.
     * .@...@.
     * .@..@@.
     * ..@@.@.
     * .......
     * .......
     */
0, 7, 3, 1, 8, 65, 1, 136, 68, 34, 145, 140, 5,

    /* 252 [ü] LATIN SMALL LETTER U WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * .......
     * .......
     * .@...@.
     * .......
     * .@...@.
     * .@...@.
     * .@...@.
     * .@...@.
     * .@..@@.
     * ..@@.@.
     * .......
     * .......
     */
0, 7, 1, 2, 7, 17, 64, 36, 18, 137, 100, 44,

    /* 253 [ý] LATIN SMALL LETTER Y WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 4
     * Pixel start Y = 1
     * Data length = 9
     * .......
     * ....@..
     * ...@...
     * .......
     * .@...@.
     * .@...@.
     * ..@.@..
     * ..@.@..
     * ...@...
     * ...@...
     * ..@....
     * @@.....
     */
0, 7, 4, 1, 9, 65, 0, 68, 34, 10, 5, 129, 32, 12,

    /* 254 [þ] LATIN SMALL LETTER THORN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 10
     * ........
     * ........
     * .@......
     * .@......
     * .@.@@@..
     * .@@...@.
     * .@....@.
     * .@....@.
     * .@@...@.
     * .@.@@@..
     * .@......
     * .@......
     */
0, 8, 1, 2, 10, 1, 1, 29, 35, 33, 33, 35, 29, 1, 1,

};
