// File generated by font_compiler.py
// FONT_SERIF8[] binary size: 2120
// Generated from https://raw.githubusercontent.com/robhagemans/hoard-of-bitfonts/master/windows/windows-3.1/ms-serif-e/MS_Serif_8.yaff

#include <stdint.h>

const uint8_t FONT_SERIF8[] = {
    /* Metadata block:
     * First glyph byte = 32
     * End glyph byte = 255
     * Ascent = 9
     * Shift-up = 2
     * Default/fallback glyph = 128
     */
    32, 255, 9, 2, 128,

    /* 32 [ ] SPACE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 0
     * Pixel start Y = 0
     * Data length = 0
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     */
0, 2, 0, 0, 0,

    /* 33 [!] EXCLAMATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     * .@.
     * ...
     * ...
     */
0, 3, 1, 2, 4, 73, 146, 0, 1,

    /* 34 ["] QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 2
     * ....
     * ....
     * .@.@
     * .@.@
     * .@.@
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     * ....
     */
0, 4, 1, 2, 2, 85, 5,

    /* 35 [#] NUMBER SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ..@.@.
     * ..@.@.
     * .@@@@@
     * ..@.@.
     * ..@.@.
     * ..@.@.
     * .@@@@@
     * ..@.@.
     * ..@.@.
     * ......
     * ......
     */
0, 6, 2, 2, 7, 69, 249, 20, 69, 249, 20, 5,

    /* 36 [$] DOLLAR SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ...@.
     * ..@@.
     * .@..@
     * .@...
     * ..@..
     * ...@.
     * ....@
     * .@..@
     * ..@@.
     * ...@.
     * .....
     */
0, 5, 3, 2, 6, 49, 41, 8, 130, 146, 33,

    /* 37 [%] PERCENT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 11
     * ..........
     * ..........
     * ..@@.....@
     * .@..@...@.
     * .@..@..@..
     * ..@@..@...
     * .....@....
     * ....@..@@.
     * ...@..@..@
     * ..@...@..@
     * .@.....@@.
     * ..........
     * ..........
     */
0, 10, 2, 2, 11, 131, 18, 73, 194, 4, 8, 144, 33, 73, 164, 96,

    /* 38 [&] AMPERSAND
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * ..@@....
     * .@..@...
     * .@..@...
     * ..@@....
     * ..@@....
     * .@..@.@@
     * .@..@.@.
     * .@...@..
     * ..@@@.@.
     * ........
     * ........
     */
0, 8, 2, 2, 9, 131, 132, 4, 3, 131, 180, 148, 8, 23,

    /* 39 ['] APOSTROPHE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 1
     * ..
     * ..
     * .@
     * .@
     * .@
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     */
0, 2, 1, 2, 1, 21,

    /* 40 [(] LEFT PARENTHESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * ..@
     * ..@
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ..@
     * ..@
     */
0, 3, 2, 2, 4, 41, 73, 146, 72,

    /* 41 [)] RIGHT PARENTHESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * .@.
     * .@.
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * .@.
     * .@.
     */
0, 3, 1, 2, 4, 137, 36, 73, 74,

    /* 42 [*] ASTERISK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * .....
     * .....
     * .@..@
     * ..@@.
     * ..@@.
     * .@..@
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     */
0, 5, 1, 2, 3, 201, 152, 4,

    /* 43 [+] PLUS SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 4
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ...@..
     * ...@..
     * .@@@@@
     * ...@..
     * ...@..
     * ......
     * ......
     * ......
     * ......
     */
0, 6, 3, 4, 4, 65, 124, 4, 1,

    /* 44 [,] COMMA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 10
     * Data length = 1
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * .@
     * .@
     * ..
     */
0, 2, 1, 10, 1, 5,

    /* 45 [-] HYPHEN-MINUS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 6
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * .@@
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 6, 1, 3,

    /* 46 [.] FULL STOP
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 10
     * Data length = 1
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * .@
     * ..
     * ..
     */
0, 2, 1, 10, 1, 1,

    /* 47 [/] SOLIDUS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * .@.
     * .@.
     * .@.
     * .@.
     * ...
     * ...
     */
0, 3, 2, 2, 3, 73, 82, 146,

    /* 48 [0] DIGIT ZERO
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@@.
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 2, 2, 6, 147, 82, 74, 41, 37, 3,

    /* 49 [1] DIGIT ONE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ...@.
     * ..@@.
     * ...@.
     * ...@.
     * ...@.
     * ...@.
     * ...@.
     * ...@.
     * ..@@@
     * .....
     * .....
     */
0, 5, 3, 2, 6, 49, 132, 16, 66, 136, 3,

    /* 50 [2] DIGIT TWO
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@@.
     * .@..@
     * ....@
     * ....@
     * ...@.
     * ..@..
     * .@...
     * .@..@
     * .@@@@
     * .....
     * .....
     */
0, 5, 2, 2, 6, 147, 16, 34, 34, 164, 7,

    /* 51 [3] DIGIT THREE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@@.
     * .@..@
     * ....@
     * ....@
     * ..@@.
     * ....@
     * ....@
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 2, 2, 6, 147, 16, 50, 8, 37, 3,

    /* 52 [4] DIGIT FOUR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 4
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ....@
     * ...@@
     * ...@@
     * ..@.@
     * ..@.@
     * .@..@
     * .@@@@
     * ....@
     * ....@
     * .....
     * .....
     */
0, 5, 4, 2, 6, 49, 166, 84, 122, 8, 1,

    /* 53 [5] DIGIT FIVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * .@@@@
     * .@...
     * .@...
     * .@@@.
     * .@..@
     * ....@
     * ....@
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 1, 2, 6, 47, 132, 147, 16, 74, 6,

    /* 54 [6] DIGIT SIX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@@.
     * .@..@
     * .@...
     * .@...
     * .@@@.
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 2, 2, 6, 147, 66, 56, 41, 37, 3,

    /* 55 [7] DIGIT SEVEN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * .@@@@
     * .@..@
     * .@..@
     * ...@.
     * ...@.
     * ...@.
     * ..@..
     * ..@..
     * ..@..
     * .....
     * .....
     */
0, 5, 1, 2, 6, 47, 37, 66, 136, 16, 2,

    /* 56 [8] DIGIT EIGHT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@@.
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 2, 2, 6, 147, 82, 50, 41, 37, 3,

    /* 57 [9] DIGIT NINE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@@.
     * .@..@
     * .@..@
     * .@..@
     * ..@@@
     * ....@
     * ....@
     * ....@
     * ..@@.
     * .....
     * .....
     */
0, 5, 2, 2, 6, 147, 82, 114, 8, 33, 3,

    /* 58 [:] COLON
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 2
     * ..
     * ..
     * ..
     * ..
     * .@
     * ..
     * ..
     * ..
     * ..
     * ..
     * .@
     * ..
     * ..
     */
0, 2, 1, 4, 2, 1, 16,

    /* 59 [;] SEMICOLON
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 2
     * ..
     * ..
     * ..
     * ..
     * .@
     * ..
     * ..
     * ..
     * ..
     * ..
     * .@
     * .@
     * ..
     */
0, 2, 1, 4, 2, 1, 80,

    /* 60 [<] LESS-THAN SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 4
     * Pixel start Y = 5
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ......
     * ....@@
     * ..@@..
     * .@....
     * ..@@..
     * ....@@
     * ......
     * ......
     * ......
     */
0, 6, 4, 5, 4, 51, 2, 3, 3,

    /* 61 [=] EQUALS SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 6
     * Data length = 3
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * .@@@@@
     * ......
     * .@@@@@
     * ......
     * ......
     * ......
     * ......
     */
0, 6, 1, 6, 3, 31, 240, 1,

    /* 62 [>] GREATER-THAN SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ......
     * .@@...
     * ...@@.
     * .....@
     * ...@@.
     * .@@...
     * ......
     * ......
     * ......
     */
0, 6, 1, 5, 4, 3, 3, 49, 3,

    /* 63 [?] QUESTION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@@.
     * .@..@
     * .@..@
     * ....@
     * ...@.
     * ..@..
     * ..@..
     * .....
     * ..@..
     * .....
     * .....
     */
0, 5, 2, 2, 6, 147, 18, 34, 66, 0, 1,

    /* 64 [@] COMMERCIAL AT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 11
     * .........
     * .........
     * ...@@@@..
     * ..@....@.
     * .@..@@@.@
     * .@.@..@.@
     * .@.@..@.@
     * .@.@..@.@
     * .@.@..@.@
     * .@..@@.@.
     * ..@......
     * ...@@@@..
     * .........
     */
0, 9, 3, 2, 11, 15, 33, 185, 74, 149, 42, 85, 42, 139, 0, 30,

    /* 65 [A] LATIN CAPITAL LETTER A
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 4
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * ....@...
     * ....@...
     * ...@.@..
     * ...@.@..
     * ...@.@..
     * ..@...@.
     * ..@@@@@.
     * ..@...@.
     * .@@@.@@@
     * ........
     * ........
     */
0, 8, 4, 2, 9, 1, 129, 130, 130, 66, 196, 71, 228, 14,

    /* 66 [B] LATIN CAPITAL LETTER B
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * .@@@@..
     * ..@..@.
     * ..@..@.
     * ..@..@.
     * ..@@@..
     * ..@..@.
     * ..@..@.
     * ..@..@.
     * .@@@@..
     * .......
     * .......
     */
0, 7, 1, 2, 8, 15, 137, 68, 226, 144, 72, 36, 15,

    /* 67 [C] LATIN CAPITAL LETTER C
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * ...@@@@
     * ..@...@
     * ..@....
     * ..@....
     * ..@....
     * ..@....
     * ..@....
     * ..@...@
     * ...@@@.
     * .......
     * .......
     */
0, 7, 3, 2, 8, 79, 36, 16, 8, 4, 2, 17, 7,

    /* 68 [D] LATIN CAPITAL LETTER D
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@@@@...
     * ..@..@..
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@..@..
     * .@@@@...
     * ........
     * ........
     */
0, 8, 1, 2, 9, 15, 18, 34, 34, 34, 34, 34, 18, 15,

    /* 69 [E] LATIN CAPITAL LETTER E
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * .@@@@@.
     * ..@..@.
     * ..@....
     * ..@.@..
     * ..@@@..
     * ..@.@..
     * ..@....
     * ..@..@.
     * .@@@@@.
     * .......
     * .......
     */
0, 7, 1, 2, 8, 31, 137, 64, 225, 80, 8, 36, 31,

    /* 70 [F] LATIN CAPITAL LETTER F
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@@@@@
     * ..@..@
     * ..@...
     * ..@.@.
     * ..@@@.
     * ..@.@.
     * ..@...
     * ..@...
     * .@@@..
     * ......
     * ......
     */
0, 6, 1, 2, 7, 159, 36, 40, 142, 34, 8, 7,

    /* 71 [G] LATIN CAPITAL LETTER G
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * ...@@@@.
     * ..@...@.
     * ..@.....
     * ..@.....
     * ..@..@@@
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ...@@@..
     * ........
     * ........
     */
0, 8, 3, 2, 9, 143, 136, 128, 128, 156, 136, 136, 8, 7,

    /* 72 [H] LATIN CAPITAL LETTER H
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@@@.@@@
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@@@@@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * .@@@.@@@
     * ........
     * ........
     */
0, 8, 1, 2, 9, 119, 34, 34, 34, 62, 34, 34, 34, 119,

    /* 73 [I] LATIN CAPITAL LETTER I
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 5
     * ....
     * ....
     * .@@@
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * .@@@
     * ....
     * ....
     */
0, 4, 1, 2, 5, 39, 34, 34, 34, 7,

    /* 74 [J] LATIN CAPITAL LETTER J
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@@@
     * ...@.
     * ...@.
     * ...@.
     * ...@.
     * ...@.
     * ...@.
     * .@.@.
     * .@@..
     * .....
     * .....
     */
0, 5, 2, 2, 6, 71, 8, 33, 132, 148, 1,

    /* 75 [K] LATIN CAPITAL LETTER K
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@@@.@@.
     * ..@..@..
     * ..@.@...
     * ..@@....
     * ..@@....
     * ..@.@...
     * ..@..@..
     * ..@...@.
     * .@@@..@@
     * ........
     * ........
     */
0, 8, 1, 2, 9, 55, 18, 10, 6, 6, 10, 18, 34, 103,

    /* 76 [L] LATIN CAPITAL LETTER L
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@@@..
     * ..@...
     * ..@...
     * ..@...
     * ..@...
     * ..@...
     * ..@...
     * ..@..@
     * .@@@@@
     * ......
     * ......
     */
0, 6, 1, 2, 7, 135, 32, 8, 130, 32, 72, 31,

    /* 77 [M] LATIN CAPITAL LETTER M
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 12
     * ..........
     * ..........
     * .@@.....@@
     * ..@.....@.
     * ..@@...@@.
     * ..@@...@@.
     * ..@.@.@.@.
     * ..@.@.@.@.
     * ..@..@..@.
     * ..@..@..@.
     * .@@@...@@@
     * ..........
     * ..........
     */
0, 10, 1, 2, 12, 131, 9, 98, 140, 49, 170, 168, 34, 137, 36, 199, 1,

    /* 78 [N] LATIN CAPITAL LETTER N
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@@..@@@
     * ..@...@.
     * ..@@..@.
     * ..@@..@.
     * ..@.@.@.
     * ..@.@.@.
     * ..@..@@.
     * ..@..@@.
     * .@@@..@.
     * ........
     * ........
     */
0, 8, 1, 2, 9, 115, 34, 38, 38, 42, 42, 50, 50, 39,

    /* 79 [O] LATIN CAPITAL LETTER O
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * ...@@@..
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ...@@@..
     * ........
     * ........
     */
0, 8, 3, 2, 9, 135, 136, 136, 136, 136, 136, 136, 8, 7,

    /* 80 [P] LATIN CAPITAL LETTER P
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@@@@.
     * ..@..@
     * ..@..@
     * ..@..@
     * ..@@@.
     * ..@...
     * ..@...
     * ..@...
     * .@@@..
     * ......
     * ......
     */
0, 6, 1, 2, 7, 143, 36, 73, 142, 32, 8, 7,

    /* 81 [Q] LATIN CAPITAL LETTER Q
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 11
     * ........
     * ........
     * ...@@@..
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ...@@@..
     * ....@@..
     * .....@@.
     */
0, 8, 3, 2, 11, 135, 136, 136, 136, 136, 136, 136, 8, 7, 6, 12,

    /* 82 [R] LATIN CAPITAL LETTER R
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 8
     * .......
     * .......
     * .@@@@..
     * ..@..@.
     * ..@..@.
     * ..@..@.
     * ..@@@..
     * ..@.@..
     * ..@..@.
     * ..@..@.
     * .@@@.@@
     * .......
     * .......
     */
0, 7, 1, 2, 8, 15, 137, 68, 226, 80, 72, 36, 55,

    /* 83 [S] LATIN CAPITAL LETTER S
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * ...@@.
     * ..@.@.
     * ..@...
     * ..@...
     * ...@..
     * ....@.
     * ....@.
     * ..@.@.
     * ..@@..
     * ......
     * ......
     */
0, 6, 3, 2, 7, 163, 8, 2, 129, 32, 138, 1,

    /* 84 [T] LATIN CAPITAL LETTER T
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@@@@@
     * .@.@.@
     * ...@..
     * ...@..
     * ...@..
     * ...@..
     * ...@..
     * ...@..
     * ..@@@.
     * ......
     * ......
     */
0, 6, 1, 2, 7, 95, 69, 16, 4, 65, 16, 14,

    /* 85 [U] LATIN CAPITAL LETTER U
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@@@.@@@
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ...@@@..
     * ........
     * ........
     */
0, 8, 1, 2, 9, 119, 34, 34, 34, 34, 34, 34, 34, 28,

    /* 86 [V] LATIN CAPITAL LETTER V
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@@@.@@@
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ...@.@..
     * ...@.@..
     * ...@.@..
     * ....@...
     * ....@...
     * ........
     * ........
     */
0, 8, 1, 2, 9, 119, 34, 34, 34, 20, 20, 20, 8, 8,

    /* 87 [W] LATIN CAPITAL LETTER W
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 10
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 11
     * ..........
     * ..........
     * .@@@...@@@
     * ..@.....@.
     * ..@.....@.
     * ..@..@..@.
     * ..@..@..@.
     * ..@.@.@.@.
     * ..@.@.@.@.
     * ...@...@..
     * ...@...@..
     * ..........
     * ..........
     */
0, 10, 1, 2, 11, 199, 9, 34, 136, 36, 146, 168, 162, 10, 17, 68,

    /* 88 [X] LATIN CAPITAL LETTER X
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@@@.@@@
     * ..@...@.
     * ...@.@..
     * ...@.@..
     * ....@...
     * ...@.@..
     * ...@.@..
     * ..@...@.
     * .@@@.@@@
     * ........
     * ........
     */
0, 8, 1, 2, 9, 119, 34, 20, 20, 8, 20, 20, 34, 119,

    /* 89 [Y] LATIN CAPITAL LETTER Y
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@@@.@@@
     * ..@...@.
     * ..@...@.
     * ...@.@..
     * ...@.@..
     * ....@...
     * ....@...
     * ....@...
     * ...@@@..
     * ........
     * ........
     */
0, 8, 1, 2, 9, 119, 34, 34, 20, 20, 8, 8, 8, 28,

    /* 90 [Z] LATIN CAPITAL LETTER Z
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@@@@@
     * .@...@
     * ....@.
     * ....@.
     * ...@..
     * ..@...
     * ..@...
     * .@...@
     * .@@@@@
     * ......
     * ......
     */
0, 6, 1, 2, 7, 95, 132, 32, 132, 32, 68, 31,

    /* 91 [[] LEFT SQUARE BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * .@@
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@@
     */
0, 3, 1, 2, 4, 75, 146, 36, 201,

    /* 92 [\] REVERSE SOLIDUS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * ..@
     * ..@
     * ..@
     * ..@
     * ...
     * ...
     */
0, 3, 1, 2, 4, 73, 18, 73, 2,

    /* 93 []] RIGHT SQUARE BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * .@@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * ..@
     * .@@
     */
0, 3, 1, 2, 4, 147, 36, 73, 210,

    /* 94 [^] CIRCUMFLEX ACCENT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 1
     * .....
     * .....
     * ..@@.
     * .@..@
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     */
0, 5, 2, 2, 1, 147,

    /* 95 [_] LOW LINE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 0
     * Pixel start Y = 12
     * Data length = 1
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * @@@@@
     */
0, 5, 0, 12, 1, 31,

    /* 96 [`] GRAVE ACCENT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 1
     * ...
     * ...
     * .@.
     * ..@
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 2, 1, 17,

    /* 97 [a] LATIN SMALL LETTER A
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 4
     * .....
     * .....
     * .....
     * .....
     * .....
     * ..@@.
     * ....@
     * ..@@@
     * .@..@
     * .@..@
     * ..@@@
     * .....
     * .....
     */
0, 5, 2, 5, 4, 131, 92, 74, 14,

    /* 98 [b] LATIN SMALL LETTER B
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * @@...
     * .@...
     * .@...
     * .@@@.
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 0, 2, 6, 67, 8, 39, 165, 148, 12,

    /* 99 [c] LATIN SMALL LETTER C
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 4
     * .....
     * .....
     * .....
     * .....
     * .....
     * ..@@.
     * .@..@
     * .@...
     * .@...
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 2, 5, 4, 147, 66, 72, 6,

    /* 100 [d] LATIN SMALL LETTER D
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ...@@
     * ....@
     * ....@
     * ..@@@
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@@
     * .....
     * .....
     */
0, 5, 3, 2, 6, 67, 200, 165, 148, 146, 3,

    /* 101 [e] LATIN SMALL LETTER E
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 4
     * .....
     * .....
     * .....
     * .....
     * .....
     * ..@@.
     * .@..@
     * .@@@@
     * .@...
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 2, 5, 4, 147, 94, 72, 6,

    /* 102 [f] LATIN SMALL LETTER F
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 4
     * ...
     * ...
     * ..@
     * .@.
     * .@.
     * @@@
     * .@.
     * .@.
     * .@.
     * .@.
     * .@@
     * ...
     * ...
     */
0, 3, 2, 2, 4, 165, 75, 146, 1,

    /* 103 [g] LATIN SMALL LETTER G
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 5
     * .....
     * .....
     * .....
     * .....
     * .....
     * ..@@@
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@@
     * ....@
     * ..@@.
     */
0, 5, 2, 5, 5, 151, 82, 74, 14, 25,

    /* 104 [h] LATIN SMALL LETTER H
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * @@...
     * .@...
     * .@...
     * .@@@.
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * .....
     * .....
     */
0, 5, 0, 2, 6, 67, 8, 39, 165, 148, 18,

    /* 105 [i] LATIN SMALL LETTER I
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ..
     * ..
     * .@
     * ..
     * ..
     * @@
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     * ..
     */
0, 2, 1, 2, 3, 97, 85, 1,

    /* 106 [j] LATIN SMALL LETTER J
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ..
     * ..
     * .@
     * ..
     * ..
     * @@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * @.
     */
0, 2, 1, 2, 3, 97, 85, 13,

    /* 107 [k] LATIN SMALL LETTER K
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * @@...
     * .@...
     * .@...
     * .@..@
     * .@.@.
     * .@@..
     * .@@..
     * .@.@.
     * .@..@
     * .....
     * .....
     */
0, 5, 0, 2, 6, 67, 8, 169, 140, 81, 18,

    /* 108 [l] LATIN SMALL LETTER L
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 3
     * ..
     * ..
     * @@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     * ..
     */
0, 2, 0, 2, 3, 171, 170, 2,

    /* 109 [m] LATIN SMALL LETTER M
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 0
     * Pixel start Y = 5
     * Data length = 6
     * ........
     * ........
     * ........
     * ........
     * ........
     * @.@@.@@.
     * .@..@..@
     * .@..@..@
     * .@..@..@
     * .@..@..@
     * .@..@..@
     * ........
     * ........
     */
0, 8, 0, 5, 6, 109, 146, 146, 146, 146, 146,

    /* 110 [n] LATIN SMALL LETTER N
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 0
     * Pixel start Y = 5
     * Data length = 4
     * .....
     * .....
     * .....
     * .....
     * .....
     * @.@@.
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * .....
     * .....
     */
0, 5, 0, 5, 4, 77, 74, 41, 37,

    /* 111 [o] LATIN SMALL LETTER O
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 4
     * .....
     * .....
     * .....
     * .....
     * .....
     * ..@@.
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 2, 5, 4, 147, 82, 74, 6,

    /* 112 [p] LATIN SMALL LETTER P
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 0
     * Pixel start Y = 5
     * Data length = 5
     * .....
     * .....
     * .....
     * .....
     * .....
     * @.@@.
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * .@@@.
     * .@...
     * @@@..
     */
0, 5, 0, 5, 5, 77, 74, 41, 157, 56,

    /* 113 [q] LATIN SMALL LETTER Q
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 5
     * .....
     * .....
     * .....
     * .....
     * .....
     * ..@@.
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@@
     * ....@
     * ...@@
     */
0, 5, 2, 5, 5, 147, 82, 74, 14, 49,

    /* 114 [r] LATIN SMALL LETTER R
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 0
     * Pixel start Y = 5
     * Data length = 3
     * ....
     * ....
     * ....
     * ....
     * ....
     * @.@@
     * .@.@
     * .@..
     * .@..
     * .@..
     * .@@.
     * ....
     * ....
     */
0, 4, 0, 5, 3, 173, 34, 98,

    /* 115 [s] LATIN SMALL LETTER S
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 3
     * ....
     * ....
     * ....
     * ....
     * ....
     * ..@@
     * .@..
     * ..@.
     * ...@
     * ...@
     * .@@.
     * ....
     * ....
     */
0, 4, 2, 5, 3, 11, 33, 26,

    /* 116 [t] LATIN SMALL LETTER T
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 3
     * Data length = 3
     * ...
     * ...
     * ...
     * .@.
     * .@.
     * @@@
     * .@.
     * .@.
     * .@.
     * .@.
     * ..@
     * ...
     * ...
     */
0, 3, 1, 3, 3, 233, 146, 68,

    /* 117 [u] LATIN SMALL LETTER U
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 0
     * Pixel start Y = 5
     * Data length = 4
     * .....
     * .....
     * .....
     * .....
     * .....
     * @@.@@
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@@
     * .....
     * .....
     */
0, 5, 0, 5, 4, 91, 74, 41, 57,

    /* 118 [v] LATIN SMALL LETTER V
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 0
     * Pixel start Y = 5
     * Data length = 4
     * .....
     * .....
     * .....
     * .....
     * .....
     * @...@
     * @...@
     * .@.@.
     * .@.@.
     * ..@..
     * ..@..
     * .....
     * .....
     */
0, 5, 0, 5, 4, 49, 42, 69, 8,

    /* 119 [w] LATIN SMALL LETTER W
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 6
     * ........
     * ........
     * ........
     * ........
     * ........
     * .@@.@.@@
     * .@..@..@
     * .@.@.@.@
     * .@.@.@.@
     * ..@...@.
     * ..@...@.
     * ........
     * ........
     */
0, 8, 1, 5, 6, 107, 73, 85, 85, 34, 34,

    /* 120 [x] LATIN SMALL LETTER X
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 0
     * Pixel start Y = 5
     * Data length = 4
     * .....
     * .....
     * .....
     * .....
     * .....
     * @@.@@
     * .@.@.
     * ..@..
     * ..@..
     * .@.@.
     * @@.@@
     * .....
     * .....
     */
0, 5, 0, 5, 4, 91, 17, 162, 54,

    /* 121 [y] LATIN SMALL LETTER Y
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 5
     * .....
     * .....
     * .....
     * .....
     * .....
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * ..@..
     * ..@..
     * .@...
     */
0, 5, 1, 5, 5, 41, 165, 100, 132, 8,

    /* 122 [z] LATIN SMALL LETTER Z
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 5
     * Data length = 4
     * .....
     * .....
     * .....
     * .....
     * .....
     * .@@@@
     * .@..@
     * ...@.
     * ..@..
     * .@..@
     * .@@@@
     * .....
     * .....
     */
0, 5, 1, 5, 4, 47, 17, 145, 30,

    /* 123 [{] LEFT CURLY BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 6
     * ....
     * ....
     * ...@
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * .@..
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ...@
     */
0, 4, 3, 2, 6, 137, 136, 132, 136, 8, 1,

    /* 124 [|] VERTICAL LINE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 3
     * Data length = 3
     * ..
     * ..
     * ..
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     */
0, 2, 1, 3, 3, 85, 85, 1,

    /* 125 [}] RIGHT CURLY BRACKET
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * ....
     * ....
     * .@..
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ...@
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * .@..
     */
0, 4, 1, 2, 6, 33, 34, 66, 34, 34, 1,

    /* 126 [~] TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 2
     * ......
     * ......
     * ..@@.@
     * .@.@@.
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     */
0, 6, 2, 2, 2, 171, 1,

    /* 127 
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 3
     * Data length = 5
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
0, 4, 1, 3, 5, 51, 51, 51, 51, 3,

    /* 128 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 129 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 130 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 131 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 132 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 133 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 134 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 135 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 136 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 137 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 138 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 139 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 140 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 141 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 142 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 143 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 144 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 145 [‘] LEFT SINGLE QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 1
     * ..
     * ..
     * .@
     * .@
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     */
0, 2, 1, 2, 1, 5,

    /* 146 [’] RIGHT SINGLE QUOTATION MARK
     * Duplicate of = 145 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ..
     * ..
     * .@
     * .@
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     */
145,

    /* 147 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 148 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 149 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 150 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 151 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 152 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 153 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 154 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 155 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 156 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 157 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 158 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 159 
     * Duplicate of = 127 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ....
     * ....
     * ....
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * .@@.
     * ....
     */
127,

    /* 160 [ ] NO-BREAK SPACE
     * Duplicate of = 32 (0 if not a duplicate)
     * Width = None
     * Pixel start X = None
     * Pixel start Y = None
     * Data length = None
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     */
32,

    /* 161 [¡] INVERTED EXCLAMATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 4
     * ...
     * ...
     * ...
     * ...
     * .@.
     * ...
     * ...
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     * .@.
     */
0, 3, 1, 4, 4, 1, 146, 36, 1,

    /* 162 [¢] CENT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 4
     * Data length = 5
     * .....
     * .....
     * .....
     * .....
     * ...@.
     * ..@@.
     * .@..@
     * .@...
     * .@...
     * .@..@
     * ..@@.
     * ..@..
     * .....
     */
0, 5, 3, 4, 5, 49, 41, 132, 100, 4,

    /* 163 [£] POUND SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@..
     * .@.@.
     * .@.@.
     * .@...
     * ..@..
     * .@@@.
     * ..@..
     * ..@..
     * .@@@@
     * .....
     * .....
     */
0, 5, 2, 2, 6, 81, 74, 16, 71, 136, 7,

    /* 164 [¤] CURRENCY SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 3
     * .....
     * .....
     * .....
     * .....
     * .@..@
     * ..@@.
     * ..@@.
     * .@..@
     * .....
     * .....
     * .....
     * .....
     * .....
     */
0, 5, 1, 4, 3, 201, 152, 4,

    /* 165 [¥] YEN SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * @@.@@
     * @...@
     * @@@@@
     * .@.@.
     * @@@@@
     * ..@..
     * ..@..
     * ..@..
     * .@@@.
     * .....
     * .....
     */
0, 5, 0, 2, 6, 59, 126, 245, 9, 33, 14,

    /* 166 [¦] BROKEN BAR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ..
     * ..
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     * .@
     * .@
     * .@
     * .@
     * .@
     */
0, 2, 1, 2, 3, 85, 81, 21,

    /* 167 [§] SECTION SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 7
     * .....
     * .....
     * ..@@.
     * .@..@
     * .@...
     * ..@..
     * .@.@.
     * .@..@
     * ..@.@
     * ...@.
     * .@..@
     * .@..@
     * ..@@.
     */
0, 5, 2, 2, 7, 147, 130, 40, 73, 145, 148, 12,

    /* 168 [¨] DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 1
     * ...
     * ...
     * @.@
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 0, 2, 1, 5,

    /* 169 [©] COPYRIGHT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * ...@@@..
     * ..@...@.
     * .@.@@@.@
     * .@.@...@
     * .@.@...@
     * .@.@@@.@
     * ..@...@.
     * ...@@@..
     * ........
     * ........
     * ........
     */
0, 8, 3, 2, 8, 135, 72, 87, 81, 81, 151, 8, 7,

    /* 170 [ª] FEMININE ORDINAL INDICATOR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * .@.
     * ..@
     * .@@
     * .@@
     * ...
     * .@@
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 2, 3, 209, 134, 1,

    /* 171 [«] LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 7
     * Data length = 3
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * ..@.@
     * .@.@.
     * .@.@.
     * ..@.@
     * .....
     * .....
     */
0, 5, 2, 7, 3, 85, 138, 2,

    /* 172 [¬] NOT SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 6
     * Data length = 2
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * .@@@@@
     * .....@
     * ......
     * ......
     * ......
     * ......
     * ......
     */
0, 6, 1, 6, 2, 31, 4,

    /* 173 SOFT HYPHEN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 7
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * .@@
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 7, 1, 3,

    /* 174 [®] REGISTERED SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 8
     * ........
     * ........
     * ...@@@..
     * ..@...@.
     * .@.@@..@
     * .@.@.@.@
     * .@.@@..@
     * .@.@.@.@
     * ..@...@.
     * ...@@@..
     * ........
     * ........
     * ........
     */
0, 8, 3, 2, 8, 135, 72, 83, 85, 83, 149, 8, 7,

    /* 175 [¯] MACRON
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 0
     * Pixel start Y = 0
     * Data length = 1
     * @@@@@
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     */
0, 5, 0, 0, 1, 31,

    /* 176 [°] DEGREE SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 1
     * ...
     * ...
     * .@.
     * @.@
     * .@.
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 2, 1, 85,

    /* 177 [±] PLUS-MINUS SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 4
     * Data length = 5
     * ......
     * ......
     * ......
     * ......
     * ...@..
     * ...@..
     * .@@@@@
     * ...@..
     * ...@..
     * ......
     * .@@@@@
     * ......
     * ......
     */
0, 6, 3, 4, 5, 65, 124, 4, 1, 124,

    /* 178 [²] SUPERSCRIPT TWO
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 2
     * ...
     * ...
     * @@.
     * ..@
     * .@.
     * @..
     * @@@
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 0, 2, 2, 163, 114,

    /* 179 [³] SUPERSCRIPT THREE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 2
     * ...
     * ...
     * @@.
     * ..@
     * .@.
     * ..@
     * @@.
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 0, 2, 2, 163, 56,

    /* 180 [´] ACUTE ACCENT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 1
     * ...
     * ...
     * ..@
     * .@.
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 2, 2, 1, 5,

    /* 181 [µ] MICRO SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 7
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * ......
     * .@..@.
     * .@..@.
     * .@..@.
     * .@@@.@
     * .@....
     * .@....
     */
0, 6, 1, 7, 4, 73, 146, 92, 65,

    /* 182 [¶] PILCROW SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@@@
     * .@@@.
     * .@@@.
     * .@@@.
     * ..@@.
     * ...@.
     * ...@.
     * ...@.
     * ...@.
     * ...@.
     * .....
     */
0, 5, 2, 2, 6, 119, 206, 49, 132, 16, 66,

    /* 183 [·] MIDDLE DOT
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 6
     * Data length = 1
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     * .@
     * ..
     * ..
     * ..
     * ..
     * ..
     * ..
     */
0, 2, 1, 6, 1, 1,

    /* 184 [¸] CEDILLA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 2
     * Pixel start Y = 11
     * Data length = 1
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     * ..@
     * .@@
     */
0, 3, 2, 11, 1, 13,

    /* 185 [¹] SUPERSCRIPT ONE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 2
     * ...
     * ...
     * .@.
     * @@.
     * .@.
     * .@.
     * @@@
     * ...
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 2, 2, 77, 58,

    /* 186 [º] MASCULINE ORDINAL INDICATOR
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 3
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ...
     * ...
     * .@@
     * .@@
     * .@@
     * .@@
     * ...
     * .@@
     * ...
     * ...
     * ...
     * ...
     * ...
     */
0, 3, 1, 2, 3, 219, 134, 1,

    /* 187 [»] RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 7
     * Data length = 3
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .....
     * .@.@.
     * ..@.@
     * ..@.@
     * .@.@.
     * .....
     * .....
     */
0, 5, 1, 7, 3, 69, 169, 2,

    /* 188 [¼] VULGAR FRACTION ONE QUARTER
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * ..@.....
     * .@@....@
     * ..@...@.
     * ..@..@..
     * .@@@@..@
     * ...@..@@
     * ..@..@.@
     * .@...@@@
     * .......@
     * ........
     * ........
     */
0, 8, 2, 2, 9, 129, 33, 17, 137, 39, 50, 169, 56, 32,

    /* 189 [½] VULGAR FRACTION ONE HALF
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * ..@.....
     * .@@....@
     * ..@...@.
     * ..@..@..
     * .@@@@@@.
     * ...@...@
     * ..@...@.
     * .@...@..
     * .....@@@
     * ........
     * ........
     */
0, 8, 2, 2, 9, 129, 33, 17, 137, 31, 34, 145, 8, 56,

    /* 190 [¾] VULGAR FRACTION THREE QUARTERS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@@.....
     * ...@...@
     * ..@...@.
     * ...@.@..
     * .@@.@..@
     * ...@..@@
     * ..@..@.@
     * .@...@@@
     * .......@
     * ........
     * ........
     */
0, 8, 1, 2, 9, 3, 68, 34, 20, 75, 100, 82, 113, 64,

    /* 191 [¿] INVERTED QUESTION MARK
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 4
     * Data length = 6
     * .....
     * .....
     * .....
     * .....
     * ..@..
     * .....
     * ..@..
     * ..@..
     * .@...
     * @....
     * @..@.
     * @..@.
     * .@@..
     */
0, 5, 2, 4, 6, 1, 132, 136, 144, 146, 1,

    /* 192 [À] LATIN CAPITAL LETTER A WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 11
     * ...@....
     * ....@...
     * ........
     * ....@...
     * ....@...
     * ...@.@..
     * ...@.@..
     * ..@...@.
     * ..@@@@@.
     * ..@...@.
     * .@@@.@@@
     * ........
     * ........
     */
0, 8, 3, 0, 11, 1, 2, 0, 2, 2, 5, 133, 136, 143, 200, 29,

    /* 193 [Á] LATIN CAPITAL LETTER A WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 5
     * Pixel start Y = 0
     * Data length = 11
     * .....@..
     * ....@...
     * ........
     * ....@...
     * ....@...
     * ...@.@..
     * ...@.@..
     * ..@...@.
     * ..@@@@@.
     * ..@...@.
     * .@@@.@@@
     * ........
     * ........
     */
0, 8, 5, 0, 11, 129, 0, 128, 128, 64, 65, 33, 226, 35, 114, 7,

    /* 194 [Â] LATIN CAPITAL LETTER A WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 11
     * ....@...
     * ...@.@..
     * ........
     * ....@...
     * ....@...
     * ...@.@..
     * ...@.@..
     * ..@...@.
     * ..@@@@@.
     * ..@...@.
     * .@@@.@@@
     * ........
     * ........
     */
0, 8, 4, 0, 11, 129, 2, 0, 1, 129, 130, 66, 196, 71, 228, 14,

    /* 195 [Ã] LATIN CAPITAL LETTER A WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 11
     * ...@@.@.
     * ..@.@@..
     * ....@...
     * ....@...
     * ...@.@..
     * ...@.@..
     * ...@.@..
     * ..@...@.
     * ..@@@@@.
     * ..@...@.
     * .@@@.@@@
     * ........
     * ........
     */
0, 8, 3, 0, 11, 139, 6, 2, 2, 5, 5, 133, 136, 143, 200, 29,

    /* 196 [Ä] LATIN CAPITAL LETTER A WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 11
     * ..@...@.
     * ........
     * ....@...
     * ....@...
     * ...@.@..
     * ...@.@..
     * ...@.@..
     * ..@...@.
     * ..@@@@@.
     * ..@...@.
     * .@@@.@@@
     * ........
     * ........
     */
0, 8, 2, 0, 11, 17, 0, 4, 4, 10, 10, 10, 17, 31, 145, 59,

    /* 197 [Å] LATIN CAPITAL LETTER A WITH RING ABOVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 11
     * ....@...
     * ...@.@..
     * ....@...
     * ....@...
     * ...@.@..
     * ...@.@..
     * ...@.@..
     * ..@...@.
     * ..@@@@@.
     * ..@...@.
     * .@@@.@@@
     * ........
     * ........
     */
0, 8, 4, 0, 11, 129, 2, 1, 129, 130, 130, 66, 196, 71, 228, 14,

    /* 198 [Æ] LATIN CAPITAL LETTER AE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 9
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 10
     * .........
     * .........
     * ...@@@@@@
     * ....@@..@
     * ....@@...
     * ...@.@.@.
     * ...@.@@@.
     * ...@.@.@.
     * ..@@@@...
     * ..@..@..@
     * .@@.@@@@@
     * .........
     * .........
     */
0, 9, 3, 2, 10, 63, 76, 24, 168, 208, 161, 226, 65, 210, 62,

    /* 199 [Ç] LATIN CAPITAL LETTER C WITH CEDILLA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 9
     * .......
     * .......
     * ...@@@@
     * ..@...@
     * ..@....
     * ..@....
     * ..@....
     * ..@....
     * ..@....
     * ..@...@
     * ...@@@.
     * ....@..
     * ...@@..
     */
0, 7, 3, 2, 9, 79, 36, 16, 8, 4, 2, 17, 7, 193,

    /* 200 [È] LATIN CAPITAL LETTER E WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 10
     * ..@....
     * ...@...
     * .@@@@@.
     * ..@..@.
     * ..@....
     * ..@.@..
     * ..@@@..
     * ..@.@..
     * ..@....
     * ..@..@.
     * .@@@@@.
     * .......
     * .......
     */
0, 7, 2, 0, 10, 1, 225, 35, 17, 40, 28, 10, 129, 228, 3,

    /* 201 [É] LATIN CAPITAL LETTER E WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 9
     * ....@..
     * ...@...
     * .@@@@@.
     * ..@..@.
     * ..@....
     * ..@.@..
     * ..@@@..
     * ..@.@..
     * ..@....
     * ..@..@.
     * .@@@@@.
     * .......
     * .......
     */
0, 7, 4, 0, 9, 65, 248, 72, 4, 10, 135, 66, 32, 249,

    /* 202 [Ê] LATIN CAPITAL LETTER E WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 10
     * ...@...
     * ..@.@..
     * .@@@@@.
     * ..@..@.
     * ..@....
     * ..@.@..
     * ..@@@..
     * ..@.@..
     * ..@....
     * ..@..@.
     * .@@@@@.
     * .......
     * .......
     */
0, 7, 3, 0, 10, 65, 241, 145, 8, 20, 14, 133, 64, 242, 1,

    /* 203 [Ë] LATIN CAPITAL LETTER E WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 7
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 10
     * ..@..@.
     * .......
     * .@@@@@.
     * ..@..@.
     * ..@....
     * ..@.@..
     * ..@@@..
     * ..@.@..
     * ..@....
     * ..@..@.
     * .@@@@@.
     * .......
     * .......
     */
0, 7, 2, 0, 10, 9, 224, 35, 17, 40, 28, 10, 129, 228, 3,

    /* 204 [Ì] LATIN CAPITAL LETTER I WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 0
     * Data length = 6
     * .@..
     * ..@.
     * .@@@
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * .@@@
     * ....
     * ....
     */
0, 4, 1, 0, 6, 33, 39, 34, 34, 34, 7,

    /* 205 [Í] LATIN CAPITAL LETTER I WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 6
     * ...@
     * ..@.
     * .@@@
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * .@@@
     * ....
     * ....
     */
0, 4, 3, 0, 6, 201, 137, 136, 136, 200, 1,

    /* 206 [Î] LATIN CAPITAL LETTER I WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 6
     * ..@.
     * .@.@
     * ....
     * .@@@
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * .@@@
     * ....
     * ....
     */
0, 4, 2, 0, 6, 41, 56, 17, 17, 145, 3,

    /* 207 [Ï] LATIN CAPITAL LETTER I WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 4
     * Pixel start X = 1
     * Pixel start Y = 0
     * Data length = 6
     * .@.@
     * ....
     * .@@@
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * ..@.
     * .@@@
     * ....
     * ....
     */
0, 4, 1, 0, 6, 5, 39, 34, 34, 34, 7,

    /* 208 [Ð] LATIN CAPITAL LETTER ETH
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * .@@@@...
     * ..@..@..
     * ..@...@.
     * ..@...@.
     * .@@@..@.
     * ..@...@.
     * ..@...@.
     * ..@..@..
     * .@@@@...
     * ........
     * ........
     */
0, 8, 1, 2, 9, 15, 18, 34, 34, 39, 34, 34, 18, 15,

    /* 209 [Ñ] LATIN CAPITAL LETTER N WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 11
     * ...@@.@.
     * ..@.@@..
     * .@@..@@@
     * ..@...@.
     * ..@@..@.
     * ..@@..@.
     * ..@.@.@.
     * ..@.@.@.
     * ..@..@@.
     * ..@..@@.
     * .@@@..@.
     * ........
     * ........
     */
0, 8, 3, 0, 11, 139, 198, 156, 136, 137, 137, 138, 138, 140, 204, 9,

    /* 210 [Ò] LATIN CAPITAL LETTER O WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 11
     * ...@....
     * ....@...
     * ...@@@..
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ...@@@..
     * ........
     * ........
     */
0, 8, 3, 0, 11, 1, 2, 135, 136, 136, 136, 136, 136, 136, 8, 7,

    /* 211 [Ó] LATIN CAPITAL LETTER O WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 5
     * Pixel start Y = 0
     * Data length = 11
     * .....@..
     * ....@...
     * ...@@@..
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ...@@@..
     * ........
     * ........
     */
0, 8, 5, 0, 11, 129, 192, 33, 34, 34, 34, 34, 34, 34, 194, 1,

    /* 212 [Ô] LATIN CAPITAL LETTER O WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 11
     * ....@...
     * ...@.@..
     * ...@@@..
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ...@@@..
     * ........
     * ........
     */
0, 8, 4, 0, 11, 129, 130, 67, 68, 68, 68, 68, 68, 68, 132, 3,

    /* 213 [Õ] LATIN CAPITAL LETTER O WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 11
     * ...@@.@.
     * ..@.@@..
     * ...@@@..
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ...@@@..
     * ........
     * ........
     */
0, 8, 3, 0, 11, 139, 6, 135, 136, 136, 136, 136, 136, 136, 8, 7,

    /* 214 [Ö] LATIN CAPITAL LETTER O WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 11
     * ..@...@.
     * ........
     * ...@@@..
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ...@@@..
     * ........
     * ........
     */
0, 8, 2, 0, 11, 17, 0, 14, 17, 17, 17, 17, 17, 17, 17, 14,

    /* 215 [×] MULTIPLICATION SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 4
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * .@...@
     * ..@.@.
     * ...@..
     * ..@.@.
     * .@...@
     * ......
     * ......
     * ......
     * ......
     */
0, 6, 1, 4, 4, 145, 66, 40, 17,

    /* 216 [Ø] LATIN CAPITAL LETTER O WITH STROKE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 9
     * ........
     * ........
     * ...@@@@.
     * ..@...@.
     * ..@..@@.
     * ..@..@@.
     * ..@.@.@.
     * ..@@..@.
     * ..@@..@.
     * ..@...@.
     * ..@@@@..
     * ........
     * ........
     */
0, 8, 3, 2, 9, 143, 136, 140, 140, 138, 137, 137, 136, 7,

    /* 217 [Ù] LATIN CAPITAL LETTER U WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 3
     * Pixel start Y = 0
     * Data length = 11
     * ...@....
     * ....@...
     * .@@@.@@@
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ...@@@..
     * ........
     * ........
     */
0, 8, 3, 0, 11, 1, 194, 157, 136, 136, 136, 136, 136, 136, 8, 7,

    /* 218 [Ú] LATIN CAPITAL LETTER U WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 5
     * Pixel start Y = 0
     * Data length = 11
     * .....@..
     * ....@...
     * .@@@.@@@
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ...@@@..
     * ........
     * ........
     */
0, 8, 5, 0, 11, 129, 112, 39, 34, 34, 34, 34, 34, 34, 194, 1,

    /* 219 [Û] LATIN CAPITAL LETTER U WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 4
     * Pixel start Y = 0
     * Data length = 11
     * ....@...
     * ...@.@..
     * .@@@.@@@
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ...@@@..
     * ........
     * ........
     */
0, 8, 4, 0, 11, 129, 226, 78, 68, 68, 68, 68, 68, 68, 132, 3,

    /* 220 [Ü] LATIN CAPITAL LETTER U WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 0
     * Data length = 11
     * ..@...@.
     * ........
     * .@@@.@@@
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ..@...@.
     * ...@@@..
     * ........
     * ........
     */
0, 8, 2, 0, 11, 17, 128, 59, 17, 17, 17, 17, 17, 17, 17, 14,

    /* 221 [Ý] LATIN CAPITAL LETTER Y WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 5
     * Pixel start Y = 0
     * Data length = 11
     * .....@..
     * ....@...
     * .@@@.@@@
     * ..@...@.
     * ..@...@.
     * ...@.@..
     * ...@.@..
     * ....@...
     * ....@...
     * ....@...
     * ...@@@..
     * ........
     * ........
     */
0, 8, 5, 0, 11, 129, 112, 39, 34, 66, 65, 129, 128, 128, 192, 1,

    /* 222 [Þ] LATIN CAPITAL LETTER THORN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 7
     * ......
     * ......
     * .@@...
     * ..@...
     * ..@@@.
     * ..@..@
     * ..@..@
     * ..@..@
     * ..@@@.
     * ..@...
     * .@@@..
     * ......
     * ......
     */
0, 6, 1, 2, 7, 131, 224, 72, 146, 228, 8, 7,

    /* 223 [ß] LATIN SMALL LETTER SHARP S
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@@.
     * .@..@
     * .@..@
     * .@..@
     * .@.@.
     * .@..@
     * .@..@
     * .@..@
     * .@.@.
     * .....
     * .....
     */
0, 5, 2, 2, 6, 147, 82, 42, 41, 165, 2,

    /* 224 [à] LATIN SMALL LETTER A WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@..
     * ...@.
     * .....
     * ..@@.
     * ....@
     * ..@@@
     * .@..@
     * .@..@
     * ..@@@
     * .....
     * .....
     */
0, 5, 2, 2, 6, 65, 128, 65, 46, 37, 7,

    /* 225 [á] LATIN SMALL LETTER A WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ...@.
     * ..@..
     * .....
     * ..@@.
     * ....@
     * ..@@@
     * .@..@
     * .@..@
     * ..@@@
     * .....
     * .....
     */
0, 5, 3, 2, 6, 17, 192, 32, 151, 146, 3,

    /* 226 [â] LATIN SMALL LETTER A WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ...@.
     * ..@.@
     * .....
     * ..@@.
     * ....@
     * ..@@@
     * .@..@
     * .@..@
     * ..@@@
     * .....
     * .....
     */
0, 5, 3, 2, 6, 81, 192, 32, 151, 146, 3,

    /* 227 [ã] LATIN SMALL LETTER A WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@.@
     * .@.@.
     * .....
     * ..@@.
     * ....@
     * ..@@@
     * .@..@
     * .@..@
     * ..@@@
     * .....
     * .....
     */
0, 5, 2, 2, 6, 85, 128, 65, 46, 37, 7,

    /* 228 [ä] LATIN SMALL LETTER A WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 3
     * Data length = 5
     * .....
     * .....
     * .....
     * ..@.@
     * .....
     * ..@@.
     * ....@
     * ..@@@
     * .@..@
     * .@..@
     * ..@@@
     * .....
     * .....
     */
0, 5, 2, 3, 5, 5, 12, 114, 41, 57,

    /* 229 [å] LATIN SMALL LETTER A WITH RING ABOVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 1
     * Data length = 6
     * .....
     * ...@.
     * ..@.@
     * ...@.
     * .....
     * ..@@.
     * ....@
     * ..@@@
     * .@..@
     * .@..@
     * ..@@@
     * .....
     * .....
     */
0, 5, 3, 1, 6, 81, 4, 24, 228, 82, 114,

    /* 230 [æ] LATIN SMALL LETTER AE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 8
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 6
     * ........
     * ........
     * ........
     * ........
     * ........
     * ..@@.@@.
     * ....@..@
     * ..@@@@@@
     * .@..@...
     * .@..@..@
     * ..@@.@@.
     * ........
     * ........
     */
0, 8, 2, 5, 6, 27, 36, 191, 132, 36, 27,

    /* 231 [ç] LATIN SMALL LETTER C WITH CEDILLA
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 5
     * .....
     * .....
     * .....
     * .....
     * .....
     * ..@@.
     * .@..@
     * .@...
     * .@...
     * .@..@
     * ..@@.
     * ...@.
     * ..@@.
     */
0, 5, 2, 5, 5, 147, 66, 72, 134, 24,

    /* 232 [è] LATIN SMALL LETTER E WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@..
     * ...@.
     * .....
     * ..@@.
     * .@..@
     * .@@@@
     * .@...
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 2, 2, 6, 65, 128, 73, 47, 36, 3,

    /* 233 [é] LATIN SMALL LETTER E WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ...@.
     * ..@..
     * .....
     * ..@@.
     * .@..@
     * .@@@@
     * .@...
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 3, 2, 6, 17, 192, 164, 23, 146, 1,

    /* 234 [ê] LATIN SMALL LETTER E WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@@.
     * .@..@
     * .....
     * ..@@.
     * .@..@
     * .@@@@
     * .@...
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 2, 2, 6, 147, 128, 73, 47, 36, 3,

    /* 235 [ë] LATIN SMALL LETTER E WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 3
     * Data length = 5
     * .....
     * .....
     * .....
     * .@..@
     * .....
     * ..@@.
     * .@..@
     * .@@@@
     * .@...
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 1, 3, 5, 9, 152, 244, 66, 50,

    /* 236 [ì] LATIN SMALL LETTER I WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 3
     * ..
     * ..
     * @.
     * .@
     * ..
     * @@
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     * ..
     */
0, 2, 0, 2, 3, 201, 170, 2,

    /* 237 [í] LATIN SMALL LETTER I WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 3
     * ..
     * ..
     * .@
     * @.
     * ..
     * @@
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     * ..
     */
0, 2, 1, 2, 3, 99, 85, 1,

    /* 238 [î] LATIN SMALL LETTER I WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 3
     * ..
     * ..
     * @@
     * ..
     * ..
     * @@
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     * ..
     */
0, 2, 0, 2, 3, 195, 170, 2,

    /* 239 [ï] LATIN SMALL LETTER I WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 2
     * Pixel start X = 0
     * Pixel start Y = 3
     * Data length = 2
     * ..
     * ..
     * ..
     * @@
     * ..
     * @@
     * .@
     * .@
     * .@
     * .@
     * .@
     * ..
     * ..
     */
0, 2, 0, 3, 2, 179, 170,

    /* 240 [ð] LATIN SMALL LETTER ETH
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * .@.@.
     * ..@..
     * .@.@.
     * ....@
     * ..@@@
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 1, 2, 6, 69, 20, 228, 82, 74, 6,

    /* 241 [ñ] LATIN SMALL LETTER N WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@.@
     * .@.@.
     * .....
     * @.@@.
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * .....
     * .....
     */
0, 5, 2, 2, 6, 85, 160, 73, 41, 165, 4,

    /* 242 [ò] LATIN SMALL LETTER O WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@..
     * ...@.
     * .....
     * ..@@.
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 2, 2, 6, 65, 128, 73, 41, 37, 3,

    /* 243 [ó] LATIN SMALL LETTER O WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ...@.
     * ..@..
     * .....
     * ..@@.
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 3, 2, 6, 17, 192, 164, 148, 146, 1,

    /* 244 [ô] LATIN SMALL LETTER O WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@@.
     * .@..@
     * .....
     * ..@@.
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 2, 2, 6, 147, 128, 73, 41, 37, 3,

    /* 245 [õ] LATIN SMALL LETTER O WITH TILDE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@.@
     * .@.@.
     * .....
     * ..@@.
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 2, 2, 6, 85, 128, 73, 41, 37, 3,

    /* 246 [ö] LATIN SMALL LETTER O WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 3
     * Data length = 5
     * .....
     * .....
     * .....
     * .@..@
     * .....
     * ..@@.
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * .....
     * .....
     */
0, 5, 1, 3, 5, 9, 152, 148, 82, 50,

    /* 247 [÷] DIVISION SIGN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 6
     * Pixel start X = 3
     * Pixel start Y = 4
     * Data length = 4
     * ......
     * ......
     * ......
     * ......
     * ...@..
     * ......
     * .@@@@@
     * ......
     * ...@..
     * ......
     * ......
     * ......
     * ......
     */
0, 6, 3, 4, 4, 1, 124, 0, 1,

    /* 248 [ø] LATIN SMALL LETTER O WITH STROKE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 5
     * Data length = 4
     * .....
     * .....
     * .....
     * .....
     * .....
     * ..@@@
     * .@.@@
     * .@.@@
     * .@@.@
     * .@@.@
     * .@@@.
     * .....
     * .....
     */
0, 5, 2, 5, 4, 215, 218, 90, 7,

    /* 249 [ù] LATIN SMALL LETTER U WITH GRAVE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * .@...
     * ..@..
     * .....
     * @@.@@
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@@
     * .....
     * .....
     */
0, 5, 1, 2, 6, 65, 192, 150, 82, 74, 14,

    /* 250 [ú] LATIN SMALL LETTER U WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ...@.
     * ..@..
     * .....
     * @@.@@
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@@
     * .....
     * .....
     */
0, 5, 3, 2, 6, 17, 176, 165, 148, 146, 3,

    /* 251 [û] LATIN SMALL LETTER U WITH CIRCUMFLEX
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 2
     * Pixel start Y = 2
     * Data length = 6
     * .....
     * .....
     * ..@..
     * .@.@.
     * .....
     * @@.@@
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@@
     * .....
     * .....
     */
0, 5, 2, 2, 6, 81, 96, 75, 41, 37, 7,

    /* 252 [ü] LATIN SMALL LETTER U WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 3
     * Data length = 5
     * .....
     * .....
     * .....
     * .@..@
     * .....
     * @@.@@
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@@
     * .....
     * .....
     */
0, 5, 1, 3, 5, 9, 182, 148, 82, 114,

    /* 253 [ý] LATIN SMALL LETTER Y WITH ACUTE
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 3
     * Pixel start Y = 2
     * Data length = 7
     * .....
     * .....
     * ...@.
     * ..@..
     * .....
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * ..@..
     * ..@..
     * .@...
     */
0, 5, 3, 2, 7, 17, 32, 165, 148, 140, 16, 1,

    /* 254 [þ] LATIN SMALL LETTER THORN
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 0
     * Pixel start Y = 2
     * Data length = 7
     * .....
     * .....
     * @@...
     * .@...
     * .@...
     * .@@@.
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * .@@@.
     * .@...
     * @@@..
     */
0, 5, 0, 2, 7, 67, 8, 39, 165, 148, 78, 28,

    /* 255 [ÿ] LATIN SMALL LETTER Y WITH DIAERESIS
     * Duplicate of = 0 (0 if not a duplicate)
     * Width = 5
     * Pixel start X = 1
     * Pixel start Y = 3
     * Data length = 6
     * .....
     * .....
     * .....
     * .@..@
     * .....
     * .@..@
     * .@..@
     * .@..@
     * .@..@
     * ..@@.
     * ..@..
     * ..@..
     * .@...
     */
0, 5, 1, 3, 6, 9, 164, 148, 146, 17, 34,

};
